/**
 * 🔐 Auth Middleware — teamflow
 * Auto-generated by Backend Factory
 */

import { verifyToken } from '../services/authService.js';

export const VALID_ROLES = ['admin', 'guest', 'member', 'owner', 'user'];

// Extract token from httpOnly cookie (browser clients) or Bearer header (SDK/API clients)
function extractToken(req) {
  if (req.cookies && req.cookies.access_token) return req.cookies.access_token;
  const header = req.headers['authorization'];
  if (header && header.startsWith('Bearer ')) return header.slice(7);
  return null;
}

export function requireAuth(req, res, next) {
  const token = extractToken(req);
  if (!token) {
    return res.status(401).json({ code: 'AUTH_MISSING_TOKEN', message: 'Authentication required' });
  }
  const { valid, payload, error } = verifyToken(token);
  if (!valid) {
    return res.status(401).json({ code: 'AUTH_INVALID_TOKEN', message: error || 'Token invalid or expired' });
  }
  req.context = { user_id: payload.sub, tenant_id: payload.tenant_id, role: payload.role, email: payload.email, locale: payload.locale || null };
  next();
}

export function requireRole(...allowedRoles) {
  return (req, res, next) => {
    if (!req.context) return res.status(401).json({ code: 'AUTH_NO_CONTEXT', message: 'requireAuth must run first' });
    if (!allowedRoles.includes(req.context.role)) {
      return res.status(403).json({ code: 'AUTH_FORBIDDEN', message: 'Role ' + req.context.role + ' not allowed. Need: ' + allowedRoles.join(' or ') });
    }
    next();
  };
}

export function optionalAuth(req, res, next) {
  const token = extractToken(req);
  if (!token) { req.context = null; return next(); }
  const { valid, payload } = verifyToken(token);
  req.context = valid ? { user_id: payload.sub, tenant_id: payload.tenant_id, role: payload.role, email: payload.email } : null;
  next();
}
