/**
 * 🚨 Error Handling Middleware
 * Auto-generated by Backend Factory
 */

import { AppError } from '../errors/AppError.js';

/**
 * Add request ID to every request
 */
let requestCounter = 0;
export function requestIdMiddleware(req, res, next) {
  req.requestId = req.headers['x-request-id'] || 'req_' + Date.now() + '_' + (++requestCounter);
  res.setHeader('X-Request-Id', req.requestId);
  next();
}

/**
 * Log every request with timing
 */
export function requestLogger(req, res, next) {
  const start = Date.now();
  const originalEnd = res.end;

  res.end = function(...args) {
    const duration = Date.now() - start;
    const level = res.statusCode >= 500 ? 'ERROR' : res.statusCode >= 400 ? 'WARN' : 'INFO';
    console.log(
      '[' + level + '] ' + req.method + ' ' + req.path +
      ' → ' + res.statusCode +
      ' (' + duration + 'ms)' +
      ' [' + req.requestId + ']'
    );
    originalEnd.apply(this, args);
  };

  next();
}

// ─── Error Rate Tracking ────────────────
const errorStats = {
  total: 0,
  byCode: {},
  byStatus: {},
  recent: [],
};

export function getErrorStats() {
  return {
    ...errorStats,
    recent: errorStats.recent.slice(-20),
  };
}

/**
 * Handle 404 — route not found
 */
export function notFoundHandler(req, res, next) {
  res.status(404).json({
    error: {
      code: 'ROUTE_NOT_FOUND',
      message: req.method + ' ' + req.path + ' does not exist',
      status: 404,
      hint: 'Check the API documentation at GET /docs for available endpoints.',
      timestamp: new Date().toISOString(),
    },
  });
}

/**
 * Global error handler
 * Must be registered LAST with app.use()
 */
export function errorHandler(err, req, res, next) {
  // Track error stats
  errorStats.total++;

  if (err instanceof AppError) {
    // Known application error
    errorStats.byCode[err.code] = (errorStats.byCode[err.code] || 0) + 1;
    errorStats.byStatus[err.status] = (errorStats.byStatus[err.status] || 0) + 1;
    errorStats.recent.push({
      code: err.code,
      message: err.message,
      path: req.path,
      timestamp: err.timestamp,
    });

    // Add request ID
    err.requestId = req.requestId;

    // Log (skip 4xx in production)
    if (err.status >= 500 || process.env.NODE_ENV !== 'production') {
      console.error('[ERROR] ' + err.code + ': ' + err.message + ' [' + req.requestId + ']');
    }

    return res.status(err.status).json(err.toJSON());
  }

  // Malformed JSON body (body-parser): the client sent bad bytes — clean 400.
  if (err && (err.type === 'entity.parse.failed' || (err instanceof SyntaxError && 'body' in err))) {
    errorStats.byCode['INVALID_JSON'] = (errorStats.byCode['INVALID_JSON'] || 0) + 1;
    errorStats.byStatus[400] = (errorStats.byStatus[400] || 0) + 1;
    return res.status(400).json({ error: { code: 'INVALID_JSON', message: 'Request body is not valid JSON', status: 400, requestId: req.requestId, timestamp: new Date().toISOString() } });
  }

  // Deliberate service-layer errors: honor err.statusCode / err.status (4xx/5xx).
  const _st = (err && Number.isInteger(err.statusCode)) ? err.statusCode : ((err && Number.isInteger(err.status)) ? err.status : null);
  if (_st !== null && _st >= 400 && _st < 600) {
    const _code = err.code || (_st >= 500 ? 'UPSTREAM_ERROR' : 'REQUEST_ERROR');
    errorStats.byCode[_code] = (errorStats.byCode[_code] || 0) + 1;
    errorStats.byStatus[_st] = (errorStats.byStatus[_st] || 0) + 1;
    if (_st >= 500 || process.env.NODE_ENV !== 'production') {
      console.error('[ERROR] ' + _st + ' ' + err.message + ' [' + req.requestId + ']');
    }
    return res.status(_st).json({ error: { code: _code, message: err.message, status: _st, requestId: req.requestId, timestamp: new Date().toISOString() } });
  }

  // Unknown error — don't leak details
  errorStats.byCode['UNKNOWN'] = (errorStats.byCode['UNKNOWN'] || 0) + 1;
  errorStats.byStatus[500] = (errorStats.byStatus[500] || 0) + 1;

  console.error('[FATAL] Unhandled error:', err.message, err.stack);

  const response = {
    error: {
      code: 'INTERNAL_ERROR',
      message: 'An unexpected error occurred',
      status: 500,
      requestId: req.requestId,
      timestamp: new Date().toISOString(),
    },
  };

  // Debug aid without internals — full stack is in the server log, not the wire
  if (process.env.NODE_ENV !== 'production') {
    response.error.debug = { name: err.name, requestId: req.requestId };
  }

  res.status(500).json(response);
}
