/**
 * 🧹 Input Sanitizer Middleware
 * Strips XSS vectors from all string inputs.
 * Auto-generated by Forgx
 *
 * Mount BEFORE routes:
 *   app.use(express.json());
 *   app.use(sanitizeInput);  // here
 *   app.use('/api', routes);
 */

const XSS_PATTERNS = [
  /<script[^>]*>/gi,
  /<\/script>/gi,
  /<iframe[^>]*>/gi,
  /<object[^>]*>/gi,
  /<embed[^>]*>/gi,
  /<link[^>]*>/gi,
  /javascript\s*:/gi,
  /vbscript\s*:/gi,
  /data\s*:\s*text\/html/gi,
  /on\w+\s*=\s*['"]?[^'"]*['"]?/gi,
  /expression\s*\(/gi,
  /eval\s*\(/gi,
  /Function\s*\(/gi,
  /setTimeout\s*\(/gi,
  /setInterval\s*\(/gi,
  /\{\{.*constructor/gi,
];

function sanitizeString(value) {
  if (typeof value !== 'string') return value;
  let clean = value;
  for (const pattern of XSS_PATTERNS) {
    clean = clean.replace(pattern, '');
  }
  clean = clean.replace(/\0/g, '');
  return clean;
}

function sanitizeDeep(obj) {
  if (typeof obj === 'string') return sanitizeString(obj);
  if (Array.isArray(obj)) return obj.map(sanitizeDeep);
  if (obj && typeof obj === 'object') {
    const cleaned = {};
    for (const [key, value] of Object.entries(obj)) {
      const cleanKey = sanitizeString(key);
      if (cleanKey === '__proto__' || cleanKey === 'constructor' || cleanKey === 'prototype') continue;
      cleaned[cleanKey] = sanitizeDeep(value);
    }
    return cleaned;
  }
  return obj;
}

const SKIP_FIELDS = new Set([
  'password', 'password_hash', 'token', 'refresh_token',
  'api_key', 'webhook_secret', 'stripe_signature',
]);

export function sanitizeInput(req, res, next) {
  if (!req.body && !req.query) return next();
  if (req.body && typeof req.body === 'object') {
    for (const [key, value] of Object.entries(req.body)) {
      if (SKIP_FIELDS.has(key)) continue;
      req.body[key] = sanitizeDeep(value);
    }
  }
  if (req.query && typeof req.query === 'object') {
    for (const [key, value] of Object.entries(req.query)) {
      if (typeof value === 'string') {
        req.query[key] = sanitizeString(value);
      }
    }
  }
  next();
}

export { sanitizeString, sanitizeDeep };
