/**
 * 🔐 Auth Routes — teamflow
 * POST /auth/signup | login | refresh | logout
 * GET  /auth/me
 * Auto-generated by Backend Factory
 */

import express from 'express';
import crypto  from 'crypto';
import { pool } from '../db/pg.js';
import { hashPassword, verifyPassword, signToken, createRefreshToken, rotateRefreshToken, revokeRefreshToken, VALID_ROLES } from '../services/authService.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';

const router = express.Router();

const PIN_MAX_ATTEMPTS   = parseInt(process.env.PIN_MAX_ATTEMPTS   || '3');
const PIN_LOCKOUT_MINS   = parseInt(process.env.PIN_LOCKOUT_MINS   || '5');

// ─── Auth audit logger ────────────────────────────────────────────────────
function logAuthEvent(req, eventType, { userId=null, tenantId=null, email=null, failureReason=null, metadata={} } = {}) {
  const ip       = (req.ip || req.connection?.remoteAddress || 'unknown').replace('::ffff:', '');
  const ua       = (req.headers['user-agent'] || '').slice(0, 500);
  const lang     = (req.headers['accept-language'] || '').slice(0, 50);
  const ipSubnet = ip.split('.').slice(0, 3).join('.');
  const deviceFp = crypto.createHash('sha256')
    .update(ua + '|' + ipSubnet + '|' + lang).digest('hex').slice(0, 64);
  pool.query(
    `INSERT INTO auth_audit_log (tenant_id,user_id,email,event_type,ip_address,user_agent,device_fingerprint,failure_reason,metadata)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
    [tenantId, userId, email, eventType, ip, ua, deviceFp, failureReason, JSON.stringify(metadata)]
  ).catch(err => console.warn('[auth-audit] Write failed:', err.message));
}

router.post('/signup', async (req, res) => {
  try {
    const { email, password, first_name, last_name, role: requestedRole } = req.body || {};
    if (!email || !password) return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'email and password required' });
    if (password.length < 8 || !/[A-Z]/.test(password) || !/[0-9]/.test(password) || !/[^A-Za-z0-9]/.test(password)) {
      return res.status(400).json({ code: 'WEAK_PASSWORD', message: 'Password needs 8+ chars, 1 uppercase, 1 number, 1 special character' });
    }
    // SECURITY: tenant_id is ALWAYS server-generated. Trusting a client header
    // (x-tenant-id) let anyone silently join — or hijack — an existing tenant.
    const { randomUUID } = await import('crypto');
    const tenant_id = randomUUID();
    if (password.length < 8) return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'password min 8 chars' });
    // Bootstrap (subject-model or workspace-owner domain): signup mints a NEW
    // tenant — there is no join-by-header path — so its FIRST user becomes the
    // tenant owner/admin (founder). Additional members are added by an existing
    // admin, or join an existing tenant through the invite flow — never as a
    // self-registered elevated role here.
    const { rows: bootstrapExisting } = await pool.query('SELECT 1 FROM users WHERE tenant_id = $1 AND deleted_at IS NULL LIMIT 1', [tenant_id]);
    const role = bootstrapExisting.length === 0 ? 'owner' : 'member';

    // Global email uniqueness (Item 5): reject if the email is registered in ANY tenant.
    const { rows: existing } = await pool.query('SELECT id FROM users WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL', [email]);
    if (existing.length > 0) return res.status(409).json({ code: 'EMAIL_TAKEN', message: 'Email already registered' });

    const password_hash = await hashPassword(password);
    const { rows } = await pool.query(
      `INSERT INTO users (email, password_hash, tenant_id, role, first_name, last_name)
       VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, email, tenant_id, role, first_name, last_name`,
      [email.toLowerCase(), password_hash, tenant_id, role, first_name || null, last_name || null]
    );
    const user = rows[0];
    const access_token = signToken({ userId: user.id, tenantId: user.tenant_id, role: user.role, email: user.email });
    const refresh_token = await createRefreshToken(user.id, user.tenant_id);
    const isProd = process.env.NODE_ENV === 'production';
    res.cookie('access_token', access_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 15 * 60 * 1000 });
    res.cookie('refresh_token', refresh_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 30 * 24 * 60 * 60 * 1000, path: '/auth/refresh' });
    res.status(201).json({ user });
  } catch (err) {
    // Unique-violation on the global email index (race with a concurrent signup) → 409
    if (err && err.code === '23505') return res.status(409).json({ code: 'EMAIL_TAKEN', message: 'Email already registered' });
    res.status(500).json({ code: 'SERVER_ERROR', message: err.message });
  }
});

router.post('/login', async (req, res) => {
  try {
    // Global email uniqueness (Item 5) means email alone identifies the account —
    // the caller no longer needs to know their tenant_id to log in.
    const { email, password } = req.body || {};
    if (!email || !password) return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'email and password required' });

    // ââ Brute force protection ââ
    const ip = req.ip || req.connection.remoteAddress || 'unknown';
    const lockKey = 'login:' + ip + ':' + email.toLowerCase();
    const lockResult = await pool.query(
      `SELECT COUNT(*) as attempts, MAX(created_at) as last_attempt FROM login_attempts WHERE ip_address = $1 AND email = $2 AND success = false AND created_at > NOW() - INTERVAL '15 minutes'`,
      [ip, email.toLowerCase()]
    ).catch(() => ({ rows: [{ attempts: 0 }] }));
    const attempts = parseInt(lockResult.rows[0]?.attempts || 0);
    if (attempts >= 5) {
      return res.status(429).json({
        code: 'ACCOUNT_LOCKED',
        message: 'Too many failed attempts. Try again in 15 minutes.',
        retryAfter: 900,
      });
    }

    const { rows } = await pool.query(
      'SELECT id, email, password_hash, role, tenant_id, first_name, last_name, is_active, last_login_at FROM users WHERE LOWER(email) = LOWER($1) AND is_active = true AND deleted_at IS NULL',
      [email]
    );
    const user = rows[0];
    // constant-time: always run hash even if user not found (prevents timing attacks).
    // Dummy hash is a STRUCTURALLY VALID salt:32-byte-hex so the compare runs like a
    // real one (verifyPassword also length-guards, so a bad hash can never crash).
    const dummyHash = 'ffffffffffffffffffffffffffffffff:' + 'f'.repeat(64);
    const passwordOk = user
      ? await verifyPassword(password, user.password_hash)
      : await verifyPassword(password, dummyHash).catch(() => false);
    if (!user || !passwordOk) {
      // Track failed attempt
      await pool.query(
        'INSERT INTO login_attempts (ip_address, email, success) VALUES ($1, $2, false)',
        [ip, email.toLowerCase()]
      ).catch((e) => console.warn('Failed to record login attempt:', e.message));
      // Audit failed login
      logAuthEvent(req, 'login_failed', { email: email.toLowerCase(), tenantId: user?.tenant_id || null, failureReason: 'INVALID_CREDENTIALS' });
      const remaining = Math.max(0, 4 - attempts);
      return res.status(401).json({
        code: 'INVALID_CREDENTIALS',
        message: 'Invalid email or password',
        attemptsRemaining: remaining,
      });
    }

    // Clear failed attempts on success
    await pool.query(
      'DELETE FROM login_attempts WHERE ip_address = $1 AND email = $2',
      [ip, email.toLowerCase()]
    ).catch((e) => console.warn('Failed to clear login attempts:', e.message));
    const access_token = signToken({ userId: user.id, tenantId: user.tenant_id, role: user.role, email: user.email });
    const refresh_token = await createRefreshToken(user.id, user.tenant_id);
    // Update last_login_at
    pool.query('UPDATE users SET last_login_at = NOW() WHERE id = $1', [user.id]).catch(() => {});
    // Audit successful login
    logAuthEvent(req, 'login_success', { userId: user.id, tenantId: user.tenant_id, email: user.email });
    const isProd = process.env.NODE_ENV === 'production';
    res.cookie('access_token', access_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 15 * 60 * 1000 });
    res.cookie('refresh_token', refresh_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 30 * 24 * 60 * 60 * 1000, path: '/auth/refresh' });
    res.json({ user: { id: user.id, email: user.email, role: user.role, tenant_id: user.tenant_id, first_name: user.first_name, last_name: user.last_name } });
  } catch (err) { res.status(500).json({ code: 'SERVER_ERROR', message: err.message }); }
});

router.post('/refresh', async (req, res) => {
  try {
    const refresh_token = req.cookies?.refresh_token || req.body?.refresh_token;
    if (!refresh_token) return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'refresh_token required' });
    const result = await rotateRefreshToken(refresh_token);
    if (!result) return res.status(401).json({ code: 'INVALID_REFRESH_TOKEN', message: 'Token invalid, expired, or revoked' });
    const isProd = process.env.NODE_ENV === 'production';
    res.cookie('access_token', result.accessToken, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 15 * 60 * 1000 });
    res.cookie('refresh_token', result.refreshToken, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 30 * 24 * 60 * 60 * 1000, path: '/auth/refresh' });
    res.json({ success: true });
  } catch (err) { res.status(500).json({ code: 'SERVER_ERROR', message: err.message }); }
});

router.post('/logout', async (req, res) => {
  try {
    const refresh_token = req.cookies?.refresh_token || req.body?.refresh_token;
    if (refresh_token) await revokeRefreshToken(refresh_token);
    // Audit logout
    if (req.context) logAuthEvent(req, 'logout', { userId: req.context.user_id, tenantId: req.context.tenant_id, email: req.context.email });
    res.clearCookie('access_token');
    res.clearCookie('refresh_token', { path: '/auth/refresh' });
    res.json({ success: true, message: 'Logged out' });
  } catch (err) { res.status(500).json({ code: 'SERVER_ERROR', message: err.message }); }
});

router.get('/me', requireAuth, async (req, res) => {
  try {
    const { rows } = await pool.query(
      'SELECT id, email, role, tenant_id, first_name, last_name, is_active, last_login_at, created_at FROM users WHERE id = $1 AND deleted_at IS NULL',
      [req.context.user_id]
    );
    if (rows.length === 0) return res.status(404).json({ code: 'USER_NOT_FOUND', message: 'User not found' });
    res.json({ user: rows[0] });
  } catch (err) { res.status(500).json({ code: 'SERVER_ERROR', message: err.message }); }
});

router.delete('/me', requireAuth, async (req, res) => {
  try {
    const { user_id, tenant_id, email } = req.context;
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      // Revoke all refresh tokens
      await client.query('UPDATE refresh_tokens SET revoked = true WHERE user_id = $1', [user_id]);
      // Erase PII — overwrite with placeholders, soft-delete
      await client.query(
        `UPDATE users SET
           email        = 'erased-' || id || '@deleted.invalid',
           password_hash = 'ERASED',
           first_name   = NULL,
           last_name    = NULL,
           pin_hash     = NULL,
           pin_enabled  = false,
           pin_device_hash = NULL,
           is_active    = false,
           deleted_at   = NOW(),
           updated_at   = NOW()
         WHERE id = $1 AND tenant_id = $2`,
        [user_id, tenant_id]
      );
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
    // Log erasure AFTER transaction — append-only audit survives erasure
    logAuthEvent(req, 'account_erased', { userId: user_id, tenantId: tenant_id, email });
    res.clearCookie('access_token');
    res.clearCookie('refresh_token', { path: '/auth/refresh' });
    res.json({ success: true, message: 'Your account and personal data have been permanently deleted.' });
  } catch (err) { res.status(500).json({ code: 'SERVER_ERROR', message: err.message }); }
});

// ─── PIN Login ────────────────────────────────────────────────────────────

router.post('/pin/setup', requireAuth, async (req, res) => {
  try {
    const { pin } = req.body;
    if (!pin) return res.status(400).json({ code: 'MISSING_PIN', message: 'PIN is required' });
    const pinStr = String(pin);
    if (!/^\d{4,6}$/.test(pinStr)) {
      return res.status(400).json({ code: 'INVALID_PIN_FORMAT', message: 'PIN must be 4-6 digits only' });
    }
    // Hash PIN with PBKDF2 (same as password — timing-safe)
    const pin_hash = await hashPassword(pinStr);
    // Device fingerprint — PIN only works from device it was set on
    const ip       = (req.ip || '').replace('::ffff:', '');
    const ua       = (req.headers['user-agent'] || '').slice(0, 500);
    const lang     = (req.headers['accept-language'] || '').slice(0, 50);
    const deviceFp = crypto.createHash('sha256')
      .update(ua + '|' + ip.split('.').slice(0,3).join('.') + '|' + lang)
      .digest('hex').slice(0, 64);
    await pool.query(
      `UPDATE users SET pin_hash=$1, pin_enabled=true, pin_set_at=NOW(), pin_device_hash=$2, updated_at=NOW()
       WHERE id=$3 AND tenant_id=$4 AND deleted_at IS NULL`,
      [pin_hash, deviceFp, req.context.user_id, req.context.tenant_id]
    );
    logAuthEvent(req, 'pin_setup', { userId: req.context.user_id, tenantId: req.context.tenant_id, email: req.context.email });
    res.json({ success: true, message: 'PIN set successfully. PIN login enabled for this device.' });
  } catch (err) {
    res.status(500).json({ code: 'SERVER_ERROR', message: process.env.NODE_ENV === 'production' ? 'Internal error' : err.message });
  }
});

router.post('/pin/login', async (req, res) => {
  try {
    // Public route (no requireAuth) — a request with no/other Content-Type leaves
    // req.body undefined; guard it so an empty call 400s at the check below, not
    // a 500 from destructuring undefined (RC4).
    const { user_id, tenant_id, pin } = req.body || {};
    if (!user_id || !tenant_id || !pin) {
      return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'user_id, tenant_id, and pin are required' });
    }
    const pinStr = String(pin);
    if (!/^\d{4,6}$/.test(pinStr)) {
      return res.status(400).json({ code: 'INVALID_PIN_FORMAT', message: 'PIN must be 4-6 digits' });
    }

    const ip = (req.ip || '').replace('::ffff:', '');
    const ua = (req.headers['user-agent'] || '').slice(0, 500);

    // ── PIN rate limiting (3 attempts, 5 min lockout) ────────────────
    const { rows: pinAttempts } = await pool.query(
      `SELECT COUNT(*) AS attempts FROM auth_audit_log
       WHERE user_id = $1 AND event_type = 'pin_login_failed'
         AND created_at > NOW() - ($2 || ' minutes')::INTERVAL`,
      [user_id, PIN_LOCKOUT_MINS]
    ).catch(() => ({ rows: [{ attempts: 0 }] }));
    if (parseInt(pinAttempts[0]?.attempts || 0) >= PIN_MAX_ATTEMPTS) {
      logAuthEvent(req, 'account_locked', { userId: user_id, tenantId: tenant_id, failureReason: 'PIN_MAX_ATTEMPTS_EXCEEDED' });
      return res.status(429).json({
        code: 'PIN_LOCKED',
        message: `Too many PIN attempts. Try again in ${PIN_LOCKOUT_MINS} minutes.`,
        retryAfter: PIN_LOCKOUT_MINS * 60,
      });
    }

    // ── Load user + verify PIN enabled ───────────────────────────────
    const { rows } = await pool.query(
      `SELECT id, email, role, tenant_id, pin_hash, pin_enabled, pin_device_hash, is_active
       FROM users WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
      [user_id, tenant_id]
    );
    const user = rows[0];
    if (!user || !user.is_active) {
      logAuthEvent(req, 'pin_login_failed', { userId: user_id, tenantId: tenant_id, failureReason: 'USER_NOT_FOUND' });
      return res.status(401).json({ code: 'INVALID_CREDENTIALS', message: 'User not found or inactive' });
    }
    if (!user.pin_enabled || !user.pin_hash) {
      return res.status(403).json({ code: 'PIN_NOT_SET', message: 'PIN login not enabled for this user. Set a PIN first.' });
    }

    // ── Device fingerprint check ──────────────────────────────────────
    // PIN only works from the device it was set on — prevents PIN theft
    const lang     = (req.headers['accept-language'] || '').slice(0, 50);
    const ipSubnet = ip.split('.').slice(0,3).join('.');
    const deviceFp = crypto.createHash('sha256')
      .update(ua + '|' + ipSubnet + '|' + lang).digest('hex').slice(0, 64);
    if (user.pin_device_hash && user.pin_device_hash !== deviceFp) {
      logAuthEvent(req, 'pin_login_failed', { userId: user.id, tenantId: tenant_id, email: user.email, failureReason: 'WRONG_DEVICE' });
      return res.status(401).json({ code: 'WRONG_DEVICE', message: 'PIN was set on a different device. Use password to log in.' });
    }

    // ── Verify PIN — always run hash even if wrong (timing-safe) ─────
    const pinOk = await verifyPassword(pinStr, user.pin_hash).catch(() => false);
    if (!pinOk) {
      logAuthEvent(req, 'pin_login_failed', { userId: user.id, tenantId: tenant_id, email: user.email, failureReason: 'WRONG_PIN' });
      const remaining = Math.max(0, PIN_MAX_ATTEMPTS - parseInt(pinAttempts[0]?.attempts || 0) - 1);
      return res.status(401).json({ code: 'WRONG_PIN', message: 'Incorrect PIN', attemptsRemaining: remaining });
    }

    // ── PIN verified — issue short-lived access token ─────────────────
    const access_token = signToken({
      userId: user.id, tenantId: user.tenant_id,
      role: user.role, email: user.email,
      loginMethod: 'pin',
    });
    pool.query('UPDATE users SET last_login_at = NOW() WHERE id = $1', [user.id]).catch(() => {});
    logAuthEvent(req, 'pin_login_success', { userId: user.id, tenantId: tenant_id, email: user.email });
    const isProd = process.env.NODE_ENV === 'production';
    res.cookie('access_token', access_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: parseInt(process.env.PIN_EXPIRES_MINUTES || '30') * 60 * 1000 });
    res.json({ user: { id: user.id, email: user.email, role: user.role, tenant_id: user.tenant_id, login_method: 'pin' } });
  } catch (err) {
    res.status(500).json({ code: 'SERVER_ERROR', message: process.env.NODE_ENV === 'production' ? 'Internal error' : err.message });
  }
});

router.post('/pin/disable', requireAuth, async (req, res) => {
  try {
    await pool.query(
      `UPDATE users SET pin_hash=NULL, pin_enabled=false, pin_device_hash=NULL, updated_at=NOW()
       WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL`,
      [req.context.user_id, req.context.tenant_id]
    );
    logAuthEvent(req, 'pin_setup', { userId: req.context.user_id, tenantId: req.context.tenant_id, metadata: { action: 'disabled' } });
    res.json({ success: true, message: 'PIN login disabled' });
  } catch (err) {
    res.status(500).json({ code: 'SERVER_ERROR', message: process.env.NODE_ENV === 'production' ? 'Internal error' : err.message });
  }
});

// ─── Auth audit log (self) ────────────────────────────────────────────────
router.get('/audit', requireAuth, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT id, event_type, ip_address, device_fingerprint, failure_reason, created_at
       FROM auth_audit_log
       WHERE user_id = $1 AND tenant_id = $2
       ORDER BY created_at DESC LIMIT 100`,
      [req.context.user_id, req.context.tenant_id]
    );
    res.json({ events: rows });
  } catch (err) {
    res.status(500).json({ code: 'SERVER_ERROR', message: err.message });
  }
});

router.get('/audit/all', requireAuth, requireRole('admin', 'super_admin', 'pharmacy_owner', 'auditor'), async (req, res) => {
  try {
    const { user_id, event_type, from_date, to_date, limit = 200 } = req.query;
    const params = [req.context.tenant_id];
    // Columns qualified with aal.* — auth_audit_log JOINs users, which also has
    // tenant_id/user_id/created_at, so unqualified refs are 'column ambiguous' (RC3).
    let where = 'WHERE aal.tenant_id = $1';
    if (user_id)    { params.push(user_id);    where += ` AND aal.user_id = $${params.length}`; }
    if (event_type) { params.push(event_type); where += ` AND aal.event_type = $${params.length}`; }
    if (from_date)  { params.push(from_date);  where += ` AND DATE(aal.created_at) >= $${params.length}`; }
    if (to_date)    { params.push(to_date);    where += ` AND DATE(aal.created_at) <= $${params.length}`; }
    const safeLimit = Math.min(parseInt(limit) || 200, 1000);
    const { rows } = await pool.query(
      `SELECT aal.*, u.email AS user_email, u.role AS user_role
       FROM auth_audit_log aal
       LEFT JOIN users u ON u.id = aal.user_id
       ${where}
       ORDER BY aal.created_at DESC LIMIT $${params.length + 1}`,
      [...params, safeLimit]
    );
    res.json({ events: rows, count: rows.length });
  } catch (err) {
    res.status(500).json({ code: 'SERVER_ERROR', message: err.message });
  }
});

// ─── Accept an invite: the ONLY token-gated way into an EXISTING tenant ─────
// The tenant and email come from the INVITE ROW — never the client. Signup is
// untouched (still mints a fresh tenant); the token proves the invitation.
router.post('/accept-invite', async (req, res) => {
  try {
    const { token, password, first_name, last_name } = req.body || {};
    if (!token || !password) return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'token and password are required' });
    if (String(password).length < 8) return res.status(400).json({ code: 'VALIDATION_ERROR', message: 'password min 8 chars' });
    const { rows: _inv } = await pool.query('SELECT * FROM invites WHERE token = $1 AND deleted_at IS NULL LIMIT 1', [token]);
    if (_inv.length === 0) return res.status(404).json({ code: 'INVITE_NOT_FOUND', message: 'Invite not found' });
    const invite = _inv[0];
    // Spec rule: only the invited email may accept. The account is created WITH
    // the invite's email (enforced by construction); a mismatch is refused loudly.
    const email = String(invite.email || '').toLowerCase();
    if (req.body.email && String(req.body.email).toLowerCase() !== email) {
      return res.status(403).json({ code: 'EMAIL_MISMATCH', message: 'Invite may only be accepted by the invited email' });
    }
    if (invite.status !== 'pending') return res.status(409).json({ code: 'INVITE_NOT_PENDING', message: 'Invite is ' + invite.status });
    if (invite.expires_at && new Date(invite.expires_at) < new Date()) return res.status(410).json({ code: 'INVITE_EXPIRED', message: 'Invite has expired' });
    // Tenant comes from the invite row — the locked identity model holds.
    const tenant_id = invite.tenant_id;
    // Role comes from the admin-authored invite, capped to declared roles.
    const role = (invite.role && VALID_ROLES.includes(invite.role)) ? invite.role : 'member';
    const { rows: existing } = await pool.query('SELECT id FROM users WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL', [email]);
    if (existing.length > 0) return res.status(409).json({ code: 'EMAIL_TAKEN', message: 'Email already registered' });
    // Seat cap (#6): accepting an invite may not exceed the subscription's seats.
    const { rows: _cap } = await pool.query('SELECT seats AS seats FROM subscriptions WHERE tenant_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1', [tenant_id]);
    if (_cap.length > 0 && Number.isInteger(_cap[0].seats)) {
      const { rows: _seatCnt } = await pool.query('SELECT COUNT(*)::int AS n FROM users WHERE tenant_id = $1 AND deleted_at IS NULL AND is_active = true', [tenant_id]);
      if (_seatCnt[0].n >= _cap[0].seats) return res.status(409).json({ code: 'SEAT_LIMIT', message: 'Subscription seat limit reached' });
    }
    // Atomically CLAIM the invite first — a concurrent double-accept loses this
    // UPDATE race deterministically (DB-level guard, no SELECT-then-act window).
    const { rows: _claim } = await pool.query("UPDATE invites SET status = 'accepted', updated_at = NOW() WHERE id = $1 AND status = 'pending' RETURNING id", [invite.id]);
    if (_claim.length === 0) return res.status(409).json({ code: 'INVITE_NOT_PENDING', message: 'Invite already used' });
    let user;
    try {
      const password_hash = await hashPassword(password);
      const { rows } = await pool.query(
        `INSERT INTO users (email, password_hash, tenant_id, role, first_name, last_name)
         VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, email, tenant_id, role, first_name, last_name`,
        [email, password_hash, tenant_id, role, first_name || null, last_name || null]
      );
      user = rows[0];
    } catch (err) {
      // Release the claim — a failed create must not burn the invite.
      await pool.query("UPDATE invites SET status = 'pending', updated_at = NOW() WHERE id = $1", [invite.id]);
      throw err;
    }
    logAuthEvent(req, 'invite_accepted', { userId: user.id, tenantId: tenant_id, email, metadata: { invite_id: invite.id, role: user.role } });
    const access_token = signToken({ userId: user.id, tenantId: user.tenant_id, role: user.role, email: user.email });
    const refresh_token = await createRefreshToken(user.id, user.tenant_id);
    const isProd = process.env.NODE_ENV === 'production';
    res.cookie('access_token', access_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 15 * 60 * 1000 });
    res.cookie('refresh_token', refresh_token, { httpOnly: true, secure: isProd, sameSite: 'strict', maxAge: 30 * 24 * 60 * 60 * 1000, path: '/auth/refresh' });
    res.status(201).json({ user });
  } catch (err) {
    if (err && err.code === '23505') return res.status(409).json({ code: 'EMAIL_TAKEN', message: 'Email already registered' });
    res.status(500).json({ code: 'SERVER_ERROR', message: err.message });
  }
});

export { router as authRoutes };
