/**
 * 🛣️ CRUD Routes for comment
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { mapPgError } from '../db/pgErrors.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
// Socket + push events (no-op if features not generated)
let emitSocketEvent = () => {};
let emitPushEvent   = () => {};
// Domain events (no-op if no feature/notification subscribes)
let publishDomainEvent = () => {};
try {
  const { publishDomainEvent: _pd } = await import('../events/dispatcher.js');
  publishDomainEvent = _pd;
} catch (_) {}
// Lifecycle hooks (no-op if hooks not generated)
let runHook = async () => {};
try {
  const { runHook: _rh } = await import('../hooks/_runtime.js');
  runHook = _rh;
} catch (_) {}

import { validateCreateComment, validateUpdateComment } from '../validation/commentValidation.js';

export function registerCommentRoutes(app) {

  // List comments
  app.get('/api/comments', requireAuth, requireRole('owner', 'admin', 'member', 'guest'), async (req, res) => {
    try {
      const { limit = 20, offset = 0 } = req.query;
      const tenant_id = req.context.tenant_id;
      const params = [tenant_id];
      const conditions = ['tenant_id = $1', 'deleted_at IS NULL'];
      let idx = 2;


      const where = 'WHERE ' + conditions.join(' AND ');
      // Pagination guards (#29): a non-numeric ?limit/?offset must not bind NaN
      // (Math.min(NaN,100) is NaN → Postgres error). Coerce with a safe default.
      const _limit  = Math.min(Math.max(parseInt(limit)  || 20, 1), 100);
      const _offset = Math.max(parseInt(offset) || 0, 0);
      params.push(_limit, _offset);

      const countResult = await pool.query('SELECT COUNT(*) as total FROM comments ' + where, params.slice(0, -2));
      const { rows } = await pool.query(
        'SELECT * FROM comments ' + where + ' ORDER BY created_at DESC LIMIT $' + idx++ + ' OFFSET $' + idx++,
        params
      );

      res.json({ data: rows, total: parseInt(countResult.rows[0].total), limit: _limit, offset: _offset });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Get comment by ID
  app.get('/api/comments/:id', requireAuth, requireRole('owner', 'admin', 'member', 'guest'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { rows } = await pool.query(
        'SELECT * FROM comments WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'comment not found' });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Create comment
  app.post('/api/comments', requireAuth, requireRole('member', 'guest', 'admin', 'owner'), async (req, res) => {
    try {
      const tenant_id = req.context.tenant_id;
      if ((await runHook('comment', 'beforeCreate', { req, res, tenantId: tenant_id, entity: 'comment', action: 'create', input: req.body })) === false) return;
      const { task_id, body, parent_id, is_internal, edited_at } = req.body;

      validateCreateComment(req.body);

      if (!task_id) return res.status(400).json({ error: 'task_id is required' });
      if (!body) return res.status(400).json({ error: 'body is required' });

      if (task_id !== undefined && task_id !== null) {
        const { rows: _fk_task_id } = await pool.query('SELECT 1 FROM tasks WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL', [task_id, tenant_id]);
        if (_fk_task_id.length === 0) return res.status(400).json({ error: 'task not found in this tenant' });
      }

      // owner_id comes from the JWT, never the request body
      const _cols = ['tenant_id', 'owner_id'];
      const _vals = [tenant_id, req.context.user_id];
      const _add = (c, v) => { if (v !== undefined) { _cols.push(c); _vals.push(v); } };
      _add('author_id', req.context.user_id);
      _add('task_id', task_id);
      _add('body', body);
      _add('parent_id', parent_id);
      _add('is_internal', is_internal);
      _add('edited_at', edited_at);
      const _ph = _vals.map((_, i) => '$' + (i + 1));
      const { rows } = await pool.query(
        `INSERT INTO comments (${_cols.join(', ')}) VALUES (${_ph.join(', ')}) RETURNING *`,
        _vals
      );
      await runHook('comment', 'afterCreate', { req, res, tenantId: tenant_id, entity: 'comment', action: 'create', input: req.body, record: rows[0] });
      emitSocketEvent('comment', 'created', tenant_id, { comment: rows[0] });
      emitPushEvent('comment', 'created', tenant_id, { record: rows[0], userId: rows[0].owner_id || req.context.user_id });
      publishDomainEvent('comment', 'created', tenant_id, { comment: rows[0] });
      res.status(201).json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Update comment
  app.put('/api/comments/:id', requireAuth, requireRole('member', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const user_id   = req.context.user_id;
      if ((await runHook('comment', 'beforeUpdate', { req, res, tenantId: tenant_id, entity: 'comment', action: 'update', id: req.params.id, input: req.body })) === false) return;
      const fields = req.body;
      validateUpdateComment(fields);
      if (!fields || Object.keys(fields).length === 0) {
        return res.status(400).json({ error: 'No fields to update' });
      }

      const allowed = ['task_id', 'body', 'parent_id', 'is_internal', 'edited_at'];
      const setClauses = [];
      const params = [];
      let idx = 1;

      for (const [key, val] of Object.entries(fields)) {
        if (allowed.includes(key)) {
          setClauses.push(key + ' = $' + idx++);
          params.push(val);
        }
      }

      if (setClauses.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
      }

      setClauses.push('updated_at = NOW()');
      // Only the owner or an admin-tier caller may update — tenant isolation +
      // ownership enforced in SQL. Admin authority comes from the JWT-verified
      // req.context.role (no redundant users lookup — #33).
      const _priv = ["admin","owner"].includes(req.context.role);
      params.push(req.params.id, tenant_id, user_id, _priv);
      const _idPh = '$' + idx++, _tenantPh = '$' + idx++, _ownerPh = '$' + idx++, _privPh = '$' + idx++;

      const { rows } = await pool.query(
        'UPDATE comments SET ' + setClauses.join(', ') + ' WHERE id = ' + _idPh + ' AND tenant_id = ' + _tenantPh + ' AND (owner_id = ' + _ownerPh + ' OR ' + _privPh + ') AND deleted_at IS NULL RETURNING *',
        params
      );
      if (rows.length === 0) return res.status(404).json({ error: 'comment not found' });
      await runHook('comment', 'afterUpdate', { req, res, tenantId: tenant_id, entity: 'comment', action: 'update', id: req.params.id, record: rows[0] });
      emitSocketEvent('comment', 'updated', tenant_id, { comment: rows[0] });
      publishDomainEvent('comment', 'updated', tenant_id, { comment: rows[0] });
      emitPushEvent('comment', 'updated', tenant_id, { record: rows[0] });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Soft-delete comment
  app.delete('/api/comments/:id', requireAuth, requireRole('member', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const user_id   = req.context.user_id;
      if ((await runHook('comment', 'beforeDelete', { req, res, tenantId: tenant_id, entity: 'comment', action: 'delete', id: req.params.id })) === false) return;
      // Only the owner or an admin-tier caller may delete — admin authority from
      // the JWT-verified req.context.role, no redundant users lookup (#33).
      const _priv = ["admin","owner"].includes(req.context.role);
      const { rows } = await pool.query(
        'UPDATE comments SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND tenant_id = $2 AND (owner_id = $3 OR $4) AND deleted_at IS NULL RETURNING id',
        [req.params.id, tenant_id, user_id, _priv]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'comment not found' });
      await runHook('comment', 'afterDelete', { req, res, tenantId: tenant_id, entity: 'comment', action: 'delete', id: rows[0].id });
      emitSocketEvent('comment', 'deleted', tenant_id, { id: rows[0].id });
      publishDomainEvent('comment', 'deleted', tenant_id, { id: rows[0].id });
      emitPushEvent('comment', 'deleted', tenant_id, { record: { id: rows[0].id } });
      res.json({ deleted: true, id: rows[0].id });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // State transitions for comment
  app.patch('/api/comments/:id/transition', requireAuth, requireRole('member', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { action } = req.body;
      const transitions = {
        'flagged': { from: ["active"], to: 'flagged' },
        'removed': { from: ["flagged"], to: 'removed' },
      };

      const transition = transitions[action];
      if (!transition) {
        return res.status(400).json({ error: 'Invalid action. Use: ' + Object.keys(transitions).join(', ') });
      }

      const { rows: current } = await pool.query(
        'SELECT status FROM comments WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (current.length === 0) return res.status(404).json({ error: 'comment not found' });

      if (!transition.from.includes(current[0].status)) {
        return res.status(400).json({
          error: 'Cannot ' + action + ' from ' + current[0].status + '. Must be one of: ' + transition.from.join(', '),
        });
      }

      const { rows } = await pool.query(
        'UPDATE comments SET status = $1, updated_at = NOW() WHERE id = $2 AND tenant_id = $3 AND deleted_at IS NULL RETURNING *',
        [transition.to, req.params.id, tenant_id]
      );
      emitSocketEvent('comment', 'transition', tenant_id, { comment: rows[0], from: transition.from, to: transition.to });
      publishDomainEvent('comment', 'transition', tenant_id, { comment: rows[0], from: transition.from, to: transition.to });
      res.json({ action, from: transition.from, to: transition.to, comment: rows[0] });
      emitPushEvent('comment', 'transition', tenant_id, { record: rows[0], from: transition.from, to: transition.to });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

}
