/**
 * ⚡ Health Check Routes
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';

const startedAt = Date.now();

export function registerHealthRoutes(app) {

  // Quick health check (for load balancers)
  app.get('/health', (req, res) => {
    res.json({ status: 'ok', uptime: Math.floor((Date.now() - startedAt) / 1000) });
  });

  // Detailed health (for monitoring)
  app.get('/health/detailed', requireAuth, requireRole('admin'), async (req, res) => {
    const checks = {};
    let healthy = true;

    // Database
    try {
      const dbStart = Date.now();
      await pool.query('SELECT 1');
      checks.database = { status: 'ok', latency: Date.now() - dbStart + 'ms' };
    } catch (err) {
      checks.database = { status: 'error', message: err.message };
      healthy = false;
    }

    // Connection pool
    checks.pool = {
      total: pool.totalCount,
      idle: pool.idleCount,
      waiting: pool.waitingCount,
    };

    // Memory
    const mem = process.memoryUsage();
    checks.memory = {
      heapUsed: Math.round(mem.heapUsed / 1024 / 1024) + 'MB',
      heapTotal: Math.round(mem.heapTotal / 1024 / 1024) + 'MB',
      rss: Math.round(mem.rss / 1024 / 1024) + 'MB',
    };

    // Entity counts
    try {
      const counts = {};
      const attachmentCount = await pool.query('SELECT COUNT(*) as c FROM attachments');
      counts.attachments = parseInt(attachmentCount.rows[0].c);
      const commentCount = await pool.query('SELECT COUNT(*) as c FROM comments');
      counts.comments = parseInt(commentCount.rows[0].c);
      const inviteCount = await pool.query('SELECT COUNT(*) as c FROM invites');
      counts.invites = parseInt(inviteCount.rows[0].c);
      const projectCount = await pool.query('SELECT COUNT(*) as c FROM projects');
      counts.projects = parseInt(projectCount.rows[0].c);
      const subscriptionCount = await pool.query('SELECT COUNT(*) as c FROM subscriptions');
      counts.subscriptions = parseInt(subscriptionCount.rows[0].c);
      const taskCount = await pool.query('SELECT COUNT(*) as c FROM tasks');
      counts.tasks = parseInt(taskCount.rows[0].c);
      checks.entities = counts;
    } catch (err) {
      checks.entities = { error: err.message };
    }

    res.status(healthy ? 200 : 503).json({
      status: healthy ? 'healthy' : 'degraded',
      uptime: Math.floor((Date.now() - startedAt) / 1000) + 's',
      version: process.env.npm_package_version || '1.0.0',
      checks,
    });
  });

  // Readiness probe (for Kubernetes)
  app.get('/ready', async (req, res) => {
    try {
      await pool.query('SELECT 1');
      res.json({ ready: true });
    } catch (err) {
      res.status(503).json({ ready: false, error: err.message });
    }
  });
}
