/**
 * 🛣️ Route Index — Auto-registers all entity routes
 * Auto-generated by Forgx
 */

import { registerAttachmentRoutes } from './attachmentRoutes.js';
import { registerCommentRoutes } from './commentRoutes.js';
import { registerInviteRoutes } from './inviteRoutes.js';
import { registerProjectRoutes } from './projectRoutes.js';
import { registerSubscriptionRoutes } from './subscriptionRoutes.js';
import { registerTaskRoutes } from './taskRoutes.js';

/**
 * Register all entity routes
 */
export function registerRoutes(app) {
  registerAttachmentRoutes(app);
  registerCommentRoutes(app);
  registerInviteRoutes(app);
  registerProjectRoutes(app);
  registerSubscriptionRoutes(app);
  registerTaskRoutes(app);
}
