/**
 * 🛣️ CRUD Routes for invite
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { mapPgError } from '../db/pgErrors.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import crypto from 'crypto';
// Socket + push events (no-op if features not generated)
let emitSocketEvent = () => {};
let emitPushEvent   = () => {};
// Domain events (no-op if no feature/notification subscribes)
let publishDomainEvent = () => {};
try {
  const { publishDomainEvent: _pd } = await import('../events/dispatcher.js');
  publishDomainEvent = _pd;
} catch (_) {}
// Lifecycle hooks (no-op if hooks not generated)
let runHook = async () => {};
try {
  const { runHook: _rh } = await import('../hooks/_runtime.js');
  runHook = _rh;
} catch (_) {}

import { validateCreateInvite, validateUpdateInvite } from '../validation/inviteValidation.js';

export function registerInviteRoutes(app) {

  // List invites
  app.get('/api/invites', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      const { limit = 20, offset = 0 } = req.query;
      const tenant_id = req.context.tenant_id;
      const params = [tenant_id];
      const conditions = ['tenant_id = $1', 'deleted_at IS NULL'];
      let idx = 2;


      const where = 'WHERE ' + conditions.join(' AND ');
      // Pagination guards (#29): a non-numeric ?limit/?offset must not bind NaN
      // (Math.min(NaN,100) is NaN → Postgres error). Coerce with a safe default.
      const _limit  = Math.min(Math.max(parseInt(limit)  || 20, 1), 100);
      const _offset = Math.max(parseInt(offset) || 0, 0);
      params.push(_limit, _offset);

      const countResult = await pool.query('SELECT COUNT(*) as total FROM invites ' + where, params.slice(0, -2));
      const { rows } = await pool.query(
        'SELECT * FROM invites ' + where + ' ORDER BY created_at DESC LIMIT $' + idx++ + ' OFFSET $' + idx++,
        params
      );

      res.json({ data: rows, total: parseInt(countResult.rows[0].total), limit: _limit, offset: _offset });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Get invite by ID
  app.get('/api/invites/:id', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { rows } = await pool.query(
        'SELECT * FROM invites WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'invite not found' });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Create invite
  app.post('/api/invites', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      const tenant_id = req.context.tenant_id;
      if ((await runHook('invite', 'beforeCreate', { req, res, tenantId: tenant_id, entity: 'invite', action: 'create', input: req.body })) === false) return;
      const { email, role, project_id, expires_at, invited_by, title, description, metadata } = req.body;

      validateCreateInvite(req.body);

      if (!email) return res.status(400).json({ error: 'email is required' });
      if (!project_id) return res.status(400).json({ error: 'project_id is required' });
      if (!title) return res.status(400).json({ error: 'title is required' });

      if (project_id !== undefined && project_id !== null) {
        const { rows: _fk_project_id } = await pool.query('SELECT status FROM projects WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL', [project_id, tenant_id]);
        if (_fk_project_id.length === 0) return res.status(400).json({ error: 'project not found in this tenant' });
        if (_fk_project_id[0].status === 'archived') return res.status(409).json({ error: 'project is archived and cannot accept new invites' });
      }
      const { rows: _cap } = await pool.query('SELECT seats AS seats FROM subscriptions WHERE tenant_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1', [tenant_id]);
      if (_cap.length > 0 && Number.isInteger(_cap[0].seats)) {
        const { rows: _seatCnt } = await pool.query('SELECT COUNT(*)::int AS n FROM users WHERE tenant_id = $1 AND deleted_at IS NULL AND is_active = true', [tenant_id]);
        if (_seatCnt[0].n >= _cap[0].seats) return res.status(409).json({ error: 'Subscription seat limit reached' });
      }

      const _cols = ['tenant_id'];
      const _vals = [tenant_id];
      const _add = (c, v) => { if (v !== undefined) { _cols.push(c); _vals.push(v); } };
      _add('token', crypto.randomBytes(32).toString('hex'));
      _add('email', email);
      _add('role', role);
      _add('project_id', project_id);
      _add('expires_at', new Date(Date.now() + 604800000).toISOString());
      _add('invited_by', invited_by);
      _add('title', title);
      _add('description', description);
      _add('metadata', metadata);
      const _ph = _vals.map((_, i) => '$' + (i + 1));
      const { rows } = await pool.query(
        `INSERT INTO invites (${_cols.join(', ')}) VALUES (${_ph.join(', ')}) RETURNING *`,
        _vals
      );
      await runHook('invite', 'afterCreate', { req, res, tenantId: tenant_id, entity: 'invite', action: 'create', input: req.body, record: rows[0] });
      emitSocketEvent('invite', 'created', tenant_id, { invite: rows[0] });
      emitPushEvent('invite', 'created', tenant_id, { record: rows[0], userId: rows[0].owner_id || req.context.user_id });
      publishDomainEvent('invite', 'created', tenant_id, { invite: rows[0] });
      res.status(201).json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Update invite
  app.put('/api/invites/:id', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      if ((await runHook('invite', 'beforeUpdate', { req, res, tenantId: tenant_id, entity: 'invite', action: 'update', id: req.params.id, input: req.body })) === false) return;
      const fields = req.body;
      validateUpdateInvite(fields);
      if (!fields || Object.keys(fields).length === 0) {
        return res.status(400).json({ error: 'No fields to update' });
      }

      const allowed = ['email', 'role', 'project_id', 'expires_at', 'invited_by', 'title', 'description', 'metadata'];
      const setClauses = [];
      const params = [];
      let idx = 1;

      for (const [key, val] of Object.entries(fields)) {
        if (allowed.includes(key)) {
          setClauses.push(key + ' = $' + idx++);
          params.push(val);
        }
      }

      if (setClauses.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
      }

      setClauses.push('updated_at = NOW()');
      params.push(req.params.id, tenant_id);

      const { rows } = await pool.query(
        'UPDATE invites SET ' + setClauses.join(', ') + ' WHERE id = $' + idx++ + ' AND tenant_id = $' + idx++ + ' AND deleted_at IS NULL RETURNING *',
        params
      );
      if (rows.length === 0) return res.status(404).json({ error: 'invite not found' });
      await runHook('invite', 'afterUpdate', { req, res, tenantId: tenant_id, entity: 'invite', action: 'update', id: req.params.id, record: rows[0] });
      emitSocketEvent('invite', 'updated', tenant_id, { invite: rows[0] });
      publishDomainEvent('invite', 'updated', tenant_id, { invite: rows[0] });
      emitPushEvent('invite', 'updated', tenant_id, { record: rows[0] });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Soft-delete invite
  app.delete('/api/invites/:id', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      if ((await runHook('invite', 'beforeDelete', { req, res, tenantId: tenant_id, entity: 'invite', action: 'delete', id: req.params.id })) === false) return;
      // Tenant isolation enforced — role access enforced by permission middleware
      const { rows } = await pool.query(
        'UPDATE invites SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL RETURNING id',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'invite not found' });
      await runHook('invite', 'afterDelete', { req, res, tenantId: tenant_id, entity: 'invite', action: 'delete', id: rows[0].id });
      emitSocketEvent('invite', 'deleted', tenant_id, { id: rows[0].id });
      publishDomainEvent('invite', 'deleted', tenant_id, { id: rows[0].id });
      emitPushEvent('invite', 'deleted', tenant_id, { record: { id: rows[0].id } });
      res.json({ deleted: true, id: rows[0].id });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // State transitions for invite
  app.patch('/api/invites/:id/transition', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { action } = req.body;
      const transitions = {
        'accepted': { from: ["pending"], to: 'accepted' },
        'expire': { from: ["pending"], to: 'expired' },
      };

      const transition = transitions[action];
      if (!transition) {
        return res.status(400).json({ error: 'Invalid action. Use: ' + Object.keys(transitions).join(', ') });
      }

      const { rows: current } = await pool.query(
        'SELECT status FROM invites WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (current.length === 0) return res.status(404).json({ error: 'invite not found' });

      if (!transition.from.includes(current[0].status)) {
        return res.status(400).json({
          error: 'Cannot ' + action + ' from ' + current[0].status + '. Must be one of: ' + transition.from.join(', '),
        });
      }

      const { rows } = await pool.query(
        'UPDATE invites SET status = $1, updated_at = NOW() WHERE id = $2 AND tenant_id = $3 AND deleted_at IS NULL RETURNING *',
        [transition.to, req.params.id, tenant_id]
      );
      emitSocketEvent('invite', 'transition', tenant_id, { invite: rows[0], from: transition.from, to: transition.to });
      publishDomainEvent('invite', 'transition', tenant_id, { invite: rows[0], from: transition.from, to: transition.to });
      res.json({ action, from: transition.from, to: transition.to, invite: rows[0] });
      emitPushEvent('invite', 'transition', tenant_id, { record: rows[0], from: transition.from, to: transition.to });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

}
