/**
 * 🛣️ CRUD Routes for project
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { mapPgError } from '../db/pgErrors.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
// Socket + push events (no-op if features not generated)
let emitSocketEvent = () => {};
let emitPushEvent   = () => {};
// Domain events (no-op if no feature/notification subscribes)
let publishDomainEvent = () => {};
try {
  const { publishDomainEvent: _pd } = await import('../events/dispatcher.js');
  publishDomainEvent = _pd;
} catch (_) {}
// Lifecycle hooks (no-op if hooks not generated)
let runHook = async () => {};
try {
  const { runHook: _rh } = await import('../hooks/_runtime.js');
  runHook = _rh;
} catch (_) {}

import { validateCreateProject, validateUpdateProject } from '../validation/projectValidation.js';

export function registerProjectRoutes(app) {

  // List projects
  app.get('/api/projects', requireAuth, requireRole('owner', 'admin', 'member', 'guest'), async (req, res) => {
    try {
      const { limit = 20, offset = 0 } = req.query;
      const tenant_id = req.context.tenant_id;
      const params = [tenant_id];
      const conditions = ['tenant_id = $1', 'deleted_at IS NULL'];
      let idx = 2;


      const where = 'WHERE ' + conditions.join(' AND ');
      // Pagination guards (#29): a non-numeric ?limit/?offset must not bind NaN
      // (Math.min(NaN,100) is NaN → Postgres error). Coerce with a safe default.
      const _limit  = Math.min(Math.max(parseInt(limit)  || 20, 1), 100);
      const _offset = Math.max(parseInt(offset) || 0, 0);
      params.push(_limit, _offset);

      const countResult = await pool.query('SELECT COUNT(*) as total FROM projects ' + where, params.slice(0, -2));
      const { rows } = await pool.query(
        'SELECT * FROM projects ' + where + ' ORDER BY created_at DESC LIMIT $' + idx++ + ' OFFSET $' + idx++,
        params
      );

      res.json({ data: rows, total: parseInt(countResult.rows[0].total), limit: _limit, offset: _offset });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Get project by ID
  app.get('/api/projects/:id', requireAuth, requireRole('owner', 'admin', 'member', 'guest'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { rows } = await pool.query(
        'SELECT * FROM projects WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'project not found' });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Create project
  app.post('/api/projects', requireAuth, requireRole('member', 'admin', 'owner'), async (req, res) => {
    try {
      const tenant_id = req.context.tenant_id;
      if ((await runHook('project', 'beforeCreate', { req, res, tenantId: tenant_id, entity: 'project', action: 'create', input: req.body })) === false) return;
      const { name, description, deadline, color, start_date, end_date, budget, progress, is_archived, metadata } = req.body;

      validateCreateProject(req.body);

      if (!name) return res.status(400).json({ error: 'name is required' });

      const _cols = ['tenant_id'];
      const _vals = [tenant_id];
      const _add = (c, v) => { if (v !== undefined) { _cols.push(c); _vals.push(v); } };
      _add('name', name);
      _add('description', description);
      _add('deadline', deadline);
      _add('color', color);
      _add('start_date', start_date);
      _add('end_date', end_date);
      _add('budget', budget);
      _add('progress', progress);
      _add('is_archived', is_archived);
      _add('metadata', metadata);
      const _ph = _vals.map((_, i) => '$' + (i + 1));
      const { rows } = await pool.query(
        `INSERT INTO projects (${_cols.join(', ')}) VALUES (${_ph.join(', ')}) RETURNING *`,
        _vals
      );
      await runHook('project', 'afterCreate', { req, res, tenantId: tenant_id, entity: 'project', action: 'create', input: req.body, record: rows[0] });
      emitSocketEvent('project', 'created', tenant_id, { project: rows[0] });
      emitPushEvent('project', 'created', tenant_id, { record: rows[0], userId: rows[0].owner_id || req.context.user_id });
      publishDomainEvent('project', 'created', tenant_id, { project: rows[0] });
      res.status(201).json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Update project
  app.put('/api/projects/:id', requireAuth, requireRole('member', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      if ((await runHook('project', 'beforeUpdate', { req, res, tenantId: tenant_id, entity: 'project', action: 'update', id: req.params.id, input: req.body })) === false) return;
      const fields = req.body;
      validateUpdateProject(fields);
      if (!fields || Object.keys(fields).length === 0) {
        return res.status(400).json({ error: 'No fields to update' });
      }

      const allowed = ['name', 'description', 'deadline', 'color', 'start_date', 'end_date', 'budget', 'progress', 'is_archived', 'metadata'];
      const setClauses = [];
      const params = [];
      let idx = 1;

      for (const [key, val] of Object.entries(fields)) {
        if (allowed.includes(key)) {
          setClauses.push(key + ' = $' + idx++);
          params.push(val);
        }
      }

      if (setClauses.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
      }

      setClauses.push('updated_at = NOW()');
      params.push(req.params.id, tenant_id);

      const { rows } = await pool.query(
        'UPDATE projects SET ' + setClauses.join(', ') + ' WHERE id = $' + idx++ + ' AND tenant_id = $' + idx++ + ' AND deleted_at IS NULL RETURNING *',
        params
      );
      if (rows.length === 0) return res.status(404).json({ error: 'project not found' });
      await runHook('project', 'afterUpdate', { req, res, tenantId: tenant_id, entity: 'project', action: 'update', id: req.params.id, record: rows[0] });
      emitSocketEvent('project', 'updated', tenant_id, { project: rows[0] });
      publishDomainEvent('project', 'updated', tenant_id, { project: rows[0] });
      emitPushEvent('project', 'updated', tenant_id, { record: rows[0] });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Soft-delete project
  app.delete('/api/projects/:id', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      if ((await runHook('project', 'beforeDelete', { req, res, tenantId: tenant_id, entity: 'project', action: 'delete', id: req.params.id })) === false) return;
      // Tenant isolation enforced — role access enforced by permission middleware
      const { rows } = await pool.query(
        'UPDATE projects SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL RETURNING id',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'project not found' });
      await runHook('project', 'afterDelete', { req, res, tenantId: tenant_id, entity: 'project', action: 'delete', id: rows[0].id });
      emitSocketEvent('project', 'deleted', tenant_id, { id: rows[0].id });
      publishDomainEvent('project', 'deleted', tenant_id, { id: rows[0].id });
      emitPushEvent('project', 'deleted', tenant_id, { record: { id: rows[0].id } });
      res.json({ deleted: true, id: rows[0].id });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // State transitions for project
  app.patch('/api/projects/:id/transition', requireAuth, requireRole('member', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { action } = req.body;
      const transitions = {
        'completed': { from: ["active"], to: 'completed' },
      };

      const transition = transitions[action];
      if (!transition) {
        return res.status(400).json({ error: 'Invalid action. Use: ' + Object.keys(transitions).join(', ') });
      }

      const { rows: current } = await pool.query(
        'SELECT status FROM projects WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (current.length === 0) return res.status(404).json({ error: 'project not found' });

      if (!transition.from.includes(current[0].status)) {
        return res.status(400).json({
          error: 'Cannot ' + action + ' from ' + current[0].status + '. Must be one of: ' + transition.from.join(', '),
        });
      }

      const { rows } = await pool.query(
        'UPDATE projects SET status = $1, updated_at = NOW() WHERE id = $2 AND tenant_id = $3 AND deleted_at IS NULL RETURNING *',
        [transition.to, req.params.id, tenant_id]
      );
      emitSocketEvent('project', 'transition', tenant_id, { project: rows[0], from: transition.from, to: transition.to });
      publishDomainEvent('project', 'transition', tenant_id, { project: rows[0], from: transition.from, to: transition.to });
      res.json({ action, from: transition.from, to: transition.to, project: rows[0] });
      emitPushEvent('project', 'transition', tenant_id, { record: rows[0], from: transition.from, to: transition.to });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

}
