/**
 * 🛣️ CRUD Routes for subscription
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { mapPgError } from '../db/pgErrors.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { generateReference } from '../businessLogic/sequentialrefService.js';
// Socket + push events (no-op if features not generated)
let emitSocketEvent = () => {};
let emitPushEvent   = () => {};
// Domain events (no-op if no feature/notification subscribes)
let publishDomainEvent = () => {};
try {
  const { publishDomainEvent: _pd } = await import('../events/dispatcher.js');
  publishDomainEvent = _pd;
} catch (_) {}
// Lifecycle hooks (no-op if hooks not generated)
let runHook = async () => {};
try {
  const { runHook: _rh } = await import('../hooks/_runtime.js');
  runHook = _rh;
} catch (_) {}

import { validateCreateSubscription, validateUpdateSubscription } from '../validation/subscriptionValidation.js';

export function registerSubscriptionRoutes(app) {

  // List subscriptions
  app.get('/api/subscriptions', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      const { limit = 20, offset = 0, status } = req.query;
      const tenant_id = req.context.tenant_id;
      const params = [tenant_id];
      const conditions = ['tenant_id = $1', 'deleted_at IS NULL'];
      let idx = 2;

      if (status) { conditions.push('status = $' + idx++); params.push(status); }

      const where = 'WHERE ' + conditions.join(' AND ');
      // Pagination guards (#29): a non-numeric ?limit/?offset must not bind NaN
      // (Math.min(NaN,100) is NaN → Postgres error). Coerce with a safe default.
      const _limit  = Math.min(Math.max(parseInt(limit)  || 20, 1), 100);
      const _offset = Math.max(parseInt(offset) || 0, 0);
      params.push(_limit, _offset);

      const countResult = await pool.query('SELECT COUNT(*) as total FROM subscriptions ' + where, params.slice(0, -2));
      const { rows } = await pool.query(
        'SELECT * FROM subscriptions ' + where + ' ORDER BY created_at DESC LIMIT $' + idx++ + ' OFFSET $' + idx++,
        params
      );

      res.json({ data: rows, total: parseInt(countResult.rows[0].total), limit: _limit, offset: _offset });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Get subscription by ID
  app.get('/api/subscriptions/:id', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { rows } = await pool.query(
        'SELECT * FROM subscriptions WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'subscription not found' });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Create subscription
  app.post('/api/subscriptions', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      const tenant_id = req.context.tenant_id;
      if ((await runHook('subscription', 'beforeCreate', { req, res, tenantId: tenant_id, entity: 'subscription', action: 'create', input: req.body })) === false) return;
      const { plan, seats, price_amount, currency, current_period_end, workspace_id, stripe_subscription_id, stripe_customer_id, stripe_price_id, status, current_period_start, cancel_at_period_end, canceled_at, trial_start, trial_end, metadata, invoice_number } = req.body;

      validateCreateSubscription(req.body);

      const _cols = ['tenant_id'];
      const _vals = [tenant_id];
      const _add = (c, v) => { if (v !== undefined) { _cols.push(c); _vals.push(v); } };
      _add('plan', plan);
      _add('seats', seats);
      _add('price_amount', price_amount);
      _add('currency', currency);
      _add('current_period_end', current_period_end);
      _add('workspace_id', workspace_id);
      _add('stripe_subscription_id', stripe_subscription_id);
      _add('stripe_customer_id', stripe_customer_id);
      _add('stripe_price_id', stripe_price_id);
      _add('status', 'trialing');
      _add('current_period_start', current_period_start);
      _add('cancel_at_period_end', cancel_at_period_end);
      _add('canceled_at', canceled_at);
      _add('trial_start', trial_start);
      _add('trial_end', trial_end);
      _add('metadata', metadata);
      _add('invoice_number', await generateReference(tenant_id, 'INV'));
      const _ph = _vals.map((_, i) => '$' + (i + 1));
      const { rows } = await pool.query(
        `INSERT INTO subscriptions (${_cols.join(', ')}) VALUES (${_ph.join(', ')}) RETURNING *`,
        _vals
      );
      await runHook('subscription', 'afterCreate', { req, res, tenantId: tenant_id, entity: 'subscription', action: 'create', input: req.body, record: rows[0] });
      emitSocketEvent('subscription', 'created', tenant_id, { subscription: rows[0] });
      emitPushEvent('subscription', 'created', tenant_id, { record: rows[0], userId: rows[0].owner_id || req.context.user_id });
      publishDomainEvent('subscription', 'created', tenant_id, { subscription: rows[0] });
      res.status(201).json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Update subscription
  app.put('/api/subscriptions/:id', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      if ((await runHook('subscription', 'beforeUpdate', { req, res, tenantId: tenant_id, entity: 'subscription', action: 'update', id: req.params.id, input: req.body })) === false) return;
      const fields = req.body;
      validateUpdateSubscription(fields);
      if (!fields || Object.keys(fields).length === 0) {
        return res.status(400).json({ error: 'No fields to update' });
      }

      const allowed = ['plan', 'seats', 'price_amount', 'currency', 'current_period_end', 'workspace_id', 'stripe_subscription_id', 'stripe_customer_id', 'stripe_price_id', 'current_period_start', 'cancel_at_period_end', 'canceled_at', 'trial_start', 'trial_end', 'metadata'];
      const setClauses = [];
      const params = [];
      let idx = 1;

      for (const [key, val] of Object.entries(fields)) {
        if (allowed.includes(key)) {
          setClauses.push(key + ' = $' + idx++);
          params.push(val);
        }
      }

      if (setClauses.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
      }

      setClauses.push('updated_at = NOW()');
      params.push(req.params.id, tenant_id);

      const { rows } = await pool.query(
        'UPDATE subscriptions SET ' + setClauses.join(', ') + ' WHERE id = $' + idx++ + ' AND tenant_id = $' + idx++ + ' AND deleted_at IS NULL RETURNING *',
        params
      );
      if (rows.length === 0) return res.status(404).json({ error: 'subscription not found' });
      await runHook('subscription', 'afterUpdate', { req, res, tenantId: tenant_id, entity: 'subscription', action: 'update', id: req.params.id, record: rows[0] });
      emitSocketEvent('subscription', 'updated', tenant_id, { subscription: rows[0] });
      publishDomainEvent('subscription', 'updated', tenant_id, { subscription: rows[0] });
      emitPushEvent('subscription', 'updated', tenant_id, { record: rows[0] });
      res.json(rows[0]);
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // Soft-delete subscription
  app.delete('/api/subscriptions/:id', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      if ((await runHook('subscription', 'beforeDelete', { req, res, tenantId: tenant_id, entity: 'subscription', action: 'delete', id: req.params.id })) === false) return;
      // Tenant isolation enforced — role access enforced by permission middleware
      const { rows } = await pool.query(
        'UPDATE subscriptions SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL RETURNING id',
        [req.params.id, tenant_id]
      );
      if (rows.length === 0) return res.status(404).json({ error: 'subscription not found' });
      await runHook('subscription', 'afterDelete', { req, res, tenantId: tenant_id, entity: 'subscription', action: 'delete', id: rows[0].id });
      emitSocketEvent('subscription', 'deleted', tenant_id, { id: rows[0].id });
      publishDomainEvent('subscription', 'deleted', tenant_id, { id: rows[0].id });
      emitPushEvent('subscription', 'deleted', tenant_id, { record: { id: rows[0].id } });
      res.json({ deleted: true, id: rows[0].id });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

  // State transitions for subscription
  app.patch('/api/subscriptions/:id/transition', requireAuth, requireRole('owner', 'admin'), async (req, res) => {
    try {
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(req.params.id)) return res.status(400).json({ code: 'INVALID_ID', message: 'id must be a valid UUID' });
      const tenant_id = req.context.tenant_id;
      const { action } = req.body;
      const transitions = {
        'active': { from: ["trialing"], to: 'active' },
        'cancelled': { from: ["active"], to: 'cancelled' },
      };

      const transition = transitions[action];
      if (!transition) {
        return res.status(400).json({ error: 'Invalid action. Use: ' + Object.keys(transitions).join(', ') });
      }

      const { rows: current } = await pool.query(
        'SELECT status FROM subscriptions WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL',
        [req.params.id, tenant_id]
      );
      if (current.length === 0) return res.status(404).json({ error: 'subscription not found' });

      if (!transition.from.includes(current[0].status)) {
        return res.status(400).json({
          error: 'Cannot ' + action + ' from ' + current[0].status + '. Must be one of: ' + transition.from.join(', '),
        });
      }

      const { rows } = await pool.query(
        'UPDATE subscriptions SET status = $1, updated_at = NOW() WHERE id = $2 AND tenant_id = $3 AND deleted_at IS NULL RETURNING *',
        [transition.to, req.params.id, tenant_id]
      );
      emitSocketEvent('subscription', 'transition', tenant_id, { subscription: rows[0], from: transition.from, to: transition.to });
      publishDomainEvent('subscription', 'transition', tenant_id, { subscription: rows[0], from: transition.from, to: transition.to });
      res.json({ action, from: transition.from, to: transition.to, subscription: rows[0] });
      emitPushEvent('subscription', 'transition', tenant_id, { record: rows[0], from: transition.from, to: transition.to });
    } catch (err) {
      const _pg = mapPgError(err);
      if (_pg) return res.status(_pg.status).json({ code: _pg.code, error: _pg.message });
      const _st = (err && Number.isInteger(err.status) && err.status >= 400 && err.status < 500) ? err.status : 500;
      res.status(_st).json({ error: (_st === 500 && process.env.NODE_ENV === 'production') ? 'Internal server error' : err.message });
    }
  });

}
