'use strict'

/**
 * upload.routes.js
 * Generated by Forgx — S3 presigned upload endpoint
 *
 * POST /uploads/presign
 *   → Returns a presigned S3 PUT URL for client-side direct upload
 *   → Client uploads file bytes directly to S3 — server never touches file data
 *   → After upload, client stores the returned key in the application database
 */

import express from 'express'
import { requireAuth } from '../middleware/authMiddleware.js'
import { generateUploadKey, getPresignedUploadUrl } from '../services/s3.service.js'
const router         = express.Router()

/**
 * POST /uploads/presign
 *
 * Body:
 *   mimeType   {string}  — required — MIME type of the file to upload
 *   expiresIn  {number}  — optional — URL lifetime in seconds (default 300, max 3600)
 *
 * Response 200:
 *   key        {string}  — S3 object key; store this in your DB after upload
 *   url        {string}  — presigned PUT URL; client uploads directly to this
 *   expiresAt  {string}  — ISO timestamp when the URL expires
 *
 * Response 400:
 *   error      {string}  — validation error message
 *
 * Response 401:
 *   error      {string}  — not authenticated
 */
router.post('/presign', requireAuth, async (req, res) => {
  const { mimeType, expiresIn } = req.body

  if (!mimeType || typeof mimeType !== 'string') {
    return res.status(400).json({ error: 'mimeType is required' })
  }

  const parsedExpiry = expiresIn !== undefined ? Number(expiresIn) : undefined
  if (parsedExpiry !== undefined && (!Number.isFinite(parsedExpiry) || parsedExpiry < 1)) {
    return res.status(400).json({ error: 'expiresIn must be a positive number' })
  }

  try {
    const key    = generateUploadKey(req.context.tenant_id, req.context.user_id, mimeType)
    const result = await getPresignedUploadUrl(key, mimeType, parsedExpiry)
    return res.status(200).json(result)
  } catch (err) {
    if (err.code === 'UNSUPPORTED_MIME_TYPE' || err.code === 'INVALID_ARGUMENT') {
      return res.status(400).json({ error: err.message })
    }
    console.error('[upload.routes] presign error:', err)
    return res.status(500).json({ error: 'Failed to generate upload URL' })
  }
})

export default router
