/**
 * 🔐 Auth Service — teamflow
 * Auto-generated by Backend Factory
 */

import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import { pool } from '../db/pg.js';

const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || '15m';
const REFRESH_EXPIRES_DAYS = parseInt(process.env.REFRESH_EXPIRES_DAYS || '30');

if (!JWT_SECRET) throw new Error('Missing JWT_SECRET in .env');

export const VALID_ROLES = ['admin', 'guest', 'member', 'owner', 'user'];

export async function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  return new Promise((resolve, reject) => {
    crypto.pbkdf2(password, salt, 310000, 32, 'sha256', (err, hash) => {
      if (err) return reject(err);
      resolve(salt + ':' + hash.toString('hex'));
    });
  });
}

export async function verifyPassword(password, stored) {
  return new Promise((resolve) => {
    try {
      const [salt, hash] = String(stored || '').split(':');
      if (!salt || !hash) return resolve(false);
      const storedBuf = Buffer.from(hash, 'hex');
      crypto.pbkdf2(password, salt, 310000, 32, 'sha256', (err, derived) => {
        if (err || storedBuf.length !== derived.length) return resolve(false);
        try { resolve(crypto.timingSafeEqual(storedBuf, derived)); }
        catch (_) { resolve(false); }
      });
    } catch (_) { resolve(false); }
  });
}

export function signToken(payload) {
  return jwt.sign(
    { sub: payload.userId, tenant_id: payload.tenantId, role: payload.role, email: payload.email, locale: payload.locale || null },
    JWT_SECRET,
    { expiresIn: JWT_EXPIRES_IN, algorithm: 'HS256' }
  );
}

export function verifyToken(token) {
  try {
    // Pin the algorithm allow-list (SEC-5): without it jwt.verify accepts any
    // algorithm the token claims. HMAC-only here, so this closes the theoretical
    // alg-confusion door and rejects anything but the HS256 we issue.
    return { valid: true, payload: jwt.verify(token, JWT_SECRET, { algorithms: ['HS256'] }) };
  } catch (err) {
    return { valid: false, error: err.message };
  }
}

export async function createRefreshToken(userId, tenantId) {
  const raw = crypto.randomBytes(64).toString('hex');
  const hash = crypto.createHash('sha256').update(raw).digest('hex');
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + REFRESH_EXPIRES_DAYS);
  await pool.query(
    'INSERT INTO refresh_tokens (user_id, tenant_id, token_hash, expires_at) VALUES ($1, $2, $3, $4)',
    [userId, tenantId, hash, expiresAt]
  );
  return raw;
}

export async function rotateRefreshToken(rawToken) {
  const hash = crypto.createHash('sha256').update(rawToken).digest('hex');
  const { rows } = await pool.query(
    `SELECT rt.*, u.role, u.email FROM refresh_tokens rt
     JOIN users u ON u.id = rt.user_id
     WHERE rt.token_hash = $1 AND rt.revoked = false AND rt.expires_at > NOW()`,
    [hash]
  );
  if (rows.length === 0) return null;
  const old = rows[0];
  await pool.query('UPDATE refresh_tokens SET revoked = true WHERE id = $1', [old.id]);
  const accessToken = signToken({ userId: old.user_id, tenantId: old.tenant_id, role: old.role, email: old.email });
  const newRefreshToken = await createRefreshToken(old.user_id, old.tenant_id);
  return { accessToken, refreshToken: newRefreshToken };
}

export async function revokeRefreshToken(rawToken) {
  const hash = crypto.createHash('sha256').update(rawToken).digest('hex');
  await pool.query('UPDATE refresh_tokens SET revoked = true WHERE token_hash = $1', [hash]);
}
