'use strict'

/**
 * lambda.service.js
 * Generated by Forgx — AWS Lambda integration
 *
 * Active patterns: Lambda SDK Invocation
 *
 * ENV required:
 *   AWS_ACCESS_KEY_ID        — IAM user access key
 *   AWS_SECRET_ACCESS_KEY    — IAM user secret key
 *   AWS_LAMBDA_REGION        — function region
 *   AWS_LAMBDA_FUNCTION_NAME — function name (used by SDK invocation)
 *   AWS_LAMBDA_FUNCTION_URL  — public HTTPS endpoint (used by Function URL calls)
 *
 * Security: callers cannot target arbitrary Lambda functions — only the function
 * provisioned for this app (AWS_LAMBDA_FUNCTION_NAME / AWS_LAMBDA_FUNCTION_URL)
 * is accessible from this service.
 */

// ═══════════════════════════════════════════════════════════════════════════════
// SDK INVOCATION
// ═══════════════════════════════════════════════════════════════════════════════

import { LambdaClient, InvokeCommand } from '@aws-sdk/client-lambda'

// ── Lambda SDK client singleton ────────────────────────────────────────────────

let _lambdaClient = null

function _getClient() {
  if (_lambdaClient) return _lambdaClient

  const accessKeyId     = process.env.AWS_ACCESS_KEY_ID
  const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY
  const region          = process.env.AWS_LAMBDA_REGION

  if (!accessKeyId || !secretAccessKey || !region) {
    throw new Error(
      '[lambda.service] AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_LAMBDA_REGION ' +
      'must be set. Check your .env file.'
    )
  }

  _lambdaClient = new LambdaClient({
    region,
    credentials: { accessKeyId, secretAccessKey },
  })

  return _lambdaClient
}

function _wrapLambdaError(err, context) {
  const msg     = err?.message ?? String(err)
  const wrapped = new Error(`[lambda.service] ${context}: ${msg}`)
  wrapped.code   = err?.name ?? err?.code ?? 'LAMBDA_ERROR'
  wrapped.status = err?.$metadata?.httpStatusCode ?? null
  return wrapped
}

// Allowed invocation types — anything else is rejected before hitting the SDK
const VALID_INVOCATION_TYPES = Object.freeze(new Set(['RequestResponse', 'Event']))

// 5 MB payload cap — Lambda's hard limit is 6 MB synchronous / 256 KB async.
// We apply the same cap for both to keep things simple and safe.
const MAX_INVOKE_PAYLOAD_BYTES = 5 * 1024 * 1024

/**
 * Invoke the app's Lambda function via the AWS SDK.
 *
 * Two invocation types:
 *   RequestResponse (default) — synchronous: waits for the function to finish
 *     and returns its response. Use for data processing, AI calls, etc.
 *   Event — asynchronous fire-and-forget: returns immediately with HTTP 202.
 *     Use for background jobs (image resize, email batch, report generation).
 *
 * @param {object} [payload={}]              — JSON-serialisable event object
 * @param {object} [options={}]
 * @param {'RequestResponse'|'Event'} [options.invocationType='RequestResponse']
 * @param {string} [options.qualifier]       — function version or alias (e.g. 'LIVE', '3')
 * @returns {Promise<{
 *   invocationType: string,
 *   statusCode:     number,
 *   body:           object|string|null,
 * }>}
 */
async function invokeFunction(payload = {}, options = {}) {
  if (typeof payload !== 'object' || payload === null || Array.isArray(payload)) {
    throw Object.assign(new Error('payload must be a plain object'), { statusCode: 400 })
  }

  const { invocationType = 'RequestResponse', qualifier } = options

  if (!VALID_INVOCATION_TYPES.has(invocationType)) {
    throw Object.assign(
      new Error(`invocationType must be one of: ${[...VALID_INVOCATION_TYPES].join(', ')}`),
      { statusCode: 400 }
    )
  }

  if (qualifier !== undefined && (typeof qualifier !== 'string' || !qualifier.trim())) {
    throw Object.assign(new Error('qualifier must be a non-empty string'), { statusCode: 400 })
  }

  const functionName = process.env.AWS_LAMBDA_FUNCTION_NAME
  if (!functionName || !functionName.trim()) {
    throw new Error('[lambda.service] AWS_LAMBDA_FUNCTION_NAME must be set')
  }

  const serialised = JSON.stringify(payload)
  if (Buffer.byteLength(serialised, 'utf8') > MAX_INVOKE_PAYLOAD_BYTES) {
    throw Object.assign(
      new Error(`payload exceeds ${MAX_INVOKE_PAYLOAD_BYTES / (1024 * 1024)} MB limit`),
      { statusCode: 400 }
    )
  }

  const client = _getClient()

  let res
  try {
    res = await client.send(new InvokeCommand({
      FunctionName:   functionName.trim(),
      InvocationType: invocationType,
      Payload:        Buffer.from(serialised),
      ...(qualifier ? { Qualifier: qualifier.trim() } : {}),
    }))
  } catch (err) {
    throw _wrapLambdaError(err, `invokeFunction('${functionName}')`)
  }

  // Async invocations return 202 with no payload
  if (invocationType === 'Event') {
    return { invocationType, statusCode: res.StatusCode ?? 202, body: null }
  }

  // Lambda-level function errors: the function ran but threw an exception.
  // We expose only errorMessage (≤200 chars) — never the full stack trace.
  if (res.FunctionError) {
    const rawPayload = res.Payload ? Buffer.from(res.Payload).toString('utf8') : ''
    let errMsg = `Lambda function error (${res.FunctionError})`
    try {
      const parsed = JSON.parse(rawPayload)
      if (parsed.errorMessage && typeof parsed.errorMessage === 'string') {
        errMsg += `: ${parsed.errorMessage.slice(0, 200)}`
      }
    } catch { /* non-JSON error payload — use generic message */ }
    throw Object.assign(new Error(errMsg), { statusCode: 502 })
  }

  const responseText = res.Payload ? Buffer.from(res.Payload).toString('utf8') : ''

  let body = null
  if (responseText) {
    try {
      body = JSON.parse(responseText)
    } catch {
      body = responseText
    }
  }

  return { invocationType, statusCode: res.StatusCode ?? 200, body }
}

export {
  invokeFunction,
}
