'use strict'

/**
 * s3.service.js
 * Generated by Forgx — AWS S3 integration
 *
 * Active patterns: S3 Presigned Upload, S3 Presigned Download, S3 Object Deletion
 *
 * ENV required:
 *   AWS_ACCESS_KEY_ID     — IAM user access key
 *   AWS_SECRET_ACCESS_KEY — IAM user secret key
 *   AWS_S3_BUCKET         — S3 bucket name
 *   AWS_S3_REGION         — S3 bucket region
 *
 * Dependencies: @aws-sdk/client-s3, @aws-sdk/s3-request-presigner
 */

import { S3Client, DeleteObjectCommand, HeadObjectCommand, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import crypto from 'crypto'

// ── S3 client singleton ────────────────────────────────────────────────────────
// Validates required env vars on first use — fails fast with a clear message.

let _s3 = null

function _getClient() {
  if (_s3) return _s3

  const accessKeyId     = process.env.AWS_ACCESS_KEY_ID
  const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY
  const region          = process.env.AWS_S3_REGION
  const bucket          = process.env.AWS_S3_BUCKET

  if (!accessKeyId || !secretAccessKey || !region || !bucket) {
    throw new Error(
      '[s3.service] AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_S3_REGION, and ' +
      'AWS_S3_BUCKET must be set. Check your .env file.'
    )
  }

  _s3 = new S3Client({
    region,
    credentials: { accessKeyId, secretAccessKey },
  })

  return _s3
}

// ── Shared validators ──────────────────────────────────────────────────────────

/**
 * Validate an S3 object key.
 * S3 keys can be up to 1024 bytes. We reject patterns that are dangerous
 * in signed URL contexts: path traversal, control characters, leading slash.
 */
function _assertS3Key(key, label = 'key') {
  if (!key || typeof key !== 'string') {
    throw Object.assign(new Error(`${label} must be a non-empty string`), { code: 'INVALID_ARGUMENT' })
  }
  if (key.length > 1024) {
    throw Object.assign(new Error(`${label} exceeds S3 maximum key length of 1024 bytes`), { code: 'INVALID_ARGUMENT' })
  }
  if (key.startsWith('/')) {
    throw Object.assign(new Error(`${label} must not start with '/'`), { code: 'INVALID_ARGUMENT' })
  }
  if (/[\x00-\x1f\x7f]/.test(key)) {
    throw Object.assign(new Error(`${label} contains invalid control characters`), { code: 'INVALID_ARGUMENT' })
  }
  // Reject path traversal sequences anywhere in the key
  if (/(^|\/)\.\.(\/|$)/.test(key)) {
    throw Object.assign(new Error(`${label} must not contain path traversal sequences (..)`), { code: 'INVALID_PATH' })
  }
}

/**
 * Wrap S3 SDK errors into a consistent shape.
 */
function _wrapS3Error(err, context) {
  const msg     = err?.message ?? String(err)
  const wrapped = new Error(`[s3.service] ${context}: ${msg}`)
  wrapped.code   = err?.Code ?? err?.code ?? 'S3_ERROR'
  wrapped.status = err?.$metadata?.httpStatusCode ?? null
  return wrapped
}

// ═══════════════════════════════════════════════════════════════════════════════
// PRESIGNED UPLOAD
// ═══════════════════════════════════════════════════════════════════════════════

// Upload URL default/max expiry — short window minimises abuse of signed URLs.
const UPLOAD_EXPIRY_DEFAULT_S = 5  * 60   // 5 minutes
const UPLOAD_EXPIRY_MAX_S     = 60 * 60   // 60 minutes hard cap

// Allowlisted MIME types for upload.
// Add types here as the application needs grow.
const UPLOAD_ALLOWED_MIME = new Set([
  'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml',
  'application/pdf',
  'text/plain', 'text/csv',
  'application/json',
  'application/zip',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'video/mp4', 'video/webm',
  'audio/mpeg', 'audio/ogg',
])

// Extension map for key generation — keeps keys human-readable.
const MIME_TO_EXT = {
  'image/jpeg':        'jpg',
  'image/png':         'png',
  'image/webp':        'webp',
  'image/gif':         'gif',
  'image/svg+xml':     'svg',
  'application/pdf':   'pdf',
  'text/plain':        'txt',
  'text/csv':          'csv',
  'application/json':  'json',
  'application/zip':   'zip',
  'application/vnd.ms-excel': 'xls',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
  'application/msword': 'doc',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
  'video/mp4':         'mp4',
  'video/webm':        'webm',
  'audio/mpeg':        'mp3',
  'audio/ogg':         'ogg',
}

/**
 * Generate a collision-proof S3 key for a user upload.
 * Format: {userId}/{timestamp}-{16hex}.{ext}
 *
 * - userId prefix enables per-user IAM policy scoping (s3:prefix condition)
 * - timestamp keeps objects chronologically orderable in the bucket
 * - 8 random bytes (16 hex chars) = 2^64 collision space
 *
 * @param {string} userId
 * @param {string} mimeType
 * @returns {string}
 */
function generateUploadKey(tenantId, userId, mimeType) {
  if (!tenantId || typeof tenantId !== 'string' || !tenantId.trim()) {
    throw Object.assign(new Error('tenantId must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }
  if (!userId || typeof userId !== 'string' || !userId.trim()) {
    throw Object.assign(new Error('userId must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }

  // Tenant-first key namespace: every stored object lives under '<tenant_id>/…' so
  // downstream validation can assert a key belongs to the caller's tenant.
  // Strip characters that are problematic in S3 keys / URLs from both prefixes.
  const safeTenantId = tenantId.replace(/[^\w\-]/g, '_').slice(0, 64)
  const safeUserId   = userId.replace(/[^\w\-]/g, '_').slice(0, 64)
  const ext          = MIME_TO_EXT[mimeType] ?? 'bin'
  const ts           = Date.now()
  const rnd          = crypto.randomBytes(8).toString('hex')

  return `${safeTenantId}/${safeUserId}/${ts}-${rnd}.${ext}`
}

/**
 * Generate a presigned PUT URL for client-side direct-to-S3 upload.
 * The server never handles the file bytes — only the presigned URL.
 *
 * Workflow:
 *   1. Client calls POST /uploads/presign with { mimeType }
 *   2. Server calls this function → returns { key, url, expiresAt }
 *   3. Client PUTs the file directly to S3 using the url
 *   4. Client notifies server of completion with the key
 *
 * @param {string} key        — S3 object key (use generateUploadKey())
 * @param {string} mimeType   — must be in UPLOAD_ALLOWED_MIME
 * @param {number} [expiresIn=300] — seconds until URL expires (max 3600)
 * @returns {Promise<{ key: string, url: string, expiresAt: string }>}
 */
async function getPresignedUploadUrl(key, mimeType, expiresIn = UPLOAD_EXPIRY_DEFAULT_S) {
  _assertS3Key(key)

  if (!mimeType || typeof mimeType !== 'string') {
    throw Object.assign(new Error('mimeType must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }
  if (!UPLOAD_ALLOWED_MIME.has(mimeType)) {
    throw Object.assign(
      new Error(`MIME type '${mimeType}' is not permitted for upload`),
      { code: 'UNSUPPORTED_MIME_TYPE' }
    )
  }

  const expiry = Math.min(Math.max(60, expiresIn), UPLOAD_EXPIRY_MAX_S)

  const s3      = _getClient()
  const bucket  = process.env.AWS_S3_BUCKET
  const command = new PutObjectCommand({
    Bucket:      bucket,
    Key:         key,
    ContentType: mimeType,
    // Server-side encryption — all objects encrypted at rest with S3-managed keys.
    ServerSideEncryption: 'AES256',
  })

  let url
  try {
    url = await getSignedUrl(s3, command, { expiresIn: expiry })
  } catch (err) {
    throw _wrapS3Error(err, `getPresignedUploadUrl('${key}')`)
  }

  return {
    key,
    url,
    expiresAt: new Date(Date.now() + expiry * 1000).toISOString(),
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// PRESIGNED DOWNLOAD
// ═══════════════════════════════════════════════════════════════════════════════

const DOWNLOAD_EXPIRY_DEFAULT_S = 15 * 60    // 15 minutes
const DOWNLOAD_EXPIRY_MAX_S     = 60 * 60    // 60 minutes hard cap

/**
 * Generate a presigned GET URL for a private S3 object.
 * Verifies the object exists before signing — avoids leaking that a key was
 * requested when it doesn't exist.
 *
 * Never expose permanent S3 URLs for private objects.
 * Every download link must be scoped to a short window.
 *
 * @param {string} key               — S3 object key
 * @param {number} [expiresIn=900]   — seconds until URL expires (max 3600)
 * @returns {Promise<string>} presigned download URL
 */
async function getPresignedDownloadUrl(key, expiresIn = DOWNLOAD_EXPIRY_DEFAULT_S) {
  _assertS3Key(key)

  const expiry = Math.min(Math.max(60, expiresIn), DOWNLOAD_EXPIRY_MAX_S)

  const s3     = _getClient()
  const bucket = process.env.AWS_S3_BUCKET

  // Existence check — HeadObject does not return the body; cheap metadata-only call.
  try {
    await s3.send(new HeadObjectCommand({ Bucket: bucket, Key: key }))
  } catch (err) {
    const status = err?.$metadata?.httpStatusCode
    if (status === 403 || status === 404) {
      throw Object.assign(
        new Error(`[s3.service] getPresignedDownloadUrl: object '${key}' not found`),
        { code: 'NOT_FOUND' }
      )
    }
    throw _wrapS3Error(err, `getPresignedDownloadUrl head('${key}')`)
  }

  const command = new GetObjectCommand({ Bucket: bucket, Key: key })

  try {
    return await getSignedUrl(s3, command, { expiresIn: expiry })
  } catch (err) {
    throw _wrapS3Error(err, `getPresignedDownloadUrl sign('${key}')`)
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// DELETE OBJECT
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Permanently delete an S3 object.
 * Idempotent — returns successfully whether the object existed or not.
 * S3 DeleteObject does not error on missing keys; this aligns with that behaviour.
 *
 * For production workloads consider enabling S3 Versioning and using a
 * lifecycle rule for delayed permanent deletion. This function issues an
 * immediate hard delete — appropriate when the caller has already performed
 * a soft-delete in the application database.
 *
 * @param {string} key — S3 object key
 * @returns {Promise<void>}
 */
async function deleteObject(key) {
  _assertS3Key(key)

  const s3     = _getClient()
  const bucket = process.env.AWS_S3_BUCKET

  try {
    await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }))
  } catch (err) {
    // S3 DeleteObject never returns 404 — if it throws, it's a real error.
    throw _wrapS3Error(err, `deleteObject('${key}')`)
  }
}

export {
  generateUploadKey,
  getPresignedUploadUrl,
  getPresignedDownloadUrl,
  deleteObject,
}
