'use strict'

/**
 * ses.service.js
 * Generated by Forgx — AWS SES email integration
 *
 * Active patterns: SES Transactional Email, SES HTML Template Email
 *
 * ENV required:
 *   AWS_ACCESS_KEY_ID          — IAM user access key
 *   AWS_SECRET_ACCESS_KEY      — IAM user secret key
 *   AWS_SES_REGION             — SES region (e.g. us-east-1)
 *   AWS_SES_FROM_EMAIL         — verified sender address
 *   AWS_SES_CONFIGURATION_SET  — SES configuration set name
 *
 * Dependencies: @aws-sdk/client-ses, bcrypt, pg
 */

import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses'

// ── SES client singleton ───────────────────────────────────────────────────────

let _ses = null

function _getClient() {
  if (_ses) return _ses

  const accessKeyId     = process.env.AWS_ACCESS_KEY_ID
  const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY
  const region          = process.env.AWS_SES_REGION

  if (!accessKeyId || !secretAccessKey || !region) {
    throw new Error(
      '[ses.service] AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SES_REGION ' +
      'must be set. Check your .env file.'
    )
  }

  _ses = new SESClient({
    region,
    credentials: { accessKeyId, secretAccessKey },
  })

  return _ses
}

// ── Shared validators ──────────────────────────────────────────────────────────

/**
 * Validate an email address before passing to SES.
 * SES charges per send — reject garbage inputs before they hit the API.
 */
function _assertEmail(email, label = 'email') {
  if (!email || typeof email !== 'string') {
    throw Object.assign(new Error(`${label} must be a non-empty string`), { code: 'INVALID_ARGUMENT' })
  }
  if (email.length > 254) {
    throw Object.assign(new Error(`${label} exceeds maximum length of 254 characters`), { code: 'INVALID_ARGUMENT' })
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) {
    throw Object.assign(new Error(`'${email}' is not a valid email address`), { code: 'INVALID_ARGUMENT' })
  }
}

/**
 * Wrap SES SDK errors into a consistent shape.
 */
function _wrapSesError(err, context) {
  const msg     = err?.message ?? String(err)
  const wrapped = new Error(`[ses.service] ${context}: ${msg}`)
  wrapped.code   = err?.name ?? err?.code ?? 'SES_ERROR'
  wrapped.status = err?.$metadata?.httpStatusCode ?? null
  return wrapped
}

// ═══════════════════════════════════════════════════════════════════════════════
// TRANSACTIONAL EMAIL
// ═══════════════════════════════════════════════════════════════════════════════

const MAX_SUBJECT_LEN = 998    // RFC 2822 line-length limit
const MAX_HTML_BYTES  = 50 * 1024   // 50 KB — well under SES 10 MB limit but sane for transactional

/**
 * Send a single transactional email via SES.
 *
 * AWS SES sandbox: in sandbox mode only verified email addresses can receive mail.
 * Request production access in the AWS console before going live.
 *
 * @param {object}   params
 * @param {string}   params.to        — recipient email address
 * @param {string}   params.subject   — email subject (max 998 chars)
 * @param {string}   params.html      — HTML body (max 50 KB)
 * @param {string}   [params.text]    — plain-text fallback (recommended for deliverability)
 * @param {string}   [params.replyTo] — reply-to address (defaults to from address)
 * @returns {Promise<{ messageId: string }>}
 */
async function sendEmail({ to, subject, html, text, replyTo }) {
  _assertEmail(to, 'to')

  if (!subject || typeof subject !== 'string' || !subject.trim()) {
    throw Object.assign(new Error('subject must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }
  if (subject.length > MAX_SUBJECT_LEN) {
    throw Object.assign(
      new Error(`subject exceeds maximum length of ${MAX_SUBJECT_LEN} characters`),
      { code: 'INVALID_ARGUMENT' }
    )
  }

  if (!html || typeof html !== 'string' || !html.trim()) {
    throw Object.assign(new Error('html body must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }
  if (Buffer.byteLength(html, 'utf8') > MAX_HTML_BYTES) {
    throw Object.assign(
      new Error(`html body exceeds ${MAX_HTML_BYTES / 1024} KB limit`),
      { code: 'PAYLOAD_TOO_LARGE' }
    )
  }

  if (replyTo !== undefined) _assertEmail(replyTo, 'replyTo')

  const fromEmail = process.env.AWS_SES_FROM_EMAIL
  const configSet = process.env.AWS_SES_CONFIGURATION_SET

  if (!fromEmail) {
    throw new Error('[ses.service] AWS_SES_FROM_EMAIL must be set')
  }

  const ses = _getClient()

  const input = {
    Source: fromEmail,
    Destination: { ToAddresses: [to] },
    Message: {
      Subject: { Data: subject.trim(), Charset: 'UTF-8' },
      Body: {
        Html: { Data: html, Charset: 'UTF-8' },
        ...(text ? { Text: { Data: text, Charset: 'UTF-8' } } : {}),
      },
    },
    ...(replyTo ? { ReplyToAddresses: [replyTo] } : {}),
    // ConfigurationSetName enables delivery events (bounces, complaints, opens)
    ...(configSet ? { ConfigurationSetName: configSet } : {}),
  }

  let res
  try {
    res = await ses.send(new SendEmailCommand(input))
  } catch (err) {
    throw _wrapSesError(err, `sendEmail(to='${to}')`)
  }

  return { messageId: res.MessageId }
}

// ═══════════════════════════════════════════════════════════════════════════════
// TEMPLATE EMAIL
// ═══════════════════════════════════════════════════════════════════════════════

import fs from 'fs'
import path from 'path'

const TEMPLATES_DIR      = path.join(__dirname, '..', 'email-templates')
const MAX_VAR_VALUE_LEN  = 2048    // max length for any single template variable value
const TEMPLATE_NAME_RE   = /^[a-z0-9_-]{1,64}$/   // safe template names only

/**
 * Escape special HTML characters in a string.
 * Applied to ALL template variable values to prevent XSS via injected variables.
 * Email clients render HTML — an unescaped variable is a stored XSS vector.
 */
function _escapeHtml(str) {
  return String(str)
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&#x27;')
    .replace(/\//g, '&#x2F;')
}

/**
 * Replace all occurrences of {{KEY}} in a template string with the matching value.
 * All values are HTML-escaped before substitution.
 * Unresolved {{KEY}} placeholders are left as empty strings — never leak template syntax.
 *
 * @param {string}              template
 * @param {Record<string, *>}   data
 * @returns {string}
 */
function _interpolate(template, data) {
  return template.replace(/\{\{([A-Z0-9_]+)\}\}/g, (_, key) => {
    const val = data[key]
    if (val === undefined || val === null) return ''
    return _escapeHtml(String(val))
  })
}

/**
 * Send an HTML template email.
 * Reads {templateName}.html from src/email-templates/, wraps it in base.html,
 * substitutes {{VARIABLE}} placeholders with escaped values from data.
 *
 * Template variable names: uppercase alphanumeric + underscores — {{ORDER_ID}}, {{USER_NAME}}.
 * All values are HTML-escaped — never pass raw HTML as a variable value.
 *
 * @param {object}              params
 * @param {string}              params.to            — recipient email
 * @param {string}              params.subject       — email subject
 * @param {string}              params.templateName  — template file name (no extension, no path)
 * @param {Record<string, *>}   params.data          — template variable values
 * @returns {Promise<{ messageId: string }>}
 */
async function sendTemplateEmail({ to, subject, templateName, data = {} }) {
  _assertEmail(to, 'to')

  if (!subject || typeof subject !== 'string' || !subject.trim()) {
    throw Object.assign(new Error('subject must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }

  if (!templateName || typeof templateName !== 'string') {
    throw Object.assign(new Error('templateName must be a non-empty string'), { code: 'INVALID_ARGUMENT' })
  }
  if (!TEMPLATE_NAME_RE.test(templateName)) {
    throw Object.assign(
      new Error('templateName must contain only lowercase alphanumeric characters, hyphens, and underscores'),
      { code: 'INVALID_ARGUMENT' }
    )
  }

  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    throw Object.assign(new Error('data must be a plain object'), { code: 'INVALID_ARGUMENT' })
  }

  // Validate data value lengths — prevent outsized content from reaching SES
  for (const [key, val] of Object.entries(data)) {
    if (String(val).length > MAX_VAR_VALUE_LEN) {
      throw Object.assign(
        new Error(`Template variable '${key}' exceeds maximum length of ${MAX_VAR_VALUE_LEN} characters`),
        { code: 'INVALID_ARGUMENT' }
      )
    }
  }

  // Resolve template file path — TEMPLATES_DIR is a fixed constant, not user-provided
  const templatePath = path.join(TEMPLATES_DIR, `${templateName}.html`)
  const basePath     = path.join(TEMPLATES_DIR, 'base.html')

  if (!fs.existsSync(templatePath)) {
    throw Object.assign(
      new Error(`Email template '${templateName}' not found at ${templatePath}`),
      { code: 'TEMPLATE_NOT_FOUND' }
    )
  }
  if (!fs.existsSync(basePath)) {
    throw Object.assign(
      new Error(`Base email template not found at ${basePath}`),
      { code: 'TEMPLATE_NOT_FOUND' }
    )
  }

  const templateContent = fs.readFileSync(templatePath, 'utf8')
  const baseContent     = fs.readFileSync(basePath, 'utf8')

  // First interpolate variables into the template
  const interpolatedContent = _interpolate(templateContent, data)

  // Then inject the rendered template into the base layout
  const finalHtml = baseContent.replace('{{CONTENT}}', interpolatedContent)

  // Plain-text fallback: strip HTML tags from the final output
  const plainText = finalHtml.replace(/<[^>]+>/g, ' ').replace(/\s{2,}/g, ' ').trim()

  return sendEmail({ to, subject: subject.trim(), html: finalHtml, text: plainText })
}

export {
  sendEmail,
  sendTemplateEmail,
}
