/**
 * 📧 Email Service
 * Auto-generated by Backend Factory
 *
 * Provider-agnostic email sending.
 * Supports: SES, SendGrid, Mailgun, SMTP, Console (dev).
 */

const EMAIL_PROVIDER = process.env.EMAIL_PROVIDER || 'ses';
const EMAIL_FROM = process.env.EMAIL_FROM || 'noreply@app.com';
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY || '';
const MAILGUN_API_KEY = process.env.MAILGUN_API_KEY || '';
const MAILGUN_DOMAIN = process.env.MAILGUN_DOMAIN || '';

const stats = { sent: 0, failed: 0, queued: 0 };
const sentLog = [];

/**
 * Send an email
 * @param {object} opts - { to, subject, html, text, from, replyTo }
 * @returns {object} { success, messageId, provider }
 */
export async function sendEmail(opts) {
  const { to, subject, html, text, from = EMAIL_FROM, replyTo } = opts;

  if (!to || !subject) {
    throw new Error('Email requires to and subject');
  }

  const email = { to, subject, html, text, from, replyTo, sentAt: new Date().toISOString() };

  try {
    let result;

    switch (EMAIL_PROVIDER) {
      case 'ses':
        result = await sendViaSes(email);
        break;
      case 'sendgrid':
        result = await sendViaSendGrid(email);
        break;
      case 'mailgun':
        result = await sendViaMailgun(email);
        break;
      case 'smtp':
        result = await sendViaSMTP(email);
        break;
      default:
        result = sendViaConsole(email);
    }

    stats.sent++;
    sentLog.push({ ...email, status: 'sent', messageId: result.messageId });
    if (sentLog.length > 100) sentLog.shift();
    return { success: true, ...result };

  } catch (err) {
    stats.failed++;
    sentLog.push({ ...email, status: 'failed', error: err.message });
    // #H4: surface the failure — a swallowed send (missing @aws-sdk/client-ses,
    // bad creds, sandbox block) previously produced a totally SILENT no-op.
    console.warn('[email] send failed via ' + EMAIL_PROVIDER + ': ' + err.message);
    return { success: false, error: err.message };
  }
}

/**
 * Send via the generated ses.service.js (declared ## Services: ses).
 * Lazy import: an unconfigured SES service degrades to a loud per-send
 * error, never a boot crash.
 */
async function sendViaSes(email) {
  const ses = await import('../services/ses.service.js');
  const result = await ses.sendEmail({ to: email.to, subject: email.subject, html: email.html, text: email.text, replyTo: email.replyTo });
  return { messageId: (result && result.messageId) || ('ses-' + Date.now()), provider: 'ses' };
}

/**
 * Send via SendGrid
 */
async function sendViaSendGrid(email) {
  const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + SENDGRID_API_KEY,
    },
    body: JSON.stringify({
      personalizations: [{ to: [{ email: email.to }] }],
      from: { email: email.from },
      subject: email.subject,
      content: [
        email.text ? { type: 'text/plain', value: email.text } : null,
        email.html ? { type: 'text/html', value: email.html } : null,
      ].filter(Boolean),
    }),
  });

  if (!response.ok) throw new Error('SendGrid error: ' + response.status);
  return { provider: 'sendgrid', messageId: response.headers.get('x-message-id') || 'sg_' + Date.now() };
}

/**
 * Send via Mailgun
 */
async function sendViaMailgun(email) {
  const form = new URLSearchParams();
  form.append('from', email.from);
  form.append('to', email.to);
  form.append('subject', email.subject);
  if (email.text) form.append('text', email.text);
  if (email.html) form.append('html', email.html);

  const response = await fetch('https://api.mailgun.net/v3/' + MAILGUN_DOMAIN + '/messages', {
    method: 'POST',
    headers: {
      'Authorization': 'Basic ' + Buffer.from('api:' + MAILGUN_API_KEY).toString('base64'),
    },
    body: form,
  });

  if (!response.ok) throw new Error('Mailgun error: ' + response.status);
  const data = await response.json();
  return { provider: 'mailgun', messageId: data.id || 'mg_' + Date.now() };
}

/**
 * Send via SMTP using nodemailer (a real dependency). Fails LOUDLY when the
 * provider is selected but unconfigured — never reports a silent fake success (#16).
 */
async function sendViaSMTP(email) {
  const { default: nodemailer } = await import('nodemailer');
  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || '587', 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  if (!host || !user || !pass) {
    const err = new Error('EMAIL_PROVIDER=smtp but SMTP_HOST/SMTP_USER/SMTP_PASS are not configured');
    err.status = 500;
    throw err;
  }
  const transporter = nodemailer.createTransport({ host, port, secure: port === 465, auth: { user, pass } });
  const info = await transporter.sendMail({
    from: process.env.SMTP_FROM || user,
    to: email.to, subject: email.subject, text: email.text, html: email.html,
  });
  return { provider: 'smtp', messageId: info.messageId };
}

/**
 * Console output (development)
 */
function sendViaConsole(email) {
  // LOW-6: console transport in PRODUCTION means EMAIL_PROVIDER was never
  // configured — no real mail is sent. Returning a fake 'sent' here made
  // sendEmail report success while customers received nothing (silent drop).
  // Fail loudly instead so the misconfiguration surfaces; dev is unchanged.
  if (process.env.NODE_ENV === 'production') {
    const err = new Error('EMAIL_PROVIDER is not configured — refusing to fake-send email in production. Set EMAIL_PROVIDER (gmail|ses|sendgrid|mailgun|smtp) and its credentials.');
    err.statusCode = 500;
    throw err;
  }
  console.log('📧 [DEV EMAIL]');
  console.log('   To:', email.to);
  console.log('   Subject:', email.subject);
  console.log('   Text:', (email.text || '').substring(0, 100));
  return { provider: 'console', messageId: 'dev_' + Date.now() };
}

/**
 * Get email stats
 */
export function getEmailStats() {
  return { ...stats, recentLog: sentLog.slice(-10) };
}
