/**
 * 📧 Email Templates for Task
 * Auto-generated by Backend Factory
 */

import { sendEmail } from '../email/emailService.js';
import { wrapHTML, renderTemplate, escapeHtml } from '../email/templateEngine.js';

/**
 * Send email when task is created
 */
export async function sendTaskCreatedEmail(record, recipientEmail) {
  const subject = 'New Task Created: ' + (record.name || record.title || record.id);

  const body = renderTemplate(
    '<h2>New Task Created</h2>' +
    '<p>A new task has been created.</p>' +
    '<table style="width:100%; border-collapse:collapse;">' +
    '<tr><td style="padding:8px; border:1px solid #e5e7eb; font-weight:600;">ID</td>' +
    '<td style="padding:8px; border:1px solid #e5e7eb;">{{id}}</td></tr>' +
    '<tr><td style="padding:8px; border:1px solid #e5e7eb; font-weight:600;">Status</td>' +
    '<td style="padding:8px; border:1px solid #e5e7eb;">{{status}}</td></tr>' +
    '<tr><td style="padding:8px; border:1px solid #e5e7eb; font-weight:600;">Created</td>' +
    '<td style="padding:8px; border:1px solid #e5e7eb;">{{created_at}}</td></tr>' +
    '</table>',
    record
  );

  const html = wrapHTML(subject, body);
  const text = 'New Task created: ' + (record.name || record.title || record.id);

  return sendEmail({ to: recipientEmail, subject, html, text });
}

/**
 * Send email when task is updated
 */
export async function sendTaskUpdatedEmail(record, changes, recipientEmail) {
  const subject = 'Task Updated: ' + (record.name || record.title || record.id);

  const changeRows = Object.entries(changes)
    .map(([key, val]) => '<tr><td style="padding:8px; border:1px solid #e5e7eb;">' + escapeHtml(key) + '</td><td style="padding:8px; border:1px solid #e5e7eb;">' + escapeHtml(val) + '</td></tr>')
    .join('');

  const body = '<h2>Task Updated</h2>' +
    '<p>The following fields were changed:</p>' +
    '<table style="width:100%; border-collapse:collapse;">' +
    '<tr><th style="padding:8px; border:1px solid #e5e7eb; text-align:left;">Field</th>' +
    '<th style="padding:8px; border:1px solid #e5e7eb; text-align:left;">New Value</th></tr>' +
    changeRows + '</table>';

  const html = wrapHTML(subject, body);
  const text = 'Task updated: ' + Object.keys(changes).join(', ');

  return sendEmail({ to: recipientEmail, subject, html, text });
}

