/**
 * 📋 Audit Log Service
 * Auto-generated by Backend Factory
 *
 * Immutable audit trail for all data modifications.
 */

import { pool } from '../db/pg.js';

/**
 * Log an audit event
 * @param {object} opts
 * @param {string} opts.action - 'create' | 'update' | 'delete' | 'login' | 'export' | custom
 * @param {string} opts.entityType - e.g., 'order'
 * @param {string} opts.entityId
 * @param {string} opts.userId - who performed the action
 * @param {string} opts.tenantId
 * @param {object} opts.before - state before change
 * @param {object} opts.after - state after change
 * @param {object} opts.metadata - { ip, userAgent, requestId }
 */
export async function logAudit(opts) {
  const {
    action, entityType, entityId, userId, tenantId,
    before = null, after = null, metadata = {},
  } = opts;

  const changes = before && after ? computeDiff(before, after) : null;

  await pool.query(
    `INSERT INTO audit_logs
     (action, entity_type, entity_id, user_id, tenant_id, before_data, after_data, changes, ip_address, user_agent, request_id, created_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())`,
    [
      action, entityType, entityId || null, userId || null, tenantId || null,
      before ? JSON.stringify(before) : null,
      after ? JSON.stringify(after) : null,
      changes ? JSON.stringify(changes) : null,
      metadata.ip || null,
      metadata.userAgent || null,
      metadata.requestId || null,
    ]
  );
}

/**
 * Compute diff between before and after states
 */
function computeDiff(before, after) {
  const changes = [];
  const allKeys = new Set([...Object.keys(before || {}), ...Object.keys(after || {})]);

  for (const key of allKeys) {
    if (key === 'updated_at' || key === 'created_at') continue;
    const oldVal = before ? before[key] : undefined;
    const newVal = after ? after[key] : undefined;
    if (JSON.stringify(oldVal) !== JSON.stringify(newVal)) {
      changes.push({ field: key, from: oldVal, to: newVal });
    }
  }

  return changes;
}

/**
 * Query audit logs
 * @param {object} opts - { entityType, entityId, userId, action, tenantId, from, to, limit, offset }
 */
export async function queryAuditLogs(opts = {}) {
  const { entityType, entityId, userId, action, tenantId, from, to, limit = 50, offset = 0 } = opts;

  const conditions = [];
  const params = [];
  let idx = 1;

  if (entityType) { conditions.push('entity_type = $' + idx++); params.push(entityType); }
  if (entityId) { conditions.push('entity_id = $' + idx++); params.push(entityId); }
  if (userId) { conditions.push('user_id = $' + idx++); params.push(userId); }
  if (action) { conditions.push('action = $' + idx++); params.push(action); }
  if (tenantId) { conditions.push('tenant_id = $' + idx++); params.push(tenantId); }
  if (from) { conditions.push('created_at >= $' + idx++); params.push(from); }
  if (to) { conditions.push('created_at <= $' + idx++); params.push(to); }

  const where = conditions.length > 0 ? 'WHERE ' + conditions.join(' AND ') : '';

  // Count
  const countResult = await pool.query('SELECT COUNT(*) as total FROM audit_logs ' + where, params);
  const total = parseInt(countResult.rows[0].total);

  // Data
  params.push(Math.min(limit, 200), offset);
  const { rows } = await pool.query(
    'SELECT * FROM audit_logs ' + where + ' ORDER BY created_at DESC LIMIT $' + idx++ + ' OFFSET $' + idx++,
    params
  );

  return { data: rows, total, limit, offset };
}

/**
 * Get full change history for a single entity
 */
export async function getEntityHistory(tenantId, entityType, entityId) {
  const { rows } = await pool.query(
    'SELECT * FROM audit_logs WHERE tenant_id = $1 AND entity_type = $2 AND entity_id = $3 ORDER BY created_at ASC',
    [tenantId, entityType, entityId]
  );
  return rows;
}

/**
 * Get all actions by a user
 */
export async function getUserActivity(tenantId, userId, opts = {}) {
  const { limit = 50, days = 30 } = opts;
  const { rows } = await pool.query(
    `SELECT action, entity_type, entity_id, created_at FROM audit_logs
     WHERE tenant_id = $1 AND user_id = $2 AND created_at > NOW() - ($3 || ' days')::INTERVAL
     ORDER BY created_at DESC LIMIT $4`,
    [tenantId, userId, days, limit]
  );
  return rows;
}

/**
 * Generate compliance summary
 * @param {object} opts - { tenantId, from, to }
 */
export async function getComplianceSummary(opts = {}) {
  const { tenantId, from, to } = opts;
  const params = [];
  const conditions = [];
  let idx = 1;

  if (tenantId) { conditions.push('tenant_id = $' + idx++); params.push(tenantId); }
  if (from) { conditions.push('created_at >= $' + idx++); params.push(from); }
  if (to) { conditions.push('created_at <= $' + idx++); params.push(to); }

  const where = conditions.length > 0 ? 'WHERE ' + conditions.join(' AND ') : '';

  // Action breakdown
  const actionBreakdown = await pool.query(
    'SELECT action, COUNT(*) as count FROM audit_logs ' + where + ' GROUP BY action ORDER BY count DESC',
    params
  );

  // Entity breakdown
  const entityBreakdown = await pool.query(
    'SELECT entity_type, COUNT(*) as count FROM audit_logs ' + where + ' GROUP BY entity_type ORDER BY count DESC',
    params
  );

  // User breakdown
  const userBreakdown = await pool.query(
    'SELECT user_id, COUNT(*) as count FROM audit_logs ' + where + ' GROUP BY user_id ORDER BY count DESC LIMIT 20',
    params
  );

  // Total
  const totalResult = await pool.query('SELECT COUNT(*) as total FROM audit_logs ' + where, params);

  return {
    total: parseInt(totalResult.rows[0].total),
    byAction: actionBreakdown.rows.map((r) => ({ action: r.action, count: parseInt(r.count) })),
    byEntity: entityBreakdown.rows.map((r) => ({ entity: r.entity_type, count: parseInt(r.count) })),
    byUser: userBreakdown.rows.map((r) => ({ userId: r.user_id, count: parseInt(r.count) })),
  };
}
