/**
 * 📋 Audit Log API Routes
 * Auto-generated by Backend Factory
 */

import { queryAuditLogs, getEntityHistory, getUserActivity, getComplianceSummary } from '../audit/auditService.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';

export function registerAuditRoutes(app) {

  // Query audit logs
  app.get('/api/v1/audit', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const { entityType, entityId, userId, action, from, to, limit, offset } = req.query;
      const result = await queryAuditLogs({
        entityType, entityId, userId, action, tenantId: req.context.tenant_id, from, to,
        limit: parseInt(limit) || 50,
        offset: parseInt(offset) || 0,
      });
      res.json(result);
    } catch (err) {
      res.status(500).json({ error: err.message });
    }
  });

  // Get entity change history
  // Get user activity log
  app.get('/api/v1/audit/user/:userId', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const { limit, days } = req.query;
      const activity = await getUserActivity(req.context.tenant_id, req.params.userId, {
        limit: parseInt(limit) || 50,
        days: parseInt(days) || 30,
      });
      res.json({ data: activity, count: activity.length });
    } catch (err) {
      res.status(500).json({ error: err.message });
    }
  });

  app.get('/api/v1/audit/:entityType/:entityId', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const history = await getEntityHistory(req.context.tenant_id, req.params.entityType, req.params.entityId);
      res.json({ data: history, count: history.length });
    } catch (err) {
      res.status(500).json({ error: err.message });
    }
  });

  // Compliance summary report
  app.get('/api/v1/audit/compliance', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const { from, to } = req.query;
      const report = await getComplianceSummary({ tenantId: req.context.tenant_id, from, to });
      res.json(report);
    } catch (err) {
      res.status(500).json({ error: err.message });
    }
  });

}
