/**
 * 🛡️ Attachment Validation
 * Auto-generated by Forgx
 * Validates all input before it reaches the database.
 */

import { ValidationError } from '../errors/AppError.js';

const KNOWN_FIELDS = new Set(['task_id', 'file_name', 'file_key', 'file_size', 'content_type', 'entity_type', 'entity_id', 'metadata']);
const IMMUTABLE    = new Set(['id', 'tenant_id', 'created_at', 'created_by']);
const SERVER_FIELDS = new Set(['id', 'tenant_id', 'owner_id', 'created_at', 'updated_at', 'deleted_at', 'user_id', 'author_id', 'uploaded_by', 'submitted_by', 'reported_by', 'posted_by', 'sender_id', 'created_by']);

/**
 * Validate attachment creation — all required fields enforced
 * @param {object} data — request body
 * @throws {ValidationError} if data is invalid
 */
export function validateCreateAttachment(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  const errors = {};

  // Reject unknown fields (server-managed fields are ignored, not rejected)
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.task_id === undefined || data.task_id === null || data.task_id === '') {
    errors.task_id = 'task_id is required';
  } else {
    if (typeof data.task_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.task_id)) {
      errors.task_id = 'task_id must be a valid UUID';
    }
  }

  if (data.file_name !== undefined && data.file_name !== null) {
    if (typeof data.file_name !== 'string') {
      errors.file_name = 'file_name must be a string';
    }
    else if (data.file_name.length > 500) {
      errors.file_name = 'file_name must be 500 characters or less';
    }
  }

  if (data.file_key !== undefined && data.file_key !== null) {
    if (typeof data.file_key !== 'string') {
      errors.file_key = 'file_key must be a string';
    }
    else if (data.file_key.length > 500) {
      errors.file_key = 'file_key must be 500 characters or less';
    }
  }

  if (data.file_size !== undefined && data.file_size !== null) {
    if (typeof data.file_size !== 'number' || isNaN(data.file_size)) {
      errors.file_size = 'file_size must be a number';
    }
    else if (!Number.isInteger(data.file_size)) {
      errors.file_size = 'file_size must be a whole number';
    }
  }

  if (data.content_type !== undefined && data.content_type !== null) {
    if (typeof data.content_type !== 'string') {
      errors.content_type = 'content_type must be a string';
    }
  }

  if (data.entity_type !== undefined && data.entity_type !== null) {
    if (typeof data.entity_type !== 'string') {
      errors.entity_type = 'entity_type must be a string';
    }
  }

  if (data.entity_id !== undefined && data.entity_id !== null) {
    if (typeof data.entity_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.entity_id)) {
      errors.entity_id = 'entity_id must be a valid UUID';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid attachment data', errors);
  }
}

/**
 * Validate attachment update — partial data allowed, immutable fields blocked
 * @param {object} data — request body (partial)
 * @throws {ValidationError} if data is invalid
 */
export function validateUpdateAttachment(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  if (Object.keys(data).length === 0) {
    throw new ValidationError('No fields to update', { body: 'At least one field must be provided' });
  }

  const errors = {};

  // Immutable field protection
  for (const field of IMMUTABLE) {
    if (data[field] !== undefined) {
      errors[field] = field + ' cannot be modified after creation';
    }
  }

  // Reject unknown fields
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !IMMUTABLE.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.task_id !== undefined && data.task_id !== null) {
    if (typeof data.task_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.task_id)) {
      errors.task_id = 'task_id must be a valid UUID';
    }
  }

  if (data.file_name !== undefined && data.file_name !== null) {
    if (typeof data.file_name !== 'string') {
      errors.file_name = 'file_name must be a string';
    }
    else if (data.file_name.length > 500) {
      errors.file_name = 'file_name must be 500 characters or less';
    }
  }

  if (data.file_key !== undefined && data.file_key !== null) {
    if (typeof data.file_key !== 'string') {
      errors.file_key = 'file_key must be a string';
    }
    else if (data.file_key.length > 500) {
      errors.file_key = 'file_key must be 500 characters or less';
    }
  }

  if (data.file_size !== undefined && data.file_size !== null) {
    if (typeof data.file_size !== 'number' || isNaN(data.file_size)) {
      errors.file_size = 'file_size must be a number';
    }
    else if (!Number.isInteger(data.file_size)) {
      errors.file_size = 'file_size must be a whole number';
    }
  }

  if (data.content_type !== undefined && data.content_type !== null) {
    if (typeof data.content_type !== 'string') {
      errors.content_type = 'content_type must be a string';
    }
  }

  if (data.entity_type !== undefined && data.entity_type !== null) {
    if (typeof data.entity_type !== 'string') {
      errors.entity_type = 'entity_type must be a string';
    }
  }

  if (data.entity_id !== undefined && data.entity_id !== null) {
    if (typeof data.entity_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.entity_id)) {
      errors.entity_id = 'entity_id must be a valid UUID';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid attachment update data', errors);
  }
}
