/**
 * 🛡️ Comment Validation
 * Auto-generated by Forgx
 * Validates all input before it reaches the database.
 */

import { ValidationError } from '../errors/AppError.js';

const KNOWN_FIELDS = new Set(['task_id', 'body', 'parent_id', 'is_internal', 'edited_at', 'metadata']);
const IMMUTABLE    = new Set(['id', 'tenant_id', 'created_at', 'created_by']);
const SERVER_FIELDS = new Set(['id', 'tenant_id', 'owner_id', 'created_at', 'updated_at', 'deleted_at', 'user_id', 'author_id', 'uploaded_by', 'submitted_by', 'reported_by', 'posted_by', 'sender_id', 'created_by']);

/**
 * Validate comment creation — all required fields enforced
 * @param {object} data — request body
 * @throws {ValidationError} if data is invalid
 */
export function validateCreateComment(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  const errors = {};

  // Reject unknown fields (server-managed fields are ignored, not rejected)
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.task_id === undefined || data.task_id === null || data.task_id === '') {
    errors.task_id = 'task_id is required';
  } else {
    if (typeof data.task_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.task_id)) {
      errors.task_id = 'task_id must be a valid UUID';
    }
  }

  if (data.body === undefined || data.body === null || data.body === '') {
    errors.body = 'body is required';
  } else {
    if (typeof data.body !== 'string') {
      errors.body = 'body must be a string';
    }
  }

  if (data.parent_id !== undefined && data.parent_id !== null) {
    if (typeof data.parent_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.parent_id)) {
      errors.parent_id = 'parent_id must be a valid UUID';
    }
  }

  if (data.is_internal !== undefined && data.is_internal !== null) {
    if (typeof data.is_internal !== 'boolean') {
      errors.is_internal = 'is_internal must be true or false';
    }
  }

  if (data.edited_at !== undefined && data.edited_at !== null) {
    if (isNaN(Date.parse(data.edited_at))) {
      errors.edited_at = 'edited_at must be a valid date';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid comment data', errors);
  }
}

/**
 * Validate comment update — partial data allowed, immutable fields blocked
 * @param {object} data — request body (partial)
 * @throws {ValidationError} if data is invalid
 */
export function validateUpdateComment(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  if (Object.keys(data).length === 0) {
    throw new ValidationError('No fields to update', { body: 'At least one field must be provided' });
  }

  const errors = {};

  // Immutable field protection
  for (const field of IMMUTABLE) {
    if (data[field] !== undefined) {
      errors[field] = field + ' cannot be modified after creation';
    }
  }

  // Reject unknown fields
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !IMMUTABLE.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.task_id !== undefined && data.task_id !== null) {
    if (typeof data.task_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.task_id)) {
      errors.task_id = 'task_id must be a valid UUID';
    }
  }

  if (data.body !== undefined && data.body !== null) {
    if (typeof data.body !== 'string') {
      errors.body = 'body must be a string';
    }
  }

  if (data.parent_id !== undefined && data.parent_id !== null) {
    if (typeof data.parent_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.parent_id)) {
      errors.parent_id = 'parent_id must be a valid UUID';
    }
  }

  if (data.is_internal !== undefined && data.is_internal !== null) {
    if (typeof data.is_internal !== 'boolean') {
      errors.is_internal = 'is_internal must be true or false';
    }
  }

  if (data.edited_at !== undefined && data.edited_at !== null) {
    if (isNaN(Date.parse(data.edited_at))) {
      errors.edited_at = 'edited_at must be a valid date';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid comment update data', errors);
  }
}
