/**
 * 🛡️ Invite Validation
 * Auto-generated by Forgx
 * Validates all input before it reaches the database.
 */

import { ValidationError } from '../errors/AppError.js';

const KNOWN_FIELDS = new Set(['email', 'role', 'project_id', 'token', 'expires_at', 'invited_by', 'title', 'description', 'metadata']);
const IMMUTABLE    = new Set(['id', 'tenant_id', 'created_at', 'created_by']);
const SERVER_FIELDS = new Set(['id', 'tenant_id', 'owner_id', 'created_at', 'updated_at', 'deleted_at', 'user_id', 'author_id', 'uploaded_by', 'submitted_by', 'reported_by', 'posted_by', 'sender_id', 'created_by']);

/**
 * Validate invite creation — all required fields enforced
 * @param {object} data — request body
 * @throws {ValidationError} if data is invalid
 */
export function validateCreateInvite(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  const errors = {};

  // Reject unknown fields (server-managed fields are ignored, not rejected)
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.email === undefined || data.email === null || data.email === '') {
    errors.email = 'email is required';
  } else {
    if (typeof data.email !== 'string' || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
      errors.email = 'email must be a valid email address';
    }
  }

  if (data.role !== undefined && data.role !== null) {
    if (typeof data.role !== 'string') {
      errors.role = 'role must be a string';
    }
    else if (data.role.length > 500) {
      errors.role = 'role must be 500 characters or less';
    }
  }

  if (data.project_id === undefined || data.project_id === null || data.project_id === '') {
    errors.project_id = 'project_id is required';
  } else {
    if (typeof data.project_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.project_id)) {
      errors.project_id = 'project_id must be a valid UUID';
    }
  }

  if (data.token !== undefined && data.token !== null) {
    if (typeof data.token !== 'string') {
      errors.token = 'token must be a string';
    }
    else if (data.token.length > 500) {
      errors.token = 'token must be 500 characters or less';
    }
  }

  if (data.expires_at !== undefined && data.expires_at !== null) {
    if (isNaN(Date.parse(data.expires_at))) {
      errors.expires_at = 'expires_at must be a valid date';
    }
  }

  if (data.invited_by !== undefined && data.invited_by !== null) {
    if (typeof data.invited_by !== 'string') {
      errors.invited_by = 'invited_by must be a string';
    }
    else if (data.invited_by.length > 500) {
      errors.invited_by = 'invited_by must be 500 characters or less';
    }
  }

  if (data.title !== undefined && data.title !== null) {
    if (typeof data.title !== 'string') {
      errors.title = 'title must be a string';
    }
  }

  if (data.description !== undefined && data.description !== null) {
    if (typeof data.description !== 'string') {
      errors.description = 'description must be a string';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid invite data', errors);
  }
}

/**
 * Validate invite update — partial data allowed, immutable fields blocked
 * @param {object} data — request body (partial)
 * @throws {ValidationError} if data is invalid
 */
export function validateUpdateInvite(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  if (Object.keys(data).length === 0) {
    throw new ValidationError('No fields to update', { body: 'At least one field must be provided' });
  }

  const errors = {};

  // Immutable field protection
  for (const field of IMMUTABLE) {
    if (data[field] !== undefined) {
      errors[field] = field + ' cannot be modified after creation';
    }
  }

  // Reject unknown fields
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !IMMUTABLE.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.email !== undefined && data.email !== null) {
    if (typeof data.email !== 'string' || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
      errors.email = 'email must be a valid email address';
    }
  }

  if (data.role !== undefined && data.role !== null) {
    if (typeof data.role !== 'string') {
      errors.role = 'role must be a string';
    }
    else if (data.role.length > 500) {
      errors.role = 'role must be 500 characters or less';
    }
  }

  if (data.project_id !== undefined && data.project_id !== null) {
    if (typeof data.project_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.project_id)) {
      errors.project_id = 'project_id must be a valid UUID';
    }
  }

  if (data.token !== undefined && data.token !== null) {
    if (typeof data.token !== 'string') {
      errors.token = 'token must be a string';
    }
    else if (data.token.length > 500) {
      errors.token = 'token must be 500 characters or less';
    }
  }

  if (data.expires_at !== undefined && data.expires_at !== null) {
    if (isNaN(Date.parse(data.expires_at))) {
      errors.expires_at = 'expires_at must be a valid date';
    }
  }

  if (data.invited_by !== undefined && data.invited_by !== null) {
    if (typeof data.invited_by !== 'string') {
      errors.invited_by = 'invited_by must be a string';
    }
    else if (data.invited_by.length > 500) {
      errors.invited_by = 'invited_by must be 500 characters or less';
    }
  }

  if (data.title !== undefined && data.title !== null) {
    if (typeof data.title !== 'string') {
      errors.title = 'title must be a string';
    }
  }

  if (data.description !== undefined && data.description !== null) {
    if (typeof data.description !== 'string') {
      errors.description = 'description must be a string';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid invite update data', errors);
  }
}
