/**
 * 🛡️ Project Validation
 * Auto-generated by Forgx
 * Validates all input before it reaches the database.
 */

import { ValidationError } from '../errors/AppError.js';

const KNOWN_FIELDS = new Set(['name', 'description', 'deadline', 'color', 'start_date', 'end_date', 'budget', 'progress', 'is_archived', 'metadata']);
const IMMUTABLE    = new Set(['id', 'tenant_id', 'created_at', 'created_by']);
const SERVER_FIELDS = new Set(['id', 'tenant_id', 'owner_id', 'created_at', 'updated_at', 'deleted_at', 'user_id', 'author_id', 'uploaded_by', 'submitted_by', 'reported_by', 'posted_by', 'sender_id', 'created_by']);

/**
 * Validate project creation — all required fields enforced
 * @param {object} data — request body
 * @throws {ValidationError} if data is invalid
 */
export function validateCreateProject(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  const errors = {};

  // Reject unknown fields (server-managed fields are ignored, not rejected)
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.name === undefined || data.name === null || data.name === '') {
    errors.name = 'name is required';
  } else {
    if (typeof data.name !== 'string') {
      errors.name = 'name must be a string';
    }
    else if (data.name.length < 1) {
      errors.name = 'name must be at least 1 characters';
    }
    else if (data.name.length > 200) {
      errors.name = 'name must be 200 characters or less';
    }
  }

  if (data.description !== undefined && data.description !== null) {
    if (typeof data.description !== 'string') {
      errors.description = 'description must be a string';
    }
  }

  if (data.deadline !== undefined && data.deadline !== null) {
    if (typeof data.deadline !== 'string') {
      errors.deadline = 'deadline must be a string';
    }
    else if (data.deadline.length > 500) {
      errors.deadline = 'deadline must be 500 characters or less';
    }
  }

  if (data.color !== undefined && data.color !== null) {
    if (typeof data.color !== 'string') {
      errors.color = 'color must be a string';
    }
    else if (data.color.length > 500) {
      errors.color = 'color must be 500 characters or less';
    }
  }

  if (data.start_date !== undefined && data.start_date !== null) {
    if (typeof data.start_date !== 'string') {
      errors.start_date = 'start_date must be a string';
    }
  }

  if (data.end_date !== undefined && data.end_date !== null) {
    if (typeof data.end_date !== 'string') {
      errors.end_date = 'end_date must be a string';
    }
  }

  if (data.budget !== undefined && data.budget !== null) {
    if (typeof data.budget !== 'string') {
      errors.budget = 'budget must be a string';
    }
  }

  if (data.progress !== undefined && data.progress !== null) {
    if (typeof data.progress !== 'string') {
      errors.progress = 'progress must be a string';
    }
  }

  if (data.is_archived !== undefined && data.is_archived !== null) {
    if (typeof data.is_archived !== 'boolean') {
      errors.is_archived = 'is_archived must be true or false';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid project data', errors);
  }
}

/**
 * Validate project update — partial data allowed, immutable fields blocked
 * @param {object} data — request body (partial)
 * @throws {ValidationError} if data is invalid
 */
export function validateUpdateProject(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  if (Object.keys(data).length === 0) {
    throw new ValidationError('No fields to update', { body: 'At least one field must be provided' });
  }

  const errors = {};

  // Immutable field protection
  for (const field of IMMUTABLE) {
    if (data[field] !== undefined) {
      errors[field] = field + ' cannot be modified after creation';
    }
  }

  // Reject unknown fields
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !IMMUTABLE.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.name !== undefined && data.name !== null) {
    if (typeof data.name !== 'string') {
      errors.name = 'name must be a string';
    }
    else if (data.name.length < 1) {
      errors.name = 'name must be at least 1 characters';
    }
    else if (data.name.length > 200) {
      errors.name = 'name must be 200 characters or less';
    }
  }

  if (data.description !== undefined && data.description !== null) {
    if (typeof data.description !== 'string') {
      errors.description = 'description must be a string';
    }
  }

  if (data.deadline !== undefined && data.deadline !== null) {
    if (typeof data.deadline !== 'string') {
      errors.deadline = 'deadline must be a string';
    }
    else if (data.deadline.length > 500) {
      errors.deadline = 'deadline must be 500 characters or less';
    }
  }

  if (data.color !== undefined && data.color !== null) {
    if (typeof data.color !== 'string') {
      errors.color = 'color must be a string';
    }
    else if (data.color.length > 500) {
      errors.color = 'color must be 500 characters or less';
    }
  }

  if (data.start_date !== undefined && data.start_date !== null) {
    if (typeof data.start_date !== 'string') {
      errors.start_date = 'start_date must be a string';
    }
  }

  if (data.end_date !== undefined && data.end_date !== null) {
    if (typeof data.end_date !== 'string') {
      errors.end_date = 'end_date must be a string';
    }
  }

  if (data.budget !== undefined && data.budget !== null) {
    if (typeof data.budget !== 'string') {
      errors.budget = 'budget must be a string';
    }
  }

  if (data.progress !== undefined && data.progress !== null) {
    if (typeof data.progress !== 'string') {
      errors.progress = 'progress must be a string';
    }
  }

  if (data.is_archived !== undefined && data.is_archived !== null) {
    if (typeof data.is_archived !== 'boolean') {
      errors.is_archived = 'is_archived must be true or false';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid project update data', errors);
  }
}
