/**
 * 🛡️ Subscription Validation
 * Auto-generated by Forgx
 * Validates all input before it reaches the database.
 */

import { ValidationError } from '../errors/AppError.js';

const KNOWN_FIELDS = new Set(['plan', 'seats', 'price_amount', 'currency', 'current_period_end', 'workspace_id', 'stripe_subscription_id', 'stripe_customer_id', 'stripe_price_id', 'status', 'current_period_start', 'cancel_at_period_end', 'canceled_at', 'trial_start', 'trial_end', 'invoice_number', 'metadata']);
const IMMUTABLE    = new Set(['id', 'tenant_id', 'created_at', 'created_by']);
const SERVER_FIELDS = new Set(['id', 'tenant_id', 'owner_id', 'created_at', 'updated_at', 'deleted_at', 'user_id', 'author_id', 'uploaded_by', 'submitted_by', 'reported_by', 'posted_by', 'sender_id', 'created_by']);

/**
 * Validate subscription creation — all required fields enforced
 * @param {object} data — request body
 * @throws {ValidationError} if data is invalid
 */
export function validateCreateSubscription(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  const errors = {};

  // Reject unknown fields (server-managed fields are ignored, not rejected)
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.plan !== undefined && data.plan !== null) {
    if (typeof data.plan !== 'string') {
      errors.plan = 'plan must be a string';
    }
    else if (data.plan.length > 500) {
      errors.plan = 'plan must be 500 characters or less';
    }
  }

  if (data.seats !== undefined && data.seats !== null) {
    if (typeof data.seats !== 'number' || isNaN(data.seats)) {
      errors.seats = 'seats must be a number';
    }
    else if (!Number.isInteger(data.seats)) {
      errors.seats = 'seats must be a whole number';
    }
    else if (data.seats < 0) {
      errors.seats = 'seats cannot be negative';
    }
  }

  if (data.price_amount !== undefined && data.price_amount !== null) {
    if (typeof data.price_amount !== 'number' || isNaN(data.price_amount)) {
      errors.price_amount = 'price_amount must be a number';
    }
    else if (data.price_amount < 0) {
      errors.price_amount = 'price_amount cannot be negative';
    }
    else if (data.price_amount > 1e12) {
      errors.price_amount = 'price_amount exceeds the maximum allowed value';
    }
  }

  if (data.currency !== undefined && data.currency !== null) {
    if (typeof data.currency !== 'string') {
      errors.currency = 'currency must be a string';
    }
    else if (data.currency.length > 500) {
      errors.currency = 'currency must be 500 characters or less';
    }
  }

  if (data.current_period_end !== undefined && data.current_period_end !== null) {
    if (typeof data.current_period_end !== 'string') {
      errors.current_period_end = 'current_period_end must be a string';
    }
    else if (data.current_period_end.length > 500) {
      errors.current_period_end = 'current_period_end must be 500 characters or less';
    }
  }

  if (data.workspace_id !== undefined && data.workspace_id !== null) {
    if (typeof data.workspace_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.workspace_id)) {
      errors.workspace_id = 'workspace_id must be a valid UUID';
    }
  }

  if (data.stripe_subscription_id !== undefined && data.stripe_subscription_id !== null) {
    if (typeof data.stripe_subscription_id !== 'string') {
      errors.stripe_subscription_id = 'stripe_subscription_id must be a string';
    }
  }

  if (data.stripe_customer_id !== undefined && data.stripe_customer_id !== null) {
    if (typeof data.stripe_customer_id !== 'string') {
      errors.stripe_customer_id = 'stripe_customer_id must be a string';
    }
  }

  if (data.stripe_price_id !== undefined && data.stripe_price_id !== null) {
    if (typeof data.stripe_price_id !== 'string') {
      errors.stripe_price_id = 'stripe_price_id must be a string';
    }
  }

  if (data.status !== undefined && data.status !== null) {
    if (typeof data.status !== 'string') {
      errors.status = 'status must be a string';
    }
    if (!errors.status && !['trialing', 'active', 'past_due', 'cancelled'].includes(data.status)) {
      errors.status = 'status must be one of: trialing, active, past_due, cancelled';
    }
  }

  if (data.current_period_start !== undefined && data.current_period_start !== null) {
    if (typeof data.current_period_start !== 'string') {
      errors.current_period_start = 'current_period_start must be a string';
    }
  }

  if (data.cancel_at_period_end !== undefined && data.cancel_at_period_end !== null) {
    if (typeof data.cancel_at_period_end !== 'string') {
      errors.cancel_at_period_end = 'cancel_at_period_end must be a string';
    }
  }

  if (data.canceled_at !== undefined && data.canceled_at !== null) {
    if (isNaN(Date.parse(data.canceled_at))) {
      errors.canceled_at = 'canceled_at must be a valid date';
    }
  }

  if (data.trial_start !== undefined && data.trial_start !== null) {
    if (typeof data.trial_start !== 'string') {
      errors.trial_start = 'trial_start must be a string';
    }
  }

  if (data.trial_end !== undefined && data.trial_end !== null) {
    if (typeof data.trial_end !== 'string') {
      errors.trial_end = 'trial_end must be a string';
    }
  }

  if (data.invoice_number !== undefined && data.invoice_number !== null) {
    if (typeof data.invoice_number !== 'string') {
      errors.invoice_number = 'invoice_number must be a string';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid subscription data', errors);
  }
}

/**
 * Validate subscription update — partial data allowed, immutable fields blocked
 * @param {object} data — request body (partial)
 * @throws {ValidationError} if data is invalid
 */
export function validateUpdateSubscription(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  if (Object.keys(data).length === 0) {
    throw new ValidationError('No fields to update', { body: 'At least one field must be provided' });
  }

  const errors = {};

  // Immutable field protection
  for (const field of IMMUTABLE) {
    if (data[field] !== undefined) {
      errors[field] = field + ' cannot be modified after creation';
    }
  }

  // Reject unknown fields
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !IMMUTABLE.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.plan !== undefined && data.plan !== null) {
    if (typeof data.plan !== 'string') {
      errors.plan = 'plan must be a string';
    }
    else if (data.plan.length > 500) {
      errors.plan = 'plan must be 500 characters or less';
    }
  }

  if (data.seats !== undefined && data.seats !== null) {
    if (typeof data.seats !== 'number' || isNaN(data.seats)) {
      errors.seats = 'seats must be a number';
    }
    else if (!Number.isInteger(data.seats)) {
      errors.seats = 'seats must be a whole number';
    }
    else if (data.seats < 0) {
      errors.seats = 'seats cannot be negative';
    }
  }

  if (data.price_amount !== undefined && data.price_amount !== null) {
    if (typeof data.price_amount !== 'number' || isNaN(data.price_amount)) {
      errors.price_amount = 'price_amount must be a number';
    }
    else if (data.price_amount < 0) {
      errors.price_amount = 'price_amount cannot be negative';
    }
    else if (data.price_amount > 1e12) {
      errors.price_amount = 'price_amount exceeds the maximum allowed value';
    }
  }

  if (data.currency !== undefined && data.currency !== null) {
    if (typeof data.currency !== 'string') {
      errors.currency = 'currency must be a string';
    }
    else if (data.currency.length > 500) {
      errors.currency = 'currency must be 500 characters or less';
    }
  }

  if (data.current_period_end !== undefined && data.current_period_end !== null) {
    if (typeof data.current_period_end !== 'string') {
      errors.current_period_end = 'current_period_end must be a string';
    }
    else if (data.current_period_end.length > 500) {
      errors.current_period_end = 'current_period_end must be 500 characters or less';
    }
  }

  if (data.workspace_id !== undefined && data.workspace_id !== null) {
    if (typeof data.workspace_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.workspace_id)) {
      errors.workspace_id = 'workspace_id must be a valid UUID';
    }
  }

  if (data.stripe_subscription_id !== undefined && data.stripe_subscription_id !== null) {
    if (typeof data.stripe_subscription_id !== 'string') {
      errors.stripe_subscription_id = 'stripe_subscription_id must be a string';
    }
  }

  if (data.stripe_customer_id !== undefined && data.stripe_customer_id !== null) {
    if (typeof data.stripe_customer_id !== 'string') {
      errors.stripe_customer_id = 'stripe_customer_id must be a string';
    }
  }

  if (data.stripe_price_id !== undefined && data.stripe_price_id !== null) {
    if (typeof data.stripe_price_id !== 'string') {
      errors.stripe_price_id = 'stripe_price_id must be a string';
    }
  }

  if (data.current_period_start !== undefined && data.current_period_start !== null) {
    if (typeof data.current_period_start !== 'string') {
      errors.current_period_start = 'current_period_start must be a string';
    }
  }

  if (data.cancel_at_period_end !== undefined && data.cancel_at_period_end !== null) {
    if (typeof data.cancel_at_period_end !== 'string') {
      errors.cancel_at_period_end = 'cancel_at_period_end must be a string';
    }
  }

  if (data.canceled_at !== undefined && data.canceled_at !== null) {
    if (isNaN(Date.parse(data.canceled_at))) {
      errors.canceled_at = 'canceled_at must be a valid date';
    }
  }

  if (data.trial_start !== undefined && data.trial_start !== null) {
    if (typeof data.trial_start !== 'string') {
      errors.trial_start = 'trial_start must be a string';
    }
  }

  if (data.trial_end !== undefined && data.trial_end !== null) {
    if (typeof data.trial_end !== 'string') {
      errors.trial_end = 'trial_end must be a string';
    }
  }

  if (data.invoice_number !== undefined && data.invoice_number !== null) {
    if (typeof data.invoice_number !== 'string') {
      errors.invoice_number = 'invoice_number must be a string';
    }
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid subscription update data', errors);
  }
}
