/**
 * 🛡️ Task Validation
 * Auto-generated by Forgx
 * Validates all input before it reaches the database.
 */

import { ValidationError } from '../errors/AppError.js';

const KNOWN_FIELDS = new Set(['title', 'description', 'project_id', 'assignee_id', 'priority', 'due_date', 'estimate_hours', 'assigned_to', 'estimated_hours', 'completed_at', 'tags', 'metadata']);
const IMMUTABLE    = new Set(['id', 'tenant_id', 'created_at', 'created_by']);
const SERVER_FIELDS = new Set(['id', 'tenant_id', 'owner_id', 'created_at', 'updated_at', 'deleted_at', 'user_id', 'author_id', 'uploaded_by', 'submitted_by', 'reported_by', 'posted_by', 'sender_id', 'created_by']);

/**
 * Validate task creation — all required fields enforced
 * @param {object} data — request body
 * @throws {ValidationError} if data is invalid
 */
export function validateCreateTask(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  const errors = {};

  // Reject unknown fields (server-managed fields are ignored, not rejected)
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.title === undefined || data.title === null || data.title === '') {
    errors.title = 'title is required';
  } else {
    if (typeof data.title !== 'string') {
      errors.title = 'title must be a string';
    }
    else if (data.title.length < 1) {
      errors.title = 'title must be at least 1 characters';
    }
    else if (data.title.length > 200) {
      errors.title = 'title must be 200 characters or less';
    }
  }

  if (data.description !== undefined && data.description !== null) {
    if (typeof data.description !== 'string') {
      errors.description = 'description must be a string';
    }
  }

  if (data.project_id === undefined || data.project_id === null || data.project_id === '') {
    errors.project_id = 'project_id is required';
  } else {
    if (typeof data.project_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.project_id)) {
      errors.project_id = 'project_id must be a valid UUID';
    }
  }

  if (data.assignee_id === undefined || data.assignee_id === null || data.assignee_id === '') {
    errors.assignee_id = 'assignee_id is required';
  } else {
    if (typeof data.assignee_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.assignee_id)) {
      errors.assignee_id = 'assignee_id must be a valid UUID';
    }
  }

  if (data.priority !== undefined && data.priority !== null) {
    if (typeof data.priority !== 'string') {
      errors.priority = 'priority must be a string';
    }
    else if (data.priority.length > 500) {
      errors.priority = 'priority must be 500 characters or less';
    }
  }

  if (data.due_date !== undefined && data.due_date !== null) {
    if (isNaN(Date.parse(data.due_date))) {
      errors.due_date = 'due_date must be a valid date';
    }
  }

  if (data.estimate_hours !== undefined && data.estimate_hours !== null) {
    if (typeof data.estimate_hours !== 'number' || isNaN(data.estimate_hours)) {
      errors.estimate_hours = 'estimate_hours must be a number';
    }
    else if (!Number.isInteger(data.estimate_hours)) {
      errors.estimate_hours = 'estimate_hours must be a whole number';
    }
    else if (data.estimate_hours < 0) {
      errors.estimate_hours = 'estimate_hours cannot be negative';
    }
  }

  if (data.assigned_to !== undefined && data.assigned_to !== null) {
    if (typeof data.assigned_to !== 'string') {
      errors.assigned_to = 'assigned_to must be a string';
    }
  }

  if (data.estimated_hours !== undefined && data.estimated_hours !== null) {
    if (typeof data.estimated_hours !== 'number' || isNaN(data.estimated_hours)) {
      errors.estimated_hours = 'estimated_hours must be a number';
    }
    else if (!Number.isInteger(data.estimated_hours)) {
      errors.estimated_hours = 'estimated_hours must be a whole number';
    }
    else if (data.estimated_hours < 0) {
      errors.estimated_hours = 'estimated_hours cannot be negative';
    }
  }

  if (data.completed_at !== undefined && data.completed_at !== null) {
    if (isNaN(Date.parse(data.completed_at))) {
      errors.completed_at = 'completed_at must be a valid date';
    }
  }

  if (data.tags !== undefined && data.tags !== null) {
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid task data', errors);
  }
}

/**
 * Validate task update — partial data allowed, immutable fields blocked
 * @param {object} data — request body (partial)
 * @throws {ValidationError} if data is invalid
 */
export function validateUpdateTask(data) {
  if (!data || typeof data !== 'object') {
    throw new ValidationError('Request body must be a JSON object', { body: 'missing or invalid' });
  }

  if (Object.keys(data).length === 0) {
    throw new ValidationError('No fields to update', { body: 'At least one field must be provided' });
  }

  const errors = {};

  // Immutable field protection
  for (const field of IMMUTABLE) {
    if (data[field] !== undefined) {
      errors[field] = field + ' cannot be modified after creation';
    }
  }

  // Reject unknown fields
  for (const key of Object.keys(data)) {
    if (!KNOWN_FIELDS.has(key) && !IMMUTABLE.has(key) && !SERVER_FIELDS.has(key)) {
      errors[key] = key + ' is not a recognised field';
    }
  }

  if (data.title !== undefined && data.title !== null) {
    if (typeof data.title !== 'string') {
      errors.title = 'title must be a string';
    }
    else if (data.title.length < 1) {
      errors.title = 'title must be at least 1 characters';
    }
    else if (data.title.length > 200) {
      errors.title = 'title must be 200 characters or less';
    }
  }

  if (data.description !== undefined && data.description !== null) {
    if (typeof data.description !== 'string') {
      errors.description = 'description must be a string';
    }
  }

  if (data.project_id !== undefined && data.project_id !== null) {
    if (typeof data.project_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.project_id)) {
      errors.project_id = 'project_id must be a valid UUID';
    }
  }

  if (data.assignee_id !== undefined && data.assignee_id !== null) {
    if (typeof data.assignee_id !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.assignee_id)) {
      errors.assignee_id = 'assignee_id must be a valid UUID';
    }
  }

  if (data.priority !== undefined && data.priority !== null) {
    if (typeof data.priority !== 'string') {
      errors.priority = 'priority must be a string';
    }
    else if (data.priority.length > 500) {
      errors.priority = 'priority must be 500 characters or less';
    }
  }

  if (data.due_date !== undefined && data.due_date !== null) {
    if (isNaN(Date.parse(data.due_date))) {
      errors.due_date = 'due_date must be a valid date';
    }
  }

  if (data.estimate_hours !== undefined && data.estimate_hours !== null) {
    if (typeof data.estimate_hours !== 'number' || isNaN(data.estimate_hours)) {
      errors.estimate_hours = 'estimate_hours must be a number';
    }
    else if (!Number.isInteger(data.estimate_hours)) {
      errors.estimate_hours = 'estimate_hours must be a whole number';
    }
    else if (data.estimate_hours < 0) {
      errors.estimate_hours = 'estimate_hours cannot be negative';
    }
  }

  if (data.assigned_to !== undefined && data.assigned_to !== null) {
    if (typeof data.assigned_to !== 'string') {
      errors.assigned_to = 'assigned_to must be a string';
    }
  }

  if (data.estimated_hours !== undefined && data.estimated_hours !== null) {
    if (typeof data.estimated_hours !== 'number' || isNaN(data.estimated_hours)) {
      errors.estimated_hours = 'estimated_hours must be a number';
    }
    else if (!Number.isInteger(data.estimated_hours)) {
      errors.estimated_hours = 'estimated_hours must be a whole number';
    }
    else if (data.estimated_hours < 0) {
      errors.estimated_hours = 'estimated_hours cannot be negative';
    }
  }

  if (data.completed_at !== undefined && data.completed_at !== null) {
    if (isNaN(Date.parse(data.completed_at))) {
      errors.completed_at = 'completed_at must be a valid date';
    }
  }

  if (data.tags !== undefined && data.tags !== null) {
  }

  if (Object.keys(errors).length > 0) {
    throw new ValidationError('Invalid task update data', errors);
  }
}
