-- ═══════════════════════════════════════════════════
-- 🔐 MIGRATION 001 — USERS & AUTH
-- Auto-generated by Backend Factory
-- Project: teamflow
-- ═══════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "users" (
  "id"            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id"     UUID NOT NULL,
  "email"         VARCHAR(255) NOT NULL,
  "password_hash" TEXT NOT NULL,
  "role"          VARCHAR(50) NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'guest', 'member', 'owner', 'user')),
  "first_name"    VARCHAR(100),
  "last_name"     VARCHAR(100),
  "is_active"     BOOLEAN NOT NULL DEFAULT true,
  "last_login_at" TIMESTAMP,
  "created_at"    TIMESTAMP DEFAULT NOW(),
  "updated_at"    TIMESTAMP DEFAULT NOW(),
  "deleted_at"    TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_global ON users (LOWER(email)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "tenant_id"   UUID NOT NULL,
  "token_hash"  TEXT NOT NULL UNIQUE,
  "expires_at"  TIMESTAMP NOT NULL,
  "revoked"     BOOLEAN NOT NULL DEFAULT false,
  "created_at"  TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_tenant ON users (tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_tenant_email ON users (tenant_id, email);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens (token_hash);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "policy_users_select_member" ON "users";
CREATE POLICY "policy_users_select_member" ON "users"
  FOR SELECT USING (
    tenant_id = current_setting('app.tenant_id', true)::uuid
  );

DROP POLICY IF EXISTS "policy_users_write_admin" ON "users";
CREATE POLICY "policy_users_write_admin" ON "users"
  FOR ALL USING (
    current_setting('app.role', true) IN ('admin', 'owner')
    AND tenant_id = current_setting('app.tenant_id', true)::uuid
  );

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger AS $fn$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users FOR EACH ROW
EXECUTE FUNCTION update_updated_at();

-- Brute force protection
CREATE TABLE IF NOT EXISTS login_attempts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address  VARCHAR(45) NOT NULL,
  email       VARCHAR(255) NOT NULL,
  success     BOOLEAN DEFAULT false,
  created_at  TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_email ON login_attempts (ip_address, email, created_at DESC);

-- PIN login support (rural shared-tablet quick login)
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_hash        TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_enabled     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_set_at      TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_device_hash TEXT;

-- Auth audit log — append-only, regulatory compliance
CREATE TABLE IF NOT EXISTS auth_audit_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID,
  user_id         UUID,
  email           VARCHAR(255),
  event_type      VARCHAR(50) NOT NULL,
  -- event_type values:
  -- login_success | login_failed | logout | pin_login_success
  -- pin_login_failed | pin_setup | pin_changed | token_refreshed
  -- password_changed | account_locked
  ip_address      VARCHAR(45),
  user_agent      TEXT,
  device_fingerprint VARCHAR(64),
  -- device_fingerprint = SHA256(user_agent + ip_subnet + accept_language)
  -- allows grouping events by device without storing PII
  session_id      UUID,
  failure_reason  VARCHAR(100),
  metadata        JSONB DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for auth audit queries
CREATE INDEX IF NOT EXISTS idx_auth_audit_tenant_user   ON auth_audit_log (tenant_id, user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_audit_email         ON auth_audit_log (email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_audit_event_type    ON auth_audit_log (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_audit_ip            ON auth_audit_log (ip_address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_audit_created       ON auth_audit_log (created_at DESC);

-- Idempotency keys — prevents double charges and duplicate operations
CREATE TABLE IF NOT EXISTS idempotency_keys (
  tenant_id    UUID NOT NULL,
  key          VARCHAR(255) NOT NULL,
  status_code  INTEGER NOT NULL DEFAULT 200,
  response_body TEXT NOT NULL,
  created_at   TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (tenant_id, key)
);

CREATE INDEX IF NOT EXISTS idx_idempotency_tenant ON idempotency_keys (tenant_id, created_at DESC);

