-- ═══════════════════════════════════════════════════
-- 🗄️  MIGRATION 002 — CORE ENTITY TABLES
-- Auto-generated by Forgx
-- Entities: attachment, comment, invite, project, subscription, task
-- Generated: 2026-07-23
-- ═══════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── ATTACHMENTS ─────────────────────────
CREATE TABLE IF NOT EXISTS "attachments" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  "owner_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "task_id" UUID NOT NULL,
  "file_name" TEXT,
  "file_key" TEXT,
  "file_size" INTEGER,
  "content_type" TEXT,
  "uploaded_by" TEXT,
  "entity_type" TEXT,
  "entity_id" UUID
);

CREATE INDEX IF NOT EXISTS idx_attachments_tenant ON "attachments" (tenant_id);
CREATE INDEX IF NOT EXISTS idx_attachments_owner  ON "attachments" (owner_id);
CREATE INDEX IF NOT EXISTS idx_attachments_status ON "attachments" (status);
CREATE INDEX IF NOT EXISTS idx_attachments_deleted ON "attachments" (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_attachments_tenant_status_created ON "attachments" (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attachments_tenant_created ON "attachments" (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attachments_tenant_owner ON "attachments" (tenant_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_attachments_owner_id ON "attachments" (tenant_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_attachments_task_id ON "attachments" (tenant_id, task_id);
CREATE INDEX IF NOT EXISTS idx_attachments_entity_id ON "attachments" (tenant_id, entity_id);

ALTER TABLE "attachments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attachments_tenant_isolation ON "attachments";
CREATE POLICY attachments_tenant_isolation ON "attachments"
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─── COMMENTS ─────────────────────────
CREATE TABLE IF NOT EXISTS "comments" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'flagged', 'removed')),
  "owner_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "task_id" UUID NOT NULL,
  "author_id" UUID NOT NULL,
  "body" TEXT NOT NULL,
  "parent_id" UUID,
  "is_internal" BOOLEAN DEFAULT FALSE,
  "edited_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_comments_tenant ON "comments" (tenant_id);
CREATE INDEX IF NOT EXISTS idx_comments_owner  ON "comments" (owner_id);
CREATE INDEX IF NOT EXISTS idx_comments_status ON "comments" (status);
CREATE INDEX IF NOT EXISTS idx_comments_deleted ON "comments" (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_comments_tenant_status_created ON "comments" (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_tenant_created ON "comments" (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_tenant_owner ON "comments" (tenant_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_comments_owner_id ON "comments" (tenant_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_comments_task_id ON "comments" (tenant_id, task_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON "comments" (tenant_id, author_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON "comments" (tenant_id, parent_id);

ALTER TABLE "comments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS comments_tenant_isolation ON "comments";
CREATE POLICY comments_tenant_isolation ON "comments"
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─── INVITES ─────────────────────────
CREATE TABLE IF NOT EXISTS "invites" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired', 'revoked')),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ,
  "email" TEXT NOT NULL,
  "role" TEXT,
  "project_id" UUID NOT NULL,
  "token" TEXT,
  "expires_at" TIMESTAMPTZ,
  "invited_by" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "metadata" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_invites_tenant ON "invites" (tenant_id);
CREATE INDEX IF NOT EXISTS idx_invites_status ON "invites" (status);
CREATE INDEX IF NOT EXISTS idx_invites_deleted ON "invites" (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invites_tenant_status_created ON "invites" (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invites_tenant_created ON "invites" (tenant_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_invites_email ON "invites" (tenant_id, email) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_invites_project_id ON "invites" (tenant_id, project_id);

ALTER TABLE "invites" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS invites_tenant_isolation ON "invites";
CREATE POLICY invites_tenant_isolation ON "invites"
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─── PROJECTS ─────────────────────────
CREATE TABLE IF NOT EXISTS "projects" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'archived')),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "deadline" TEXT,
  "color" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "budget" TEXT,
  "progress" TEXT,
  "is_archived" BOOLEAN DEFAULT FALSE,
  "metadata" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_projects_tenant ON "projects" (tenant_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON "projects" (status);
CREATE INDEX IF NOT EXISTS idx_projects_deleted ON "projects" (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_projects_tenant_status_created ON "projects" (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_projects_tenant_created ON "projects" (tenant_id, created_at DESC);

ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS projects_tenant_isolation ON "projects";
CREATE POLICY projects_tenant_isolation ON "projects"
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─── SUBSCRIPTIONS ─────────────────────────
CREATE TABLE IF NOT EXISTS "subscriptions" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ,
  "plan" TEXT,
  "seats" INTEGER,
  "price_amount" NUMERIC(12,2),
  "currency" TEXT NOT NULL DEFAULT 'usd',
  "current_period_end" TEXT,
  "workspace_id" UUID,
  "stripe_subscription_id" TEXT,
  "stripe_customer_id" TEXT,
  "stripe_price_id" TEXT,
  "status" VARCHAR(50) NOT NULL DEFAULT 'trialing' CHECK (status IN ('trialing', 'active', 'past_due', 'cancelled')),
  "current_period_start" TEXT,
  "cancel_at_period_end" TEXT,
  "canceled_at" TIMESTAMPTZ,
  "trial_start" TEXT,
  "trial_end" TEXT,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "invoice_number" TEXT
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant ON "subscriptions" (tenant_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON "subscriptions" (status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_deleted ON "subscriptions" (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant_status_created ON "subscriptions" (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant_created ON "subscriptions" (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_workspace_id ON "subscriptions" (tenant_id, workspace_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_subscription_id ON "subscriptions" (tenant_id, stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_customer_id ON "subscriptions" (tenant_id, stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_price_id ON "subscriptions" (tenant_id, stripe_price_id);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_subscriptions_stripe_subscription_id ON "subscriptions" (stripe_subscription_id) WHERE stripe_subscription_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uidx_subscriptions_stripe_customer_id ON "subscriptions" (stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uidx_subscriptions_stripe_price_id ON "subscriptions" (stripe_price_id) WHERE stripe_price_id IS NOT NULL;

ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS subscriptions_tenant_isolation ON "subscriptions";
CREATE POLICY subscriptions_tenant_isolation ON "subscriptions"
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─── TASKS ─────────────────────────
CREATE TABLE IF NOT EXISTS "tasks" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'in_review', 'done', 'blocked')),
  "owner_id" UUID NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMPTZ,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "project_id" UUID NOT NULL,
  "assignee_id" UUID NOT NULL,
  "priority" TEXT,
  "due_date" TIMESTAMPTZ,
  "estimate_hours" INTEGER,
  "assigned_to" TEXT,
  "estimated_hours" INTEGER,
  "completed_at" TIMESTAMPTZ,
  "tags" JSONB DEFAULT '{}',
  "metadata" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_tasks_tenant ON "tasks" (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tasks_owner  ON "tasks" (owner_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON "tasks" (status);
CREATE INDEX IF NOT EXISTS idx_tasks_deleted ON "tasks" (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_tenant_status_created ON "tasks" (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_tenant_created ON "tasks" (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_tenant_owner ON "tasks" (tenant_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_tasks_owner_id ON "tasks" (tenant_id, owner_id);
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON "tasks" (tenant_id, project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee_id ON "tasks" (tenant_id, assignee_id);

ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tasks_tenant_isolation ON "tasks";
CREATE POLICY tasks_tenant_isolation ON "tasks"
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─── FOREIGN KEYS ─────────────────────────

DO $$
BEGIN
  -- Only add FK if both the column and the referenced table exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_attachments_task_id' AND table_name = 'attachments'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'attachments' AND column_name = 'task_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'tasks'
  ) THEN
    ALTER TABLE "attachments"
    ADD CONSTRAINT "fk_attachments_task_id"
    FOREIGN KEY ("task_id") REFERENCES "tasks"("id");
  END IF;
EXCEPTION WHEN undefined_table OR undefined_column OR others THEN
  RAISE NOTICE 'Skipping FK fk_attachments_task_id: %', SQLERRM;
END
$$;

DO $$
BEGIN
  -- Only add FK if both the column and the referenced table exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_comments_task_id' AND table_name = 'comments'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'comments' AND column_name = 'task_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'tasks'
  ) THEN
    ALTER TABLE "comments"
    ADD CONSTRAINT "fk_comments_task_id"
    FOREIGN KEY ("task_id") REFERENCES "tasks"("id");
  END IF;
EXCEPTION WHEN undefined_table OR undefined_column OR others THEN
  RAISE NOTICE 'Skipping FK fk_comments_task_id: %', SQLERRM;
END
$$;

DO $$
BEGIN
  -- Only add FK if both the column and the referenced table exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_invites_project_id' AND table_name = 'invites'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'invites' AND column_name = 'project_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'projects'
  ) THEN
    ALTER TABLE "invites"
    ADD CONSTRAINT "fk_invites_project_id"
    FOREIGN KEY ("project_id") REFERENCES "projects"("id");
  END IF;
EXCEPTION WHEN undefined_table OR undefined_column OR others THEN
  RAISE NOTICE 'Skipping FK fk_invites_project_id: %', SQLERRM;
END
$$;

DO $$
BEGIN
  -- Only add FK if both the column and the referenced table exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_tasks_project_id' AND table_name = 'tasks'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'tasks' AND column_name = 'project_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'projects'
  ) THEN
    ALTER TABLE "tasks"
    ADD CONSTRAINT "fk_tasks_project_id"
    FOREIGN KEY ("project_id") REFERENCES "projects"("id");
  END IF;
EXCEPTION WHEN undefined_table OR undefined_column OR others THEN
  RAISE NOTICE 'Skipping FK fk_tasks_project_id: %', SQLERRM;
END
$$;

-- ─── AUTO-UPDATE TRIGGERS ──────────────────

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger AS $fn$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

-- ─── STATE TRANSITION TRIGGERS ────────────

-- State transition enforcement for subscription
CREATE OR REPLACE FUNCTION check_subscription_transition()
RETURNS trigger AS $fn$
BEGIN
  IF NOT (
    (OLD.status = 'trialing' AND NEW.status = 'active')
    OR (OLD.status = 'active' AND NEW.status = 'cancelled')
  ) THEN
    RAISE EXCEPTION 'Invalid status transition from % to %', OLD.status, NEW.status;
  END IF;
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_subscription_transition ON "subscriptions";
CREATE TRIGGER trg_subscription_transition
BEFORE UPDATE ON "subscriptions"
FOR EACH ROW
WHEN (OLD.status IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION check_subscription_transition();

-- ═══════════════════════════════════════════════════
-- Migration 002 complete — 6 tables
-- ═══════════════════════════════════════════════════
SELECT 1;
