-- ═══════════════════════════════════════════════════
-- ⚡ INDEX OPTIMIZATION
-- Auto-generated by Backend Factory
-- ═══════════════════════════════════════════════════
--
-- Entities: 6
-- Generated: 2026-07-23
--
-- Index types:
--   • Composite indexes for multi-column queries
--   • Partial indexes for status-filtered queries
--   • Expression indexes for case-insensitive search
--   • GIN indexes for JSONB columns
--   • Foreign key indexes for JOINs
-- ═══════════════════════════════════════════════════

-- ─── INVITE ─────────────────────────

-- Case-insensitive email lookup
CREATE INDEX IF NOT EXISTS idx_invites_email_lower ON invites (LOWER(email));

-- Case-insensitive name/title search
CREATE INDEX IF NOT EXISTS idx_invites_name_lower ON invites (LOWER(title));

-- GIN index for JSONB queries on metadata
CREATE INDEX IF NOT EXISTS idx_invites_metadata_gin ON invites USING GIN (metadata);

-- ─── PROJECT ─────────────────────────

-- Case-insensitive name/title search
CREATE INDEX IF NOT EXISTS idx_projects_name_lower ON projects (LOWER(name));

-- GIN index for JSONB queries on metadata
CREATE INDEX IF NOT EXISTS idx_projects_metadata_gin ON projects USING GIN (metadata);

-- ─── SUBSCRIPTION ─────────────────────────

-- Partial index — only live (non-soft-deleted) records (smaller, faster)
CREATE INDEX IF NOT EXISTS idx_subscriptions_active ON subscriptions (created_at DESC) WHERE deleted_at IS NULL;

-- GIN index for JSONB queries on metadata
CREATE INDEX IF NOT EXISTS idx_subscriptions_metadata_gin ON subscriptions USING GIN (metadata);

-- ─── TASK ─────────────────────────

-- Case-insensitive name/title search
CREATE INDEX IF NOT EXISTS idx_tasks_name_lower ON tasks (LOWER(title));

-- GIN index for JSONB queries on tags
CREATE INDEX IF NOT EXISTS idx_tasks_tags_gin ON tasks USING GIN (tags);

-- GIN index for JSONB queries on metadata
CREATE INDEX IF NOT EXISTS idx_tasks_metadata_gin ON tasks USING GIN (metadata);
