-- ═══════════════════════════════════════════════
-- 📋 AUDIT LOG TABLES
-- Auto-generated by Backend Factory
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGSERIAL PRIMARY KEY,
  action VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id UUID,
  user_id UUID,
  tenant_id UUID,
  before_data JSONB,
  after_data JSONB,
  changes JSONB,
  ip_address VARCHAR(45),
  user_agent TEXT,
  request_id VARCHAR(100),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Query by entity
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs (entity_type, entity_id, created_at DESC);

-- Query by user
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs (user_id, created_at DESC);

-- Query by action
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs (action, created_at DESC);

-- Query by tenant
CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit_logs (tenant_id, created_at DESC);

-- Time-range queries
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs (created_at DESC);

DROP RULE IF EXISTS audit_no_update ON audit_logs;
CREATE RULE audit_no_update AS ON UPDATE TO audit_logs DO INSTEAD NOTHING;
DROP RULE IF EXISTS audit_no_delete ON audit_logs;
CREATE RULE audit_no_delete AS ON DELETE TO audit_logs DO INSTEAD NOTHING;
