/**
 * 🪝 Lifecycle Hook Runtime — generated by Forgx. DO NOT EDIT.
 *
 * Loads the per-entity hook module at src/hooks/<entity>.js and runs the matching
 * function around each CRUD write. Fill in your logic in those per-entity files —
 * Forgx creates them once and never overwrites them. This runtime is refreshed on
 * every generation, so edits here are lost.
 *
 * ctx = { req, res, tenantId, entity, action, input?, id?, record? }
 *
 * Contract:
 *   before*(ctx)  Runs before the DB write. Enrich ctx.input (the request body) in
 *                 place if you like. To REJECT the request, write the response via
 *                 ctx.res and `return false` — the route stops immediately.
 *   after*(ctx)   Runs after the DB write, with ctx.record set to the row. Its
 *                 errors are logged and swallowed: the write already committed, so
 *                 a failing side-effect never turns a success into a 500.
 */

const _cache = new Map(); // entity → { guard, gen, dev }

async function _load(entity) {
  if (_cache.has(entity)) return _cache.get(entity);
  const pair = { guard: null, gen: null, dev: null };
  if (/^[A-Za-z0-9_]+$/.test(entity)) {
    // Order = safety first: deterministic Forgx guards, then validated rule hooks,
    // then the developer's write-once hooks. Any absent file is a silent no-op.
    try { pair.guard = await import(new URL('./_' + entity + '.guards.js', import.meta.url)); } catch (_) {}
    try { pair.gen   = await import(new URL('./_' + entity + '.rules.js', import.meta.url)); } catch (_) {}
    try { pair.dev   = await import(new URL('./' + entity + '.js', import.meta.url)); } catch (_) {}
  }
  _cache.set(entity, pair);
  return pair;
}

/**
 * Run a lifecycle hook. Deterministic guards run first, then generated rule hooks,
 * then the developer's. For before* events any `return false` short-circuits
 * (request rejected); for after* events every hook runs and errors are logged.
 */
export async function runHook(entity, event, ctx) {
  const { guard, gen, dev } = await _load(entity);
  const fns = [guard && guard[event], gen && gen[event], dev && dev[event]].filter((f) => typeof f === 'function');
  if (fns.length === 0) return undefined;

  if (event.startsWith('after')) {
    for (const fn of fns) {
      try { await fn(ctx); }
      catch (err) { console.error('[hook:' + entity + '.' + event + '] ' + (err && err.message ? err.message : err)); }
    }
    return undefined;
  }

  for (const fn of fns) {
    if ((await fn(ctx)) === false) return false;
  }
  return undefined;
}

export default runHook;
