/**
 * 🧭 Postgres error → HTTP response mapper
 * Auto-generated by Forgx
 *
 * Constraint violations are client errors: surfacing them as 500s hides the
 * cause from the caller and misfiles user mistakes as server faults. Messages
 * are generic on purpose — no constraint names or raw driver detail leaks.
 */

const PG_ERROR_MAP = {
  '23505': { status: 409, code: 'CONFLICT', message: 'A record with this value already exists' },
  '23503': { status: 409, code: 'FK_CONFLICT', message: 'Operation conflicts with a related record' },
  '23502': { status: 400, code: 'MISSING_FIELD', message: 'A required field is missing' },
  '22003': { status: 400, code: 'OUT_OF_RANGE', message: 'A numeric value is out of range' },
  '22P02': { status: 400, code: 'INVALID_INPUT', message: 'A value has an invalid format' },
};

export function mapPgError(err) {
  if (!err || typeof err.code !== 'string') return null;
  return PG_ERROR_MAP[err.code] || null;
}
