/**
 * ⚡ Optimized Connection Pool
 * Auto-generated by Backend Factory
 *
 * Pool size: 5-17 connections
 * Entities: 6
 */

import { pool } from './pg.js';
export { pool };

// ─── Slow Query Detection ────────────────
const SLOW_QUERY_MS = 500;

const originalQuery = pool.query.bind(pool);
pool.query = async function trackedQuery(...args) {
  const start = Date.now();
  try {
    const result = await originalQuery(...args);
    const duration = Date.now() - start;
    if (duration > SLOW_QUERY_MS) {
      console.warn('⚠️  SLOW QUERY (' + duration + 'ms):', typeof args[0] === 'string' ? args[0].substring(0, 100) : 'prepared');
    }
    return result;
  } catch (err) {
    const duration = Date.now() - start;
    console.error('❌ QUERY ERROR (' + duration + 'ms):', err.message);
    throw err;
  }
};

// ─── Pool Metrics ───────────────────────
export function getPoolMetrics() {
  return {
    total: pool.totalCount,
    idle: pool.idleCount,
    waiting: pool.waitingCount,
    max: 17,
    utilization: ((pool.totalCount - pool.idleCount) / 17 * 100).toFixed(1) + '%',
  };
}

// ─── Health Check ───────────────────────
export async function checkPoolHealth() {
  const start = Date.now();
  try {
    const { rows } = await originalQuery('SELECT 1 as ok');
    const latency = Date.now() - start;
    return {
      healthy: true,
      latency,
      metrics: getPoolMetrics(),
    };
  } catch (err) {
    return {
      healthy: false,
      error: err.message,
      metrics: getPoolMetrics(),
    };
  }
}

// ─── Graceful Shutdown ──────────────────
let _poolEnded = false;
export async function shutdownPool() {
  if (_poolEnded) return;
  _poolEnded = true;
  console.log('🔌 Draining connection pool...');
  await pool.end();
  console.log('✅ Pool drained');
}

// Auto-shutdown on process exit
process.on('SIGTERM', shutdownPool);
process.on('SIGINT', shutdownPool);

// ─── Connection error handling ──────────
pool.on('error', (err) => {
  console.error('🚨 Unexpected pool error:', err.message);
});

pool.on('connect', () => {
  // Set per-connection defaults
});
