/**
 * 🔄 Retry & Recovery Helpers
 * Auto-generated by Backend Factory
 */

/**
 * Retry an async operation with exponential backoff.
 * @param {function} fn - async function to retry
 * @param {object} opts - { retries, baseDelay, maxDelay, shouldRetry }
 * @returns {*} result of fn
 */
export async function withRetry(fn, opts = {}) {
  const {
    retries = 3,
    baseDelay = 200,
    maxDelay = 5000,
    shouldRetry = (err) => err.status >= 500 || err.code === 'ECONNRESET',
  } = opts;

  let lastError;

  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      return await fn();
    } catch (err) {
      lastError = err;

      if (attempt === retries || !shouldRetry(err)) {
        throw err;
      }

      const delay = Math.min(baseDelay * Math.pow(2, attempt) + Math.random() * 100, maxDelay);
      console.warn('⚠️  Retry ' + (attempt + 1) + '/' + retries + ' after ' + Math.round(delay) + 'ms: ' + err.message);
      await new Promise((r) => setTimeout(r, delay));
    }
  }

  throw lastError;
}

/**
 * Circuit Breaker — stops calling failing services.
 *
 * States: CLOSED (normal) → OPEN (failing) → HALF_OPEN (testing)
 *
 * @param {object} opts - { failureThreshold, resetTimeout, name }
 */
export class CircuitBreaker {
  constructor(opts = {}) {
    this.name = opts.name || 'default';
    this.failureThreshold = opts.failureThreshold || 5;
    this.resetTimeout = opts.resetTimeout || 30000;
    this.state = 'CLOSED';
    this.failures = 0;
    this.lastFailure = null;
    this.successes = 0;
  }

  async call(fn) {
    if (this.state === 'OPEN') {
      if (Date.now() - this.lastFailure > this.resetTimeout) {
        this.state = 'HALF_OPEN';
      } else {
        throw new Error('Circuit breaker OPEN for ' + this.name + ' — service unavailable');
      }
    }

    try {
      const result = await fn();
      this.onSuccess();
      return result;
    } catch (err) {
      this.onFailure();
      throw err;
    }
  }

  onSuccess() {
    this.failures = 0;
    this.successes++;
    if (this.state === 'HALF_OPEN') {
      this.state = 'CLOSED';
      console.log('🟢 Circuit breaker CLOSED for ' + this.name);
    }
  }

  onFailure() {
    this.failures++;
    this.lastFailure = Date.now();
    if (this.failures >= this.failureThreshold) {
      this.state = 'OPEN';
      console.error('🔴 Circuit breaker OPEN for ' + this.name + ' after ' + this.failures + ' failures');
    }
  }

  getStatus() {
    return {
      name: this.name,
      state: this.state,
      failures: this.failures,
      successes: this.successes,
    };
  }
}

/**
 * Dead Letter Queue — stores operations that failed permanently.
 * Useful for webhook deliveries, notifications, etc.
 */
export class DeadLetterQueue {
  constructor(opts = {}) {
    this.name = opts.name || 'default';
    this.maxSize = opts.maxSize || 1000;
    this.items = [];
  }

  add(operation, error, context = {}) {
    if (this.items.length >= this.maxSize) {
      this.items.shift();
    }
    this.items.push({
      operation,
      error: error.message,
      context,
      failedAt: new Date().toISOString(),
      retryCount: 0,
    });
  }

  getAll() {
    return [...this.items];
  }

  size() {
    return this.items.length;
  }

  clear() {
    this.items = [];
  }

  async retryAll(handler) {
    const results = { succeeded: 0, failed: 0 };
    const remaining = [];

    for (const item of this.items) {
      try {
        await handler(item);
        results.succeeded++;
      } catch (err) {
        item.retryCount++;
        item.lastRetryError = err.message;
        remaining.push(item);
        results.failed++;
      }
    }

    this.items = remaining;
    return results;
  }
}
