// Generated by Forgx — mounts external-service routes.
// Auto-discovered by the server's dynamic route loader, which imports this
// src/integrations/index.js and awaits its registerRoutes(app) export.
//
// Each route is imported INDEPENDENTLY and wrapped in try/catch: a single service
// that fails to load (e.g. a missing optional dependency) is logged and skipped,
// and can never stop the other services' routes from mounting.
const _mounts = [
  ['/api/uploads', '../routes/upload.routes.js']
]

export async function registerRoutes(app) {
  for (const [base, file] of _mounts) {
    try {
      const mod = await import(file)
      const router = mod.default || mod.router
      if (router) app.use(base, router)
    } catch (e) {
      console.error('[integrations] skipped ' + file + ' — ' + e.message)
    }
  }
}

export default registerRoutes
