/**
 * 🧠 Business Logic — Route Registration Index
 * Auto-generated by Forgx
 */

import { registerSettlementRoutes } from './settlementRoutes.js';
import { registernotificationqueueRoutes } from './notificationqueueRoutes.js';
import { registerMultiCurrencyRoutes } from './multicurrencyRoutes.js';

export function registerRoutes(app) {
  registerSettlementRoutes(app);
  registernotificationqueueRoutes(app);
  registerMultiCurrencyRoutes(app);
}
