/**
 * Multi-Currency / FX Service — teamflow
 * Auto-generated by Forgx | ISO-4217 currency engine
 *
 * Correctness contract: ALL money arithmetic happens in Postgres NUMERIC —
 * amounts and rates travel through JavaScript as validated strings only, so
 * IEEE-754 float error can never touch a monetary value. Rounding uses each
 * currency's ISO-4217 minor-unit exponent (JPY=0, USD=2, KWD=3).
 *
 * Rate model: append-only per-tenant history (rates are never mutated), the
 * latest effective rate wins, future-dated rates activate automatically.
 * Resolution is direct pair → stored inverse (1/rate). NO implicit
 * cross-rates: chaining pairs compounds spread error silently — a missing
 * pair is an explicit NO_RATE, never a guess.
 */

import { pool } from '../db/pg.js';

const CODE_RE   = /^[A-Z]{3}$/;
const AMOUNT_RE = /^\d{1,15}(\.\d{1,10})?$/;
const RATE_RE   = /^\d{1,12}(\.\d{1,12})?$/;
const ZERO_RE   = /^0+(\.0+)?$/;

export class FxError extends Error {
  constructor(code, message) { super(message); this.code = code; }
}

const assertCode = (c) => {
  const code = String(c == null ? '' : c).trim().toUpperCase();
  if (!CODE_RE.test(code)) throw new FxError('INVALID_CURRENCY', 'currency must be a 3-letter ISO 4217 code');
  return code;
};

const assertAmount = (a) => {
  const amount = String(a == null ? '' : a).trim();
  if (!AMOUNT_RE.test(amount) || ZERO_RE.test(amount)) {
    throw new FxError('INVALID_AMOUNT', 'amount must be a positive decimal (max 15 integer / 10 fraction digits)');
  }
  return amount;
};

async function assertKnown(codes) {
  const { rows } = await pool.query('SELECT code FROM currencies WHERE active AND code = ANY($1)', [codes]);
  const known = new Set(rows.map(r => r.code));
  for (const c of codes) {
    if (!known.has(c)) throw new FxError('UNKNOWN_CURRENCY', 'unknown or inactive currency: ' + c);
  }
}

export async function listCurrencies() {
  const { rows } = await pool.query('SELECT code, name, exponent FROM currencies WHERE active ORDER BY code');
  return rows;
}

/**
 * Latest effective rate for a pair. Direct rate preferred; a stored inverse
 * pair is applied as division. Throws NO_RATE when neither exists.
 */
export async function getRate(tenantId, from, to) {
  const f = assertCode(from), t = assertCode(to);
  const { rows } = await pool.query(
    `SELECT id, rate::text AS rate, source, effective_at, inverted
       FROM (
         SELECT id, rate, source, effective_at, FALSE AS inverted
           FROM exchange_rates
          WHERE tenant_id = $1 AND base_currency = $2 AND quote_currency = $3 AND effective_at <= now()
         UNION ALL
         SELECT id, rate, source, effective_at, TRUE
           FROM exchange_rates
          WHERE tenant_id = $1 AND base_currency = $3 AND quote_currency = $2 AND effective_at <= now()
       ) candidates
      ORDER BY inverted ASC, effective_at DESC
      LIMIT 1`,
    [tenantId, f, t]
  );
  if (rows.length === 0) throw new FxError('NO_RATE', 'no exchange rate configured for ' + f + '/' + t + ' — an admin must add one');
  return rows[0];
}

/** Convert without persisting — a price display / preview. */
export async function quote(tenantId, { from, to, amount }) {
  if (!tenantId) throw new FxError('INVALID_TENANT', 'missing tenant context');
  const f = assertCode(from), t = assertCode(to), amt = assertAmount(amount);
  await assertKnown(f === t ? [f] : [f, t]);

  if (f === t) {
    const { rows } = await pool.query(
      'SELECT round($1::numeric, exponent)::text AS converted FROM currencies WHERE code = $2',
      [amt, t]
    );
    return { from: f, to: t, amount: amt, converted: rows[0].converted, rate: '1', inverted: false, rate_id: null, source: 'identity', effective_at: null };
  }

  const r = await getRate(tenantId, f, t);
  const { rows } = await pool.query(
    'SELECT round(CASE WHEN $3 THEN $1::numeric / $2::numeric ELSE $1::numeric * $2::numeric END, c.exponent)::text AS converted FROM currencies c WHERE c.code = $4',
    [amt, r.rate, r.inverted, t]
  );
  return { from: f, to: t, amount: amt, converted: rows[0].converted, rate: r.rate, inverted: r.inverted, rate_id: r.id, source: r.source, effective_at: r.effective_at };
}

/** Convert AND persist an audit row (rate snapshot survives independently). */
export async function convert(tenantId, { from, to, amount, reference }, userId = null) {
  const q = await quote(tenantId, { from, to, amount });
  const ref = reference == null ? null : String(reference).slice(0, 200);
  const { rows } = await pool.query(
    `INSERT INTO fx_conversions (tenant_id, rate_id, from_currency, to_currency, amount_in, amount_out, rate_used, inverted, reference, created_by)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
     RETURNING id, created_at`,
    [tenantId, q.rate_id, q.from, q.to, q.amount, q.converted, q.rate, q.inverted, ref, userId]
  );
  return { ...q, conversion_id: rows[0].id, created_at: rows[0].created_at };
}

/** Append a rate (admin). Never updates — history is the audit trail. */
export async function addRate(tenantId, { base, quote: quoteCcy, rate, source, effective_at }, userId = null) {
  if (!tenantId) throw new FxError('INVALID_TENANT', 'missing tenant context');
  const b = assertCode(base), q = assertCode(quoteCcy);
  if (b === q) throw new FxError('INVALID_RATE', 'base and quote currencies must differ');
  const r = String(rate == null ? '' : rate).trim();
  if (!RATE_RE.test(r) || ZERO_RE.test(r)) {
    throw new FxError('INVALID_RATE', 'rate must be a positive decimal (max 12 integer / 12 fraction digits)');
  }
  await assertKnown([b, q]);
  let eff = null;
  if (effective_at != null) {
    const ts = Date.parse(effective_at);
    if (!Number.isFinite(ts)) throw new FxError('INVALID_RATE', 'effective_at must be an ISO-8601 timestamp');
    eff = new Date(ts).toISOString();
  }
  const src = source == null ? 'manual' : String(source).slice(0, 40);
  const { rows } = await pool.query(
    `INSERT INTO exchange_rates (tenant_id, base_currency, quote_currency, rate, source, effective_at, created_by)
     VALUES ($1, $2, $3, $4, $5, COALESCE($6::timestamptz, now()), $7)
     RETURNING id, base_currency, quote_currency, rate::text AS rate, source, effective_at`,
    [tenantId, b, q, r, src, eff, userId]
  );
  return rows[0];
}

/** Current rate per pair (default) or full append-only history (history=true). */
export async function listRates(tenantId, { base, quote: quoteCcy, history, limit } = {}) {
  if (!tenantId) throw new FxError('INVALID_TENANT', 'missing tenant context');
  const params = [tenantId];
  const where  = ['tenant_id = $1'];
  if (base)     { params.push(assertCode(base));     where.push('base_currency = $'  + params.length); }
  if (quoteCcy) { params.push(assertCode(quoteCcy)); where.push('quote_currency = $' + params.length); }
  params.push(Math.min(Math.max(parseInt(limit, 10) || 50, 1), 200));
  const cols = 'id, base_currency, quote_currency, rate::text AS rate, source, effective_at, created_at';
  const sql = history
    ? 'SELECT ' + cols + ' FROM exchange_rates WHERE ' + where.join(' AND ') +
      ' ORDER BY effective_at DESC LIMIT $' + params.length
    : 'SELECT DISTINCT ON (base_currency, quote_currency) ' + cols +
      ' FROM exchange_rates WHERE ' + where.join(' AND ') + ' AND effective_at <= now()' +
      ' ORDER BY base_currency, quote_currency, effective_at DESC LIMIT $' + params.length;
  const { rows } = await pool.query(sql, params);
  return rows;
}
