/**
 * Multi-Currency / FX Routes — teamflow
 * Auto-generated by Forgx | tenant-isolated, parameterized SQL
 * Quote/convert: any authenticated user. Rate management: admin only.
 */

import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { FxError, listCurrencies, quote, convert, addRate, listRates } from './multiCurrencyService.js';

const STATUS = { INVALID_CURRENCY: 400, INVALID_AMOUNT: 400, INVALID_RATE: 400, UNKNOWN_CURRENCY: 400, INVALID_TENANT: 401, NO_RATE: 422 };

const fail = (res, err) => {
  if (err instanceof FxError) return res.status(STATUS[err.code] || 400).json({ error: err.message, code: err.code });
  res.status(500).json({ error: process.env.NODE_ENV === 'production' ? 'Internal server error' : err.message });
};

export function registerMultiCurrencyRoutes(app) {
  app.get('/api/currencies', requireAuth, async (req, res) => {
    try { res.json({ currencies: await listCurrencies() }); } catch (err) { fail(res, err); }
  });

  app.get('/api/fx/quote', requireAuth, async (req, res) => {
    try {
      res.json(await quote(req.context.tenant_id, { from: req.query.from, to: req.query.to, amount: req.query.amount }));
    } catch (err) { fail(res, err); }
  });

  app.post('/api/fx/convert', requireAuth, async (req, res) => {
    try {
      const b = req.body || {};
      res.status(201).json(await convert(req.context.tenant_id,
        { from: b.from, to: b.to, amount: b.amount, reference: b.reference },
        req.context.user_id || null));
    } catch (err) { fail(res, err); }
  });

  app.get('/api/admin/fx/rates', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const rates = await listRates(req.context.tenant_id, {
        base: req.query.base, quote: req.query.quote,
        history: req.query.history === 'true', limit: req.query.limit,
      });
      res.json({ rates, count: rates.length });
    } catch (err) { fail(res, err); }
  });

  app.post('/api/admin/fx/rates', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      res.status(201).json(await addRate(req.context.tenant_id, req.body || {}, req.context.user_id || null));
    } catch (err) { fail(res, err); }
  });
}
