/**
 * Notification Queue Routes — teamflow
 * Auto-generated by Forgx
 */

import { Router } from 'express';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { enqueue, enqueueFromTemplate, enqueueBatch, retryNotification, listNotifications, getPreferences, setPreference, createTemplate, listTemplates, } from '../businessLogic/notificationqueueService.js';

const router = Router();

// ── Enqueue ───────────────────────────────────────────────────────────────

router.post('/', requireAuth, async (req, res) => {
  try {
    const { recipientId, channel, type, subject, body, metadata, idempotencyKey, scheduledAt } = req.body;
    const result = await enqueue({
      tenantId: req.context.tenant_id,
      recipientId, channel, type, subject, body,
      metadata, idempotencyKey,
      scheduledAt: scheduledAt ? new Date(scheduledAt) : null,
    });
    res.status(201).json({ status: 'ok', data: result });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

router.post('/template', requireAuth, async (req, res) => {
  try {
    const { templateCode, recipientId, channel, vars, metadata, idempotencyKey, scheduledAt } = req.body;
    const result = await enqueueFromTemplate({
      tenantId: req.context.tenant_id,
      templateCode, recipientId, channel,
      vars: vars || {},
      metadata, idempotencyKey,
      scheduledAt: scheduledAt ? new Date(scheduledAt) : null,
    });
    res.status(201).json({ status: 'ok', data: result });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

router.post('/batch', requireAuth, async (req, res) => {
  try {
    const { recipients, notification } = req.body;
    const results = await enqueueBatch(req.context.tenant_id, recipients, notification);
    res.json({ status: 'ok', data: results });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

// ── Query ─────────────────────────────────────────────────────────────────

router.get('/', requireAuth, async (req, res) => {
  try {
    const notifications = await listNotifications(req.context.tenant_id, {
      recipientId: req.query.recipientId,
      channel:     req.query.channel,
      status:      req.query.status,
      type:        req.query.type,
      limit:       req.query.limit,
      offset:      req.query.offset,
    });
    res.json({ status: 'ok', data: notifications });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

// ── Retry ─────────────────────────────────────────────────────────────────

router.post('/:id/retry', requireAuth, async (req, res) => {
  try {
    const result = await retryNotification(req.params.id, req.context.tenant_id);
    res.json({ status: 'ok', data: result });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

// ── Preferences ───────────────────────────────────────────────────────────

router.get('/preferences', requireAuth, async (req, res) => {
  try {
    const prefs = await getPreferences(req.context.tenant_id, req.context.user_id);
    res.json({ status: 'ok', data: prefs });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

router.put('/preferences', requireAuth, async (req, res) => {
  try {
    const { channel, notificationType, isEnabled } = req.body;
    if (typeof isEnabled !== 'boolean') {
      return res.status(400).json({ status: 'error', code: 'INVALID_PAYLOAD', message: 'isEnabled must be a boolean' });
    }
    await setPreference(req.context.tenant_id, req.context.user_id, channel, notificationType || '*', isEnabled);
    res.json({ status: 'ok' });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

// ── Templates ─────────────────────────────────────────────────────────────

router.get('/templates', requireAuth, async (req, res) => {
  try {
    const templates = await listTemplates(req.context.tenant_id);
    res.json({ status: 'ok', data: templates });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

router.post('/templates', requireAuth, requireRole('admin'), async (req, res) => {
  try {
    const template = await createTemplate(req.context.tenant_id, req.body);
    res.status(201).json({ status: 'ok', data: template });
  } catch (err) {
    res.status(err.status || 500).json({ status: 'error', code: err.code || 'INTERNAL_ERROR', message: err.message });
  }
});

export function registernotificationqueueRoutes(app) {
  app.use('/api/notifications', router);
}
