/**
 * Notification Queue Service — teamflow
 * Auto-generated by Forgx | Production-grade | Security-first
 *
 * Architecture:
 *   Enqueue → DB row (status=pending) → Worker polls (SKIP LOCKED) → Deliver → mark sent/failed
 *   Retries: exponential backoff [60s → 300s → 900s], max 3 attempts
 *   Idempotency: unique (tenant_id, idempotency_key) — duplicate enqueues are no-ops
 *   Preferences: per-user, per-channel, per-type opt-out (wildcard '*' covers all types)
 *   Rate limit: 10 notifications per user per channel per 1h window
 *
 * Channel adapters (email/SMS/push) are injected at call time — this service
 * handles only queue management and state tracking.
 */

import { pool } from '../db/pg.js';

// ── Constants ────────────────────────────────────────────────────────────────

const CHANNEL = Object.freeze({
  EMAIL:  'email',
  SMS:    'sms',
  PUSH:   'push',
  IN_APP: 'in_app',
});
const STATUS = Object.freeze({
  PENDING:    'pending',
  SENDING:    'sending',
  SENT:       'sent',
  FAILED:     'failed',
  SUPPRESSED: 'suppressed',
});
const VALID_CHANNELS  = Object.values(CHANNEL);
const RETRY_DELAYS_S  = [60, 300, 900];   // attempt 1→60s, 2→300s, 3→900s
const MAX_RETRIES     = RETRY_DELAYS_S.length;
const RATE_LIMIT_WINDOW_H = 1;
const RATE_LIMIT_MAX      = 10;

// ── Helpers ──────────────────────────────────────────────────────────────────

function assertChannel(channel) {
  if (!VALID_CHANNELS.includes(channel)) {
    throw Object.assign(
      new Error(`channel must be one of: ${VALID_CHANNELS.join(', ')}`),
      { status: 400, code: 'INVALID_CHANNEL' }
    );
  }
}

// Renders {{variable}} placeholders. Strips HTML from injected values to prevent
// injection if notification body is ever rendered in a browser context.
function renderTemplate(template, vars = {}) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const val = vars[key];
    if (val == null) return '';
    return String(val).replace(/<[^>]*>/g, '');
  });
}

// ── Core Queue Operations ────────────────────────────────────────────────────

/**
 * Enqueue a notification. Returns immediately; delivery is async via worker poll.
 *
 * @param {object}  opts
 * @param {string}  opts.tenantId
 * @param {string}  opts.recipientId     — user id of recipient
 * @param {string}  opts.channel         — 'email' | 'sms' | 'push' | 'in_app'
 * @param {string}  opts.type            — notification type, e.g. 'order_confirmed'
 * @param {string}  [opts.subject]       — subject line (email only)
 * @param {string}  opts.body            — rendered message body
 * @param {object}  [opts.metadata]      — arbitrary JSON payload
 * @param {string}  [opts.idempotencyKey] — caller-supplied dedup key
 * @param {Date}    [opts.scheduledAt]   — future delivery time; null = immediate
 * @returns {{ notificationId: string|null, status: string, reason?: string }}
 */
export async function enqueue(opts) {
  const {
    tenantId, recipientId, channel, type,
    subject, body, metadata = {},
    idempotencyKey, scheduledAt = null,
  } = opts;

  assertChannel(channel);
  if (!recipientId)  throw Object.assign(new Error('recipientId is required'),  { status: 400, code: 'MISSING_RECIPIENT' });
  if (!type)         throw Object.assign(new Error('type is required'),          { status: 400, code: 'MISSING_TYPE' });
  if (!body?.trim()) throw Object.assign(new Error('body is required'),          { status: 400, code: 'MISSING_BODY' });

  const ikey   = idempotencyKey || `${tenantId}:${recipientId}:${type}:${channel}`;
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Preference check — most-specific preference wins (type > '*')
    const { rows: prefRows } = await client.query(
      `SELECT is_enabled
       FROM notification_preferences
       WHERE tenant_id = $1 AND user_id = $2 AND channel = $3
         AND (notification_type = $4 OR notification_type = '*')
       ORDER BY CASE WHEN notification_type = '*' THEN 1 ELSE 0 END
       LIMIT 1`,
      [tenantId, recipientId, channel, type]
    );
    if (prefRows.length > 0 && !prefRows[0].is_enabled) {
      await client.query('ROLLBACK');
      return { notificationId: null, status: STATUS.SUPPRESSED, reason: 'user_preference' };
    }

    // Rate limit: count non-suppressed/failed in last RATE_LIMIT_WINDOW_H hours
    const { rows: rateRows } = await client.query(
      `SELECT COUNT(*) AS cnt
       FROM notifications
       WHERE tenant_id = $1 AND recipient_id = $2 AND channel = $3
         AND status NOT IN ('suppressed', 'failed')
         AND created_at >= NOW() - ($4 || ' hours')::INTERVAL`,
      [tenantId, recipientId, channel, RATE_LIMIT_WINDOW_H]
    );
    if (parseInt(rateRows[0].cnt, 10) >= RATE_LIMIT_MAX) {
      await client.query('ROLLBACK');
      return { notificationId: null, status: STATUS.SUPPRESSED, reason: 'rate_limit' };
    }

    // Idempotent insert — ON CONFLICT DO NOTHING returns 0 rows on duplicate
    const { rows } = await client.query(
      `INSERT INTO notifications
         (tenant_id, recipient_id, channel, notification_type, subject, body,
          metadata, idempotency_key, scheduled_at, status, retry_count, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending', 0, NOW())
       ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
       RETURNING id, status`,
      [tenantId, recipientId, channel, type, subject || null, body,
       JSON.stringify(metadata), ikey, scheduledAt]
    );

    await client.query('COMMIT');
    if (rows.length === 0) return { notificationId: null, status: STATUS.SUPPRESSED, reason: 'duplicate' };
    return { notificationId: rows[0].id, status: rows[0].status };
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

/**
 * Render a stored template and enqueue.
 */
export async function enqueueFromTemplate(opts) {
  const { tenantId, templateCode, recipientId, channel, vars = {}, metadata, idempotencyKey, scheduledAt } = opts;
  const { rows } = await pool.query(
    `SELECT subject_template, body_template, notification_type
     FROM notification_templates
     WHERE tenant_id = $1 AND deleted_at IS NULL AND code = $2 AND is_active = true
     LIMIT 1`,
    [tenantId, templateCode]
  );
  if (rows.length === 0) {
    throw Object.assign(new Error(`Template '${templateCode}' not found`), { status: 404, code: 'TEMPLATE_NOT_FOUND' });
  }
  const t = rows[0];
  return enqueue({
    tenantId, recipientId, channel,
    type:    t.notification_type,
    subject: t.subject_template ? renderTemplate(t.subject_template, vars) : null,
    body:    renderTemplate(t.body_template, vars),
    metadata, idempotencyKey, scheduledAt,
  });
}

/**
 * Batch enqueue — same notification type to multiple recipients.
 * Each enqueue is individually idempotency-checked and rate-limited.
 * Returns per-recipient results without short-circuiting on individual failures.
 */
export async function enqueueBatch(tenantId, recipients, notifBase) {
  if (!Array.isArray(recipients) || recipients.length === 0) {
    throw Object.assign(new Error('recipients must be a non-empty array'), { status: 400, code: 'INVALID_RECIPIENTS' });
  }
  if (recipients.length > 1000) {
    throw Object.assign(new Error('Batch size limit is 1000'), { status: 400, code: 'BATCH_TOO_LARGE' });
  }
  const results = [];
  for (const recipientId of recipients) {
    try {
      const res = await enqueue({ ...notifBase, tenantId, recipientId });
      results.push({ recipientId, ...res });
    } catch (err) {
      results.push({ recipientId, status: 'error', error: err.message });
    }
  }
  return results;
}

// ── Worker Polling ───────────────────────────────────────────────────────────

/**
 * Poll next batch of pending notifications ready for delivery.
 * SELECT FOR UPDATE SKIP LOCKED — safe for concurrent worker processes.
 * Workers should call markSent or markFailed after attempting delivery.
 */
export async function pollPending(batchSize = 50) {
  const { rows } = await pool.query(
    `SELECT id, tenant_id, recipient_id, channel, notification_type,
            subject, body, metadata, retry_count
     FROM notifications
     WHERE status = 'pending'
       AND (scheduled_at IS NULL OR scheduled_at <= NOW())
     ORDER BY created_at ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED`,
    [Math.min(batchSize, 200)]
  );
  return rows;
}

export async function markSent(notificationId, tenantId) {
  await pool.query(
    `UPDATE notifications
     SET status = 'sent', sent_at = NOW(), updated_at = NOW()
     WHERE id = $1 AND tenant_id = $2 AND status IN ('pending', 'sending')`,
    [notificationId, tenantId]
  );
}

/**
 * Mark failed and schedule retry with exponential backoff.
 * After MAX_RETRIES attempts, status becomes 'failed' permanently (manual retry required).
 */
export async function markFailed(notificationId, tenantId, errorMessage) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const { rows } = await client.query(
      `SELECT retry_count FROM notifications
       WHERE id = $1 AND tenant_id = $2
       FOR UPDATE`,
      [notificationId, tenantId]
    );
    if (rows.length === 0) { await client.query('ROLLBACK'); return; }

    const n = rows[0].retry_count;
    if (n < MAX_RETRIES) {
      await client.query(
        `UPDATE notifications
         SET status = 'pending',
             retry_count   = retry_count + 1,
             last_error    = $1,
             next_retry_at = NOW() + ($2 || ' seconds')::INTERVAL,
             updated_at    = NOW()
         WHERE id = $3 AND tenant_id = $4`,
        [String(errorMessage).slice(0, 500), RETRY_DELAYS_S[n], notificationId, tenantId]
      );
    } else {
      await client.query(
        `UPDATE notifications
         SET status = 'failed', last_error = $1, updated_at = NOW()
         WHERE id = $2 AND tenant_id = $3`,
        [String(errorMessage).slice(0, 500), notificationId, tenantId]
      );
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

/** Manually retry a failed notification — resets attempt counter. */
export async function retryNotification(notificationId, tenantId) {
  const { rows } = await pool.query(
    `UPDATE notifications
     SET status = 'pending', retry_count = 0, next_retry_at = NULL, updated_at = NOW()
     WHERE id = $1 AND tenant_id = $2 AND status = 'failed'
     RETURNING id`,
    [notificationId, tenantId]
  );
  if (rows.length === 0) {
    throw Object.assign(new Error('Notification not found or not in failed state'), { status: 404, code: 'NOT_FOUND' });
  }
  return rows[0];
}

// ── Preferences ──────────────────────────────────────────────────────────────

export async function getPreferences(tenantId, userId) {
  const { rows } = await pool.query(
    `SELECT channel, notification_type, is_enabled
     FROM notification_preferences
     WHERE tenant_id = $1 AND user_id = $2
     ORDER BY channel, notification_type`,
    [tenantId, userId]
  );
  return rows;
}

/**
 * Upsert a single preference.
 * Set notification_type = '*' to opt-out of an entire channel.
 */
export async function setPreference(tenantId, userId, channel, notificationType, isEnabled) {
  assertChannel(channel);
  await pool.query(
    `INSERT INTO notification_preferences
       (tenant_id, user_id, channel, notification_type, is_enabled, updated_at)
     VALUES ($1, $2, $3, $4, $5, NOW())
     ON CONFLICT (tenant_id, user_id, channel, notification_type)
     DO UPDATE SET is_enabled = EXCLUDED.is_enabled, updated_at = NOW()`,
    [tenantId, userId, channel, notificationType, isEnabled]
  );
}

// ── Templates ────────────────────────────────────────────────────────────────

export async function createTemplate(tenantId, { code, notification_type, subject_template, body_template, description }) {
  if (!code || !notification_type || !body_template) {
    throw Object.assign(new Error('code, notification_type, and body_template are required'), { status: 400, code: 'MISSING_FIELDS' });
  }
  const { rows } = await pool.query(
    `INSERT INTO notification_templates
       (tenant_id, code, notification_type, subject_template, body_template, description, is_active, created_at)
     VALUES ($1, $2, $3, $4, $5, $6, true, NOW())
     ON CONFLICT (tenant_id, code) DO UPDATE
       SET subject_template = EXCLUDED.subject_template,
           body_template     = EXCLUDED.body_template,
           description       = EXCLUDED.description,
           updated_at        = NOW()
     RETURNING id, code`,
    [tenantId, code, notification_type, subject_template || null, body_template, description || null]
  );
  return rows[0];
}

export async function listTemplates(tenantId) {
  const { rows } = await pool.query(
    `SELECT id, code, notification_type, description, is_active, created_at
     FROM notification_templates
     WHERE tenant_id = $1 AND deleted_at IS NULL
     ORDER BY notification_type, code`,
    [tenantId]
  );
  return rows;
}

// ── Query ────────────────────────────────────────────────────────────────────

export async function listNotifications(tenantId, filters = {}) {
  const { recipientId, channel, status, type, limit = 50, offset = 0 } = filters;
  const params = [tenantId];
  const conds  = ['n.tenant_id = $1'];

  if (recipientId) conds.push(`n.recipient_id = $${params.push(recipientId)}`);
  if (channel)     conds.push(`n.channel = $${params.push(channel)}`);
  if (status)      conds.push(`n.status = $${params.push(status)}`);
  if (type)        conds.push(`n.notification_type = $${params.push(type)}`);

  const lim = Math.min(Number(limit)  || 50,  200);
  const off = Math.max(Number(offset) || 0,   0);

  const { rows } = await pool.query(
    `SELECT id, recipient_id, channel, notification_type, status,
            retry_count, scheduled_at, sent_at, created_at
     FROM notifications n
     WHERE ${conds.join(' AND ')}
     ORDER BY created_at DESC
     LIMIT ${lim} OFFSET ${off}`,
    params
  );
  return rows;
}
