/**
 * 🚀 teamflow — Server
 * Generated by Backend Factory
 */

import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import dotenv from 'dotenv';
import { readdirSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';

import { authRoutes } from './routes/authRoutes.js';
import { sanitizeInput } from './middleware/sanitizer.js';
import { requestIdMiddleware, errorHandler, notFoundHandler } from './middleware/errorMiddleware.js';
import { registerAttachmentRoutes } from './routes/attachmentRoutes.js';
import { registerCommentRoutes } from './routes/commentRoutes.js';
import { registerInviteRoutes } from './routes/inviteRoutes.js';
import { registerProjectRoutes } from './routes/projectRoutes.js';
import { registerSubscriptionRoutes } from './routes/subscriptionRoutes.js';
import { registerTaskRoutes } from './routes/taskRoutes.js';

import { registerAuditRoutes } from './audit/auditRoutes.js';
import { registerCronRoutes } from './cron/cronRoutes.js';

// ─── Auto-wired imports ───
import { registerHealthRoutes } from './routes/health.js';
import { auditMiddleware } from './audit/auditMiddleware.js';
import { startAllCronJobs } from './cron/cronService.js';
import './cron/cleanupJobs.js';
import './cron/reminderJobs.js';


dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(helmet());
app.use(requestIdMiddleware);
app.use(cookieParser());
app.use(cors({
  origin: process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',').map(o => o.trim()) : (process.env.NODE_ENV === 'production' ? (console.warn('⚠️  ALLOWED_ORIGINS not set — all cross-origin requests blocked'), []) : '*'),
  credentials: true,
}));
app.use(express.json({ limit: '10mb' }));
app.use(rateLimit({ windowMs: Math.max(1000, parseInt(process.env.RATE_LIMIT_WINDOW_MS || '60000') || 60000), max: Math.max(1, parseInt(process.env.RATE_LIMIT_MAX_REQUESTS || process.env.RATE_LIMIT_MAX || '100') || 100), standardHeaders: true, legacyHeaders: false }));
const authRateLimit = rateLimit({ windowMs: 15 * 60 * 1000, max: 10, standardHeaders: true, legacyHeaders: false, message: { code: 'TOO_MANY_ATTEMPTS', message: 'Too many auth attempts, try again in 15 minutes' } });
app.use('/auth/login', authRateLimit);
app.use('/auth/signup', authRateLimit);
app.use('/auth/reset-password', authRateLimit);

// XSS sanitization — strips HTML/script from all inputs
app.use(sanitizeInput);

// Request logger — structured JSON for Datadog/CloudWatch
try {
  const { requestLogger } = await import('./middleware/requestLogger.js');
  app.use(requestLogger);
} catch (_) {}

app.get('/health', (req, res) => res.json({ status: 'ok', service: 'teamflow', timestamp: new Date().toISOString() }));

// ─── Audit + request logging middleware MUST be here, before routes ───

// ─── Auto-wired middleware ───
app.use(auditMiddleware);

app.use('/auth', authRoutes);

registerAttachmentRoutes(app);
registerCommentRoutes(app);
registerInviteRoutes(app);
registerProjectRoutes(app);
registerSubscriptionRoutes(app);
registerTaskRoutes(app);

registerAuditRoutes(app);
registerCronRoutes(app);

const dynamicDirs = existsSync(fileURLToPath(new URL('.', import.meta.url))) ? readdirSync(fileURLToPath(new URL('.', import.meta.url))) : [];
// #11: 'routes' (entity CRUD) is mounted explicitly above; its index.js also
// exports registerRoutes, so the dynamic loader would mount every entity route a
// second time. Skip already-explicitly-mounted dirs (businessLogic stays dynamic).
const EXPLICITLY_MOUNTED = new Set(['routes']);
for (const dir of dynamicDirs) {
  if (EXPLICITLY_MOUNTED.has(dir)) continue;
  try {
    const indexPath = fileURLToPath(new URL('./' + dir + '/index.js', import.meta.url));
    if (existsSync(indexPath)) {
      const mod = await import('./' + dir + '/index.js');
      if (mod.registerRoutes) {
        await mod.registerRoutes(app);
        console.log('   ✅ Dynamic route: /api/' + dir);
      }
    }
  } catch (e) { console.error('Dynamic route load error:', e.message); }
}


// ─── Auto-wired routes ───
registerHealthRoutes(app);

app.use(notFoundHandler);
app.use(errorHandler);

app.listen(PORT, '0.0.0.0', () => {
    // ─── Start cron jobs ───
    startAllCronJobs();

  console.log('\n🚀 teamflow on port ' + PORT);
  console.log('   Auth: http://localhost:' + PORT + '/auth/signup');
  console.log('   API:  http://localhost:' + PORT + '/api/\n');
});

export default app;
