/**
 * 🧹 Cleanup Jobs
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { registerCronJob } from './cronService.js';

/**
 * Clean up old events (older than 90 days)
 */
registerCronJob('cleanup:events', {
  interval: '1d',
  description: 'Delete events older than 90 days',
  handler: async () => {
    const t = await pool.query("SELECT to_regclass('public.events') AS t");
    if (!t.rows[0].t) return { deleted: 0, table: 'events', skipped: 'table not present' };
    const { rowCount } = await pool.query(
      "DELETE FROM events WHERE created_at < NOW() - INTERVAL '90 days'"
    );
    return { deleted: rowCount, table: 'events' };
  },
});

/**
 * Clean up old webhook delivery logs (older than 30 days)
 */
registerCronJob('cleanup:login-attempts', {
  interval: '1h',
  description: 'Delete login attempt records older than 24 hours',
  handler: async () => {
    const { rowCount } = await pool.query(
      "DELETE FROM login_attempts WHERE created_at < NOW() - INTERVAL '24 hours'"
    ).catch(() => ({ rowCount: 0 }));
    return { deleted: rowCount, table: 'login_attempts' };
  },
});

registerCronJob('cleanup:idempotency-keys', {
  interval: '1h',
  description: 'Delete idempotency keys older than 24 hours',
  handler: async () => {
    const { rowCount } = await pool.query(
      "DELETE FROM idempotency_keys WHERE created_at < NOW() - INTERVAL '24 hours'"
    ).catch(() => ({ rowCount: 0 }));
    return { deleted: rowCount, table: 'idempotency_keys' };
  },
});

registerCronJob('cleanup:webhook-logs', {
  interval: '1d',
  description: 'Delete webhook delivery logs older than 30 days',
  handler: async () => {
    const t = await pool.query("SELECT to_regclass('public.webhook_delivery_logs') AS t");
    if (!t.rows[0].t) return { deleted: 0, table: 'webhook_delivery_logs', skipped: 'table not present' };
    const { rowCount } = await pool.query(
      "DELETE FROM webhook_delivery_logs WHERE created_at < NOW() - INTERVAL '30 days'"
    );
    return { deleted: rowCount, table: 'webhook_delivery_logs' };
  },
});

/**
 * Clean up old read notifications (older than 60 days)
 */
registerCronJob('cleanup:notifications', {
  interval: '1d',
  description: 'Delete read notifications older than 60 days',
  handler: async () => {
    const t = await pool.query("SELECT to_regclass('public.notifications') AS t");
    if (!t.rows[0].t) return { deleted: 0, table: 'notifications', skipped: 'table not present' };
    const { rowCount } = await pool.query(
      "DELETE FROM notifications WHERE read = true AND created_at < NOW() - INTERVAL '60 days'"
    );
    return { deleted: rowCount, table: 'notifications' };
  },
});

/**
 * Log database table sizes (monitoring)
 */
registerCronJob('monitor:db-stats', {
  interval: '6h',
  description: 'Log database table sizes for monitoring',
  handler: async () => {
    const counts = {};
    try {
      const r = await pool.query('SELECT COUNT(*) as c FROM attachments');
      counts.attachments = parseInt(r.rows[0].c);
    } catch (e) { counts.attachments = 'error'; }
    try {
      const r = await pool.query('SELECT COUNT(*) as c FROM comments');
      counts.comments = parseInt(r.rows[0].c);
    } catch (e) { counts.comments = 'error'; }
    try {
      const r = await pool.query('SELECT COUNT(*) as c FROM invites');
      counts.invites = parseInt(r.rows[0].c);
    } catch (e) { counts.invites = 'error'; }
    try {
      const r = await pool.query('SELECT COUNT(*) as c FROM projects');
      counts.projects = parseInt(r.rows[0].c);
    } catch (e) { counts.projects = 'error'; }
    try {
      const r = await pool.query('SELECT COUNT(*) as c FROM subscriptions');
      counts.subscriptions = parseInt(r.rows[0].c);
    } catch (e) { counts.subscriptions = 'error'; }
    try {
      const r = await pool.query('SELECT COUNT(*) as c FROM tasks');
      counts.tasks = parseInt(r.rows[0].c);
    } catch (e) { counts.tasks = 'error'; }
    // #18: the raw per-table totals are PLATFORM-WIDE (cron has no tenant context).
    // Keep them in server-side ops logs only; the value returned here is persisted to
    // the tenant-accessible admin cron log, so it must NOT leak cross-tenant counts.
    console.log('📊 DB Stats (platform ops):', JSON.stringify(counts));
    return { ok: true, monitoredTables: Object.keys(counts).length, loggedAt: new Date().toISOString() };
  },
});

/**
 * Heartbeat — log that server is alive
 */
registerCronJob('heartbeat', {
  interval: '5m',
  description: 'Log server heartbeat for uptime monitoring',
  handler: async () => {
    const mem = process.memoryUsage();
    return {
      uptime: Math.floor(process.uptime()) + 's',
      heapMB: Math.round(mem.heapUsed / 1024 / 1024),
      rssMB: Math.round(mem.rss / 1024 / 1024),
    };
  },
});
