/**
 * ⏰ Cron Scheduler Service
 * Auto-generated by Backend Factory
 *
 * Lightweight in-process scheduler.
 * For production, use node-cron or BullMQ repeatable jobs.
 */

const jobs = {};
const timers = {};
const executionLog = [];
const MAX_LOG_SIZE = 500;
let isRunning = false;

/**
 * Parse human-readable interval to milliseconds
 * Supports: '30s', '5m', '1h', '6h', '1d', '1w'
 */
function parseInterval(interval) {
  if (typeof interval === 'number') return interval;
  const match = String(interval).match(/^(\d+)\s*(s|m|h|d|w)$/);
  if (!match) throw new Error('Invalid interval: ' + interval + '. Use: 30s, 5m, 1h, 6h, 1d, 1w');
  const num = parseInt(match[1]);
  const unit = match[2];
  const multipliers = { s: 1000, m: 60000, h: 3600000, d: 86400000, w: 604800000 };
  return num * multipliers[unit];
}

/**
 * Register a scheduled job
 * @param {string} name - unique job name
 * @param {object} opts - { interval, handler, enabled, runOnStart, description }
 */
export function registerCronJob(name, opts) {
  const {
    interval,
    handler,
    enabled = true,
    runOnStart = false,
    description = '',
  } = opts;

  const intervalMs = parseInterval(interval);

  jobs[name] = {
    name,
    interval,
    intervalMs,
    handler,
    enabled,
    runOnStart,
    description,
    lastRun: null,
    nextRun: null,
    runCount: 0,
    errorCount: 0,
    lastError: null,
  };

  if (isRunning && enabled) startJob(name);
  return jobs[name];
}

/**
 * Start a single job's timer
 */
function startJob(name) {
  const job = jobs[name];
  if (!job || !job.enabled) return;

  if (timers[name]) clearInterval(timers[name]);

  async function execute() {
    const startTime = Date.now();
    try {
      const result = await job.handler();
      job.runCount++;
      job.lastRun = new Date().toISOString();
      job.nextRun = new Date(Date.now() + job.intervalMs).toISOString();

      logExecution(name, 'success', Date.now() - startTime, result);
    } catch (err) {
      job.errorCount++;
      job.lastError = err.message;
      logExecution(name, 'error', Date.now() - startTime, null, err.message);
      console.error('⏰ Cron job failed [' + name + ']:', err.message);
    }
  }

  if (job.runOnStart) execute();
  timers[name] = setInterval(execute, job.intervalMs);
}

function logExecution(name, status, durationMs, result, error) {
  executionLog.push({
    job: name,
    status,
    durationMs,
    result: result ? JSON.stringify(result).substring(0, 200) : null,
    error: error || null,
    executedAt: new Date().toISOString(),
  });
  if (executionLog.length > MAX_LOG_SIZE) executionLog.shift();
}

/**
 * Start all enabled cron jobs
 */
export function startAllCronJobs() {
  isRunning = true;
  console.log('⏰ Starting cron scheduler...');
  for (const name of Object.keys(jobs)) {
    if (jobs[name].enabled) startJob(name);
  }
  console.log('⏰ ' + Object.keys(jobs).length + ' jobs registered');
}

/**
 * Stop all cron jobs
 */
export function stopAllCronJobs() {
  isRunning = false;
  for (const name of Object.keys(timers)) {
    clearInterval(timers[name]);
    delete timers[name];
  }
  console.log('⏰ All cron jobs stopped');
}

/**
 * Enable a job
 */
export function enableJob(name) {
  if (!jobs[name]) return null;
  jobs[name].enabled = true;
  if (isRunning) startJob(name);
  return jobs[name];
}

/**
 * Disable a job
 */
export function disableJob(name) {
  if (!jobs[name]) return null;
  jobs[name].enabled = false;
  if (timers[name]) {
    clearInterval(timers[name]);
    delete timers[name];
  }
  return jobs[name];
}

/**
 * Manually trigger a job
 */
export async function runJobNow(name) {
  const job = jobs[name];
  if (!job) throw new Error('Job not found: ' + name);
  const start = Date.now();
  const result = await job.handler();
  job.runCount++;
  job.lastRun = new Date().toISOString();
  logExecution(name, 'manual', Date.now() - start, result);
  return result;
}

/**
 * Get all job stats
 */
export function getCronStats() {
  return {
    running: isRunning,
    totalJobs: Object.keys(jobs).length,
    enabledJobs: Object.values(jobs).filter((j) => j.enabled).length,
    jobs: Object.values(jobs).map((j) => ({
      name: j.name,
      interval: j.interval,
      enabled: j.enabled,
      runCount: j.runCount,
      errorCount: j.errorCount,
      lastRun: j.lastRun,
      nextRun: j.nextRun,
      lastError: j.lastError,
      description: j.description,
    })),
    recentExecutions: executionLog.slice(-20),
  };
}

process.on('SIGTERM', stopAllCronJobs);
process.on('SIGINT', stopAllCronJobs);
