/**
 * ⏰ Cron Admin Routes
 * Auto-generated by Backend Factory
 */

import { getCronStats, enableJob, disableJob, runJobNow } from '../cron/cronService.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';

export function registerCronRoutes(app) {

  // Get all cron stats
  app.get('/api/v1/admin/cron', requireAuth, requireRole('admin'), (req, res) => {
    res.json(getCronStats());
  });

  // Enable a job
  app.post('/api/v1/admin/cron/:name/enable', requireAuth, requireRole('admin'), (req, res) => {
    const job = enableJob(req.params.name);
    if (!job) return res.status(404).json({ error: 'Job not found' });
    res.json({ enabled: true, job });
  });

  // Disable a job
  app.post('/api/v1/admin/cron/:name/disable', requireAuth, requireRole('admin'), (req, res) => {
    const job = disableJob(req.params.name);
    if (!job) return res.status(404).json({ error: 'Job not found' });
    res.json({ disabled: true, job });
  });

  // Trigger a job manually
  app.post('/api/v1/admin/cron/:name/run', requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const result = await runJobNow(req.params.name);
      res.json({ executed: true, result });
    } catch (err) {
      res.status(err.message.includes('not found') ? 404 : 500).json({ error: err.message });
    }
  });

}
