/**
 * ⏰ Reminder Jobs
 * Auto-generated by Backend Factory
 */

import { pool } from '../db/pg.js';
import { registerCronJob } from './cronService.js';

// Domain events (no-op if no feature/notification subscribes)
let publishDomainEvent = () => {};
try {
  const { publishDomainEvent: _pd } = await import('../events/dispatcher.js');
  publishDomainEvent = _pd;
} catch (_) {}

/**
 * Remind about invites due soon (within 24h)
 */
registerCronJob('reminder:invite:due-soon', {
  interval: '1h',
  description: 'Find invites due within 24 hours',
  handler: async () => {
    const { rows: tenants } = await pool.query(
      'SELECT DISTINCT tenant_id FROM users WHERE is_active = true AND deleted_at IS NULL'
    );
    const allRows = [];
    for (const { tenant_id } of tenants) {
      const { rows } = await pool.query(
        `SELECT * FROM invites
         WHERE expires_at BETWEEN NOW() AND NOW() + INTERVAL '24 hours'
         AND tenant_id = $1 AND deleted_at IS NULL`,
        [tenant_id]
      );
      // DELIVERY (not just counting): publish reminder_due for rows entering the
      // FINAL hour of the window ([23h,24h] ahead). The job runs hourly, so each
      // row is reminded exactly once — publishing the whole 24h window would
      // re-remind every row on every run.
      const _bandStart = Date.now() + 23 * 60 * 60 * 1000;
      for (const r of rows) {
        if (new Date(r.expires_at).getTime() >= _bandStart) {
          publishDomainEvent('invite', 'reminder_due', tenant_id, { record: r });
        }
      }
      allRows.push(...rows);
    }
    const rows = allRows;
    if (rows.length > 0) {
      console.log('⏰ ' + rows.length + ' invite(s) due within 24h');
    }
    return { dueSoon: rows.length, inviteIds: rows.map((r) => r.id) };
  },
});

/**
 * Expire overdue invites (daily)
 */
registerCronJob('expire:invite:overdue', {
  interval: '1d',
  description: 'Move overdue invites to expired',
  handler: async () => {
    const { rowCount } = await pool.query(
      `UPDATE invites SET status = 'expired', updated_at = NOW()
       WHERE expires_at < NOW() AND deleted_at IS NULL
       AND status IN ('pending')`
    );
    if (rowCount > 0) console.log('⏳ ' + rowCount + ' overdue invite(s) expired');
    return { expired: rowCount };
  },
});

/**
 * Remind about projects due soon (within 24h)
 */
registerCronJob('reminder:project:due-soon', {
  interval: '1h',
  description: 'Find projects due within 24 hours',
  handler: async () => {
    const { rows: tenants } = await pool.query(
      'SELECT DISTINCT tenant_id FROM users WHERE is_active = true AND deleted_at IS NULL'
    );
    const allRows = [];
    for (const { tenant_id } of tenants) {
      const { rows } = await pool.query(
        `SELECT * FROM projects
         WHERE deadline BETWEEN NOW() AND NOW() + INTERVAL '24 hours'
         AND tenant_id = $1 AND deleted_at IS NULL`,
        [tenant_id]
      );
      // DELIVERY (not just counting): publish reminder_due for rows entering the
      // FINAL hour of the window ([23h,24h] ahead). The job runs hourly, so each
      // row is reminded exactly once — publishing the whole 24h window would
      // re-remind every row on every run.
      const _bandStart = Date.now() + 23 * 60 * 60 * 1000;
      for (const r of rows) {
        if (new Date(r.deadline).getTime() >= _bandStart) {
          publishDomainEvent('project', 'reminder_due', tenant_id, { record: r });
        }
      }
      allRows.push(...rows);
    }
    const rows = allRows;
    if (rows.length > 0) {
      console.log('⏰ ' + rows.length + ' project(s) due within 24h');
    }
    return { dueSoon: rows.length, projectIds: rows.map((r) => r.id) };
  },
});

/**
 * Find stale subscriptions (no updates in 7 days)
 */
registerCronJob('reminder:subscription:stale', {
  interval: '1d',
  description: 'Find subscriptions with no activity for 7 days',
  handler: async () => {
    const { rows: tenants } = await pool.query(
      'SELECT DISTINCT tenant_id FROM users WHERE is_active = true AND deleted_at IS NULL'
    );
    const allRows = [];
    for (const { tenant_id } of tenants) {
      const { rows } = await pool.query(
        `SELECT id, status, updated_at FROM subscriptions
         WHERE updated_at < NOW() - INTERVAL '7 days'
         AND tenant_id = $1 AND deleted_at IS NULL
         AND status NOT IN ('cancelled')
         LIMIT 100`,
        [tenant_id]
      );
      allRows.push(...rows);
    }
    const rows = allRows;
    if (rows.length > 0) {
      console.log('⚠️  ' + rows.length + ' stale subscription(s) found');
    }
    return { stale: rows.length };
  },
});

/**
 * Remind about tasks due soon (within 24h)
 */
registerCronJob('reminder:task:due-soon', {
  interval: '1h',
  description: 'Find tasks due within 24 hours',
  handler: async () => {
    const { rows: tenants } = await pool.query(
      'SELECT DISTINCT tenant_id FROM users WHERE is_active = true AND deleted_at IS NULL'
    );
    const allRows = [];
    for (const { tenant_id } of tenants) {
      const { rows } = await pool.query(
        `SELECT * FROM tasks
         WHERE due_date BETWEEN NOW() AND NOW() + INTERVAL '24 hours'
         AND tenant_id = $1 AND deleted_at IS NULL`,
        [tenant_id]
      );
      // DELIVERY (not just counting): publish reminder_due for rows entering the
      // FINAL hour of the window ([23h,24h] ahead). The job runs hourly, so each
      // row is reminded exactly once — publishing the whole 24h window would
      // re-remind every row on every run.
      const _bandStart = Date.now() + 23 * 60 * 60 * 1000;
      for (const r of rows) {
        if (new Date(r.due_date).getTime() >= _bandStart) {
          publishDomainEvent('task', 'reminder_due', tenant_id, { record: r });
        }
      }
      allRows.push(...rows);
    }
    const rows = allRows;
    if (rows.length > 0) {
      console.log('⏰ ' + rows.length + ' task(s) due within 24h');
    }
    return { dueSoon: rows.length, taskIds: rows.map((r) => r.id) };
  },
});

